### ISSUE TITLE
Document somehow that observation_period table has 0 rows

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#102]
Many non-claims dataset have no rows in observation_period table.
For Heel and other analyses, it may be good to know that.
If the table is empty, all analyses 100-118 will be null.
Having a measure 119 that would say 0 if the table has no data would be useful. 

For achilles-wiki  - this is needed so that this wiki function can only rely on pre-computed analyses.

**Comment by cgreich** [comment]
Vojtech:

That should not be the case. Not sure which non-claims datasets you are talking about, but they would be non-compliant if that were true. Any data in the main clinical tables should have records only within an active Observation Period. If you have no Observation Period, those tables should be empty as well. The ETL should be fixed for these databases.

Generally, in an EMR database, if you have no way of knowing when a patient was actually observed, take the very first and very last record and define the Observation Period that way. It is probably not always correct, but the best guess you can make.

**Comment by vojtechhuser** [comment]
The dataset that has that problem is 'SynPUF 1k' dataset.
That is a great suggestion for a simple ETL addition - if there is a script
that somehow populates the observation_period table based on first and last
visit, I think that would be a great addition. (not that hard to do, also)

I don't have write privileges to fix that for the synpuf data.

**Comment by chrisknoll** [comment]
If there is a repository for the sympuf ETL on git, that would be the place to report the issue. Otherwise, contact the etl owner via the ohdsi forums.

**Comment by vojtechhuser** [comment]
Synpuf data now has correct observation_period table.
