### ISSUE TITLE
Heel (DQ): Percentage of non-numerical measurement records

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#105]
@vojtechhuser, 

Hey, just ran the ACHILLES and got this error:

`WARNING: percentage of non-numerical measurement records exceeds general population threshold`

I see you hard coded to 80%.  Where did that come from?  When you say "general population threshold" it sounds like you compared against other DBs.

Either way, it may be nicer to say "WARNING: percentage of non-numerical measurement records exceeds 80%"

**Comment by ericaVoss** [comment]
Also, for DBs that only have procedure claims records that are considered measurements (e.g. CPT4 '85025-Blood count; complete (CBC), automated (Hgb, Hct, RBC, WBC and platelet count) and automated differential WBC count`), this error will fire.  May it make sense to do something that includes looking at the type of record that is coming across?

**Comment by vojtechhuser** [comment]
In the StudySandbox, there is a data quality study that will collect from
multiple sites this number and threshold will be decided based upon this
analysis.

I am hoping J&J will participate.

The actual number is in the new table achilles_results_derived.
Once you re-run achilles on datasets, the data for such DQ study will be
available.
I plan to add many other similar measures for which we will deside some
general population range.
 I am also suggesting some dataset metadata that designate a datset as
general population.

**Comment by vojtechhuser** [comment]
Patrick suggested to have new type of output (NOTIFICATION) . So this was changed to notification.
