### ISSUE TITLE
Condition Type report not returning any rows

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#107]
There is an issue in exportToJson for condition reports where we are looking for concepts in the domain 'Condition Type'.  This domain id no longer exists (is replaced with domain Concept Type, and the concept type is in 'concept_class_id' and this field has 'Condition Type' in it.

**Comment by alondhe** [comment]
Chris, I can confirm that the new branch "issue_107" resolves this issue for 3 data sources I've tested. Thanks!
