### ISSUE TITLE
Heel check for cdm_source table and Add contents of cdm_source table to Achilles output (and show in Atlas)

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Achilles#114]
It would be helpful if Achilles could show the version of the vocabulary. For one, this would be a silent reminder for people to update if they're still using a very old version...

``` sql
SELECT vocabulary_version
FROM vocabulary
WHERE vocabulary_id = 'none'
```

**Comment by vojtechhuser** [comment]
I can add this. Just pick an ID for it:


--{2020 IN (@list_of_analysis_ids)}?{
-- 2020	Vocab version
insert into @results_database_schema.ACHILLES_results (analysis_id, stratum_1)
select 2020 as analysis_id,  --2000 is IRIS range (assigned by Patrick), can be changed to other ID
	vocabulary_version as stratum_1 
from
	@vocabulary_database_schema.vocabulary 
where vocabulary_id='None';  
;
--}

**Comment by schuemie** [comment]
I modified the topic of this issue. We should include everything in the [cdm_source table](https://github.com/OHDSI/CommonDataModel/blob/master/Sql%20Server/OMOP%20CDM%20ddl%20-%20SQL%20Server.sql#L196) in the Achilles output, and show it in Achilles Web:
```sql
CREATE TABLE cdm_source 
    (  
     cdm_source_name					VARCHAR(255)	NOT NULL,
	 cdm_source_abbreviation			VARCHAR(25)		NULL,
	 cdm_holder							VARCHAR(255)	NULL,
	 source_description					VARCHAR(MAX)	NULL,
	 source_documentation_reference		VARCHAR(255)	NULL,
	 cdm_etl_reference					VARCHAR(255)	NULL,
	 source_release_date				DATE			NULL,
	 cdm_release_date					DATE			NULL,
	 cdm_version						VARCHAR(10)		NULL,
	 vocabulary_version					VARCHAR(20)		NULL
    ) 
;
```

**Comment by chrisknoll** [comment]
Ok, this is easy enough, we can add a summary JSON file in the export that just reads this file. We can call it cdm_source.json and we can present it on all the report pages in Achilles Web.

**Comment by vojtechhuser** [comment]
Note that we are trying to extend the table. See the proposal here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:next_cdm:metadata

**Comment by vojtechhuser** [comment]
Is there a webAPI call now that does this (by any chance?).  Also, checking that at least one row exist in cdm_source is something I woudl like to add to Heel.
