### ISSUE TITLE
ExportToJson hangs at Generating Drug Treemap

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Achilles#115]
The exportToJson function exports the first files, but freezes at the message 'Generating Drug Treemap', at 0 %. I let it run for 2 hours, but no progress at all and R even crashes at some point.
I use the following command to export the json (after running the achilles command):
```
exportToJson(connectionDetails, 
             cdmDatabaseSchema="cdm5", 
             resultsDatabaseSchema = "results_achilles", 
             outputPath = "/Documents/achilles/data",  
             cdmVersion = "5")
```

R version 3.2.4, on Windows machine and the latest version of Achilles (installed with install_github('OHDSI/Achilles').
On my Mac laptop I cannot reproduce this problem.

Does anyone else have this problem?

**Comment by jmbanda** [comment]
Generating the Drug Treemap in some of the instances I have run it takes more than 15 hours to complete. Seems like it hangs, but check your R processes to see if they are active. I haven't had this crash completely on a RedHat environment.

**Comment by chrisknoll** [comment]
Indexing is also a factor but if it works on your Mac (but connecting to the same database) i can't explain that.  I can extract the portion of the trug treemap query that executes and post it here, and you can possibly do a 'show plan' on it to see if there's any issues that the query analyzer reports.  I'll need to know what dialect you are using, can you tell me what RDBMS you are hosting the CDM on?

**Comment by MaximMoinat** [comment]
Thanks for your answer.
In this case the drug exposure table just contained 10,000 rows. That shouldn't take such a long time to complete, right?
Or is there another way, besides making the table smaller, to speed this step up?

**Comment by lofung** [comment]
same happened. Drug Treemap I let it run for 4 days. And it has not returned anything, in a cohort of only 1 million patients.

When I force stop R and extract the SQL, run it in python psycopg2, it returns result in 6 minutes. I do not know what is wrong.
