### ISSUE TITLE
Heel (DQ): For a subset of checks/rules: Allow users of other CDMs to utilize Heel DQ checks

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#116]
Data Quality Initiative introduced DQ CDM.
The goal is evolve Achilles in a way that it can "inspire" even non OHDSI CDM adopters.
So that checks/rules would operate on such measures that abstract out the CDM.

Heel currently has CDM conformance checking rules and DQ rules.

For new DQ rules (on original or derived measures (=analyses)) we should encourage users to think about how this DQ rule would operate on any CDM that is able to produce a stratified analysis.

DevH branch is trying to document the type of the rule and for some rules it tries to abstract out the underlying CDM model. 

So an analysis gets computed (ratio of patient/providers) and a rule that operates on it is "CDM model independent". It only depends on [derived] analyses.

**Comment by vojtechhuser** [comment]
This in fact applies to runing Heel v5 file on precomputations done on CDM v4. I was able to run sucesfully Heel v5 SQL file (and derived measures) on v4 precomputations  (IMEDS, GE dataset)

**Comment by vojtechhuser** [comment]
June 9 updates try to implement this by computing a derived measure first and the rule operating on it is "simpler". It is also using % a lot so non CDM dataset (or v4 datasets) can take advantage of such less-model dependent DQ rules

**Comment by fdefalco** [comment]
Achilles Heel has been superceded by the Data Quality Dashboard.
