### ISSUE TITLE
Achilles 1.2.2 "JDBC update query failed"

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Achilles#120]
The new Achilles release seems to contain an error in the database connection.
When I run achilles(), I get the following error:

`Executing multiple queries. This could take a while
  |=======================================================================       |  91%
Error executing SQL: Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (ERROR: syntax error at or near "}"
  Position: 1)`

The script runs without errors when switching to an older Achilles release (v1.2). 

I call achilles with the following parameters:
`connectionDetails <- createConnectionDetails(dbms="postgresql", 
                                             server="localhost/ohdsi", 
                                             user="postgres", 
                                             password="",
                                             port=5433,
                                             schema="cdm5")`

`achillesResults <- achilles(connectionDetails, 
                            cdmDatabaseSchema="cdm5", 
                            resultsDatabaseSchema = "results_achilles", 
                            cdmVersion = "5",
                            smallcellcount = 5,
                            runHeel = TRUE,
                            validateSchema = FALSE) `

Edit: I am using the 5.0 CDM. Should I set runCostAnalysis to TRUE (although I don't want to run the cost analysis in my case)

**Comment by chrisknoll** [comment]
No, let me push in a fix for this, apologies for that!   The update must have introduced a regression.

**Comment by chrisknoll** [comment]
Ok, I have just updated the release with this fix. Can you pull the release (tag v1.2.2) and let me know if you have any other issues.

**Comment by MaximMoinat** [comment]
Thanks, for now we will work with v1.2. When we switch to cdm 5.1, we will use Achilles v1.2.2 as well.
