### ISSUE TITLE
Review Achilles codebase for impacts from recent vocabulary updates

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#121]
We've uncovered a few cases in Achilles where vocabulary updates have impacted results/reports.  This issue is to track a review of the codebase and make any updates to handle any changes in the vocabulary.

**Comment by mark-velez** [comment]
@chrisknoll can you describe how the results/reports are impacted? We are currently experiencing issues with the visualizations which may possibly be related to the Achilles output after a vocabulary update.

**Comment by chrisknoll** [comment]
One case is 'Unknown Gender' has been replaced with ConceptID 0 (Unmapped).  Another case is that one of the vocabulary IDs for concept types (like condition concept types) has been changed in favor of using a 'concept_class' field in the domain 'Concept Type'.  I'm sure there are many others which is why we need to look through it and see what's impacted in Achilles.

If you are able to dig into the achilles code and understand if it is a visualization code bug or if it is something the exportToJson() call failed to export properly from the achilles R package, please file the issue here and we can reference this issue to track the potential vocabulary issues that are impacting Achilles.

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll

1) We have dug a bit into the Achilles R package and the Atlas 'datasources' (formerly AchillesWeb) code and it is not yet clear whether it is a visualization code issue or an issue in exportJSON(). See Atlas Issue [#45](https://github.com/OHDSI/Atlas/issues/137).

2) Is there a running list of these impacts that we can consult/contribute to? If not should, might it be advisable to create one here?

**Comment by chrisknoll** [comment]
Hi, @t-abdul-basser . No I don't think there's a list yet, this issue is just a reminder to myself that a list needs to be created.  I think either we can add reports to this issue or we can create new issues and reference this one just to group them all together.

**Comment by t-abdul-basser** [comment]
Makes sense. Thanks!
