### ISSUE TITLE
Laboratory (and other) data characterization and data quality (Obs, Meas)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#123]
With rich EHR laboratory data, I propose Achilles and Heel try to characterize and analyze this data.

Ideally, weight (and LDL) are measured using a consistent unit.
In practice, we can't enforce that, but we can count number of units used within given concept_id-event (Lab, Obs) and report this count. For events that use only single unit - we report those as of high quality.

Similarly, we can look at the [numeric] ranges of any [numeric] observation or measurements.

Is there any strong oposition?

**Comment by pbr6cornell** [comment]
Achilles already contains the count of measurements by unit concept id, and
a distribution of value_as_number stratified by measurement_concept_id and
unit_concept_id.  What other statistic are you looking to generate?

**Comment by PRijnbeek** [comment]
We had some studies where we want to include people that have at least two BMI values etc.
Recently, we got questions from companies that needed this information for other measurements as well.

We made piecharts and histograms of the frequency of measurements. 0,1,2,3,4,5,5+

I would be in favour of adding this for feasibility questions.

Peter

Verstuurd vanaf mijn iPhone

Op 9 jun. 2016 om 17:15 heeft Patrick Ryan <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Achilles already contains the count of measurements by unit concept id, and
a distribution of value_as_number stratified by measurement_concept_id and
unit_concept_id. What other statistic are you looking to generate?

**Comment by vojtechhuser** [comment]
I wrote the request and later found out that 80% of analyses are already there. (but not displayed by AchillesWeb).
So it was my mistake. However, what Peter suggest is something new and I like that idea.  (and will think about it)

**Comment by vojtechhuser** [comment]
A new rule (#35) addresses this partially.

**Comment by vojtechhuser** [comment]
forum post created for that. to check LDL values, one has to be able to "standardize" units for LDL and preferred code (e.g., LOINC).    Weight is harder. LOINC vs SNOMED code. (both are allowed; standard concepts)
