### ISSUE TITLE
Add Heel rule of encounter outside of visit window

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#126]
Hi,

Can we add a rule to Heel to check if any encounter (procedure occurrence, observation, condition occurrence, drug exposure, etc) occurs outside of the visit_start_date and visit_end_date of its associated visit?

Thanks,
Ajit

**Comment by vojtechhuser** [comment]
That would require new analysis first.
A note on related existing rules is that we check for patients with no visits (and if those have non-visit events, they violate your new proposed rule) (so partial check is already there).

But  agree with the proposed new rule.

**Comment by vojtechhuser** [comment]
I think drug prescription without a visit is a valid event.

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
