### ISSUE TITLE
Run Achilles only on Study Cohort

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Achilles#131]
Is there a way to run Achilles only on a specific cohort? (Other than creating a new schema with a subset of the data.) 
This could give interesting descriptives on our study population of interest.

And if it is not possible, do you think it be a useful new feature for Achilles?

**Comment by pbr6cornell** [comment]
There is a tool called heracles which is exactly what you are looking
for...achilles for a cohort.  Check it out!

**Comment by MaximMoinat** [comment]
Thanks for your answer!

I even see that Heracles is integrated in the new Atlas version, under 'Cohort Reporting'. That is great!
