### ISSUE TITLE
Database Connector error when using extraSettings for PostgressSQL

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Achilles#134]
Connecting using PostgreSQL driver
Error in paste(connectionString, "?", extraSettings, sep = "") : 
  object 'connectionString' not found

The connectionString is never created, so the past fails.

**Comment by schuemie** [comment]
Oops! My bad. Latest version of DatabaseConnector should fix that (https://github.com/OHDSI/DatabaseConnector/commit/849a2f47dadbbfb2c4ac507d5bd91e5133e2aae9)) 

Could you update and try again?
