### ISSUE TITLE
int to float change in achilles_heel_result table

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#138]
I would like to propose to change the data type of column row_cnt to  float. (currently [big]int).

Some rules need to document (output) a number with decimal places  (% of unmaped source values) and int output would round this to 0.

Any disagreement? 
(I would prefer not to change the column name - but that could be done as well.)

**Comment by chrisknoll** [comment]
The row_cnt column is used to store the number of rows.  I am not sure how you could come up with '1.273 rows' as a result.  If you want a % of a number, you'd combine the row_count from your analysis as the numerator with the row_count from the analysis that gives you the total rows, and display that as a % (n/m * 100) in your report query.  If you must have a column to store row_pct then a new column should be added.

**Comment by pbr6cornell** [comment]
Which table are you referring to?   We should NOT change ACHILLES_RESULTS
or ACHILLES_RESULTS_DIST.  Those should explicitly only contains counts,
which should be typed as 'bigint'.

For the new ACHILLES_RESULTS_DERIVED table that is under development, I
would favor having some column like 'statistic_value', which could be of
type 'float'.

**Comment by vojtechhuser** [comment]
the table name is in the title of the issue and it is achilles_heel_results

**Comment by vojtechhuser** [comment]
@chrisknoll the plan is update achilles web to surface better the "depth of the problem" and even allow drill down ability.  Currently AchillesWeb does mere listing of most columns from achilles_heel_results. Depth of the problem is unstructured in the text of the warning. (which I think is not ideal)

**Comment by vojtechhuser** [comment]
marking it closed. Subsumed by #146
