### ISSUE TITLE
Drill Down feature for Heel Rules

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#139]
If a user is notified about errors in data, allow him/her to investigate which data rows (or other items, such as drug or lab test) trigger this error   (requested by Patrick Ryan in email). (linked issue for web is https://github.com/OHDSI/AchillesWeb/issues/55

**Comment by vojtechhuser** [comment]
Knowledge Base for this feature is now part of Achilles. Authors of new rules are encouraged to provide drill down views for their new DQA rules.

**Comment by vojtechhuser** [comment]
related UI issue here https://github.com/OHDSI/Atlas/issues/266

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
