### ISSUE TITLE
Exceed Threshold

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#144]
For any of the Notifications that say "exceeds threshold" it would be nice if threshold was defined as so we don't have to log into GitHub to figure out what threshold means.

For example:

``` text
NOTIFICATION: Percentage of patients with no visits exceeds threshold
```

In my case here there are 800K people out of 9M that have no visits.  About 8%.  What was the threshold and why was it important?  Maybe if the warning told me 8% of my people have no visits - I would then say that sounds fine and go on with my life.  :)

**Comment by vojtechhuser** [comment]
The vision is to have in the future multiple thresholds - warning threshold and error threshold.
To easily get current "hard coded" thresholds, you can see rules.CSV file.

The achilles heel table only allows integer numbers. So 0.08 becomes 0 and 0.51 becomes 1. I can't seem to talk others into allowing real numbers.  See it here: #138

**Comment by chrisknoll** [comment]
Yes, @vojtechhuser , as explained in the other thread, the column you are referring to is called 'row_cnt', and the purpose of that row is to indicate the number of rows impacted by this check.  **You can not have 3.98 rows.**

**Comment by ericaVoss** [comment]
I can't find the rules.CSV, could you link me to it?

Couldn't you cast it as a string and pass it in the description?  Something like this:

```
NOTIFICATION: Percentage of patients with no visits exceeds 10%, this CDM was at 15%.
```

This gives me enough information to make a decision on the notification without having to hunt for additional information.  I would like to avoid having to go find a file to review the ACHILLES HEEL results.  We have a 11 CDMs at the moment and we review HEELs every month.

**Comment by t-abdul-basser** [comment]
@ericaVoss I agree fully that we need to modify these descriptions so that they read as per your example. It would enhance the utility of the Achilles reports significantly. Observation similar to yours have been made multiple times here at Columbia. 

@vojtechhuser I would suggest that we attempt to implement this without modifying the column (primarily for the reason that @chrisknoll mentions here and in the [#138](https://github.com/OHDSI/Achilles/issues/138).

**Comment by vojtechhuser** [comment]
The CSV link is correct. 
Casting would be possible. And I will try to improve it.

**Comment by ericaVoss** [comment]
@t-abdul-basser  thx for sharing the link!

@vojtechhuser  I'm not sure if you were throwing those questions out into the universe or wanting a reply.  But I can reply.  :)

I believe it is important work to set an appropriate threshold but I always struggle with what is the right answer.  The right answer for one DB will not be the right one for another (e.g. in commercial claims it 100% makes sense to have a person who never has a visit - think of healthy 20 somethings).  

As a user of the HEEL, I kind of don't care what things are set to through (although again I acknowledge that is important work), I just want to quickly be able to get through HEEL ignore things that are nonsense for the DB I'm reviewing for.  Each of my CDMs throw about 40 errors/warnings/notifications so the quicker I can get through them the better.

Additionally I agree and think there is an opportunity to improve HEEL.  For example, we need issues to throw unique identifiers (even if that is a composite key) so that we could create a method for knowing issues that were already reviewed in previous loads.  Right now there isn't a way to uniquely identify an issue.  But this is a comment for another thread and another day.

**Comment by chrisknoll** [comment]
@vojtechhuser, are you clear on the purpose of the row_cnt column?  You addressed the other points above but not that one.

**Comment by vojtechhuser** [comment]
I am fine with the row_cnt column. A related question is: What is the purpose of Achilles_heel_results table.  
How it fits into reporting. How Heel output should be structured and consumed.

Especially what is the purpose of the error text column.  As informatician, I am forcing clinicians to produce structured data and that means I should be producing structured data whenever I can. 

So if I have structured data on threshold and float value over threshold, I should not be putting them into a free text column.

**Comment by chrisknoll** [comment]
Heel_results is just a collection of error/warning messages. You should be able to see this by looking at the schema: analysis_id, achilles_heel_warning, rule_id, record_count

From this structure, we create a tabular report view in AchillesWeb to inform the user what errors/warnings we found after executing the achilles heel script.

That's it, that's all it does, it was never any more complicated than that.  If you're looking for a more complex table schema, then that's something that can be added to the package, and then the UI has to be written to pull data from this other schema to present those results.  At this point, however, I haven't seen any concrete design on how this sort of thing should be structured in the database and then presented in the UI.  

To answer your question: if you are defining a new HEEL check and you want to report it (such as a certain threshold is exceeded), you can make that threshold a parameter to the achilles Heel call, and if it trips then you should be writing a message to the HEEL_results table with a message like 'Warning: X exceeds threshold {threshold value}.'.and if there's a count of rows that are involved in this threshold, then put that in record_count.  If you don't want to parameterize it and put it hard-coded in the script, that's fine too, but I think that's not flexible.

**Comment by vojtechhuser** [comment]
Forget the current hard coding for the moment and current status quo.

For 2017 - here is my proposal: At the time of Heel execution - a default threshold is used and error generated. 
But a user is able to change threshold up or down (when viewing data in Achilles). 
Each rule generates a value (stored in derived measures or an analysis) and at Heel viewing time, threshold logic is re-executed.

Hence Heel result table is a place to store the initial errors. - But tinkering later is possible.

**Comment by chrisknoll** [comment]
The threshold is something used at HEEL-analysis time, not reporting time, so I'm not sure how you can specify a threshold after the reports were generated.

Tinkering later is not a modality that we have thought about, and i'm not sure of the feasibility of recalculating all statistics in order to find new heel messages.  What we've done in this sort of thing is pre-calculated different threshold levels and let the user choose from the set of threholds, but it's never been supported that people can do ad-hoc analysis on the achilles results.

**Comment by t-abdul-basser** [comment]
Some comment on the proposal as I understand it:

Default threshold values are fine as long as they are documented, presented clearly in the web report as per @ericaVoss observations and are configurable. For the sake of simplicity, I would prefer that *administrators* configure these thresholds settings  (e.g. via runAchilles parameters or configuration files) prio to report generation (i.e. prior to running Achilles).

**Comment by t-abdul-basser** [comment]
@chrisknoll I agree fully "tinkering later" I would not suggest that it be part of the proposed effort as it would constitute a major modification to the current analysis-generation-view process and the underlying code base.

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
