### ISSUE TITLE
Improvements to Heel Report (how it is consumed by users) (dynamic thresholds, underlying measure)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#146]
How heel output is currently consumed is a view of a SQL table. 

feature 1
Ideally, a drill down feature would allow a more interactive view. (see what concepts trigger an error).

feature 2
Another feature is adjusting thresholds. A rule is really a view of a derived measure, and a user can dial up or down a threshold and see if the rule fires or not (dynamically).
For example % of patients without visit (current threshold can be moved from 10% to 20%) and a notification would dynamically display (or not). That would be possible because a derived measure computes the rule logic and a simple threshold-logic would either display it or not.

Current logic is hardcode everything into SQL logic (with casting). With dynamic thresholds, this hard coding would be a problem. A rule description would simply refer to a changeable threshold.

This was driven by @pbr6cornell request to have a derived measure have a logic of the DQA idea and the underlying rule be rather simple view of the derived logic. So a user can see the "assesed" DQA parameter no matter if the rule "fired" or not.

**Comment by vojtechhuser** [comment]
related atlas issue here: https://github.com/OHDSI/Atlas/issues/266

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
