### ISSUE TITLE
Handling CDM 5.0.1 and 5.1 and future versions

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#147]
I do not believe ACHILLES is CDM 5.0.1 ready.  Just opening this issue to get us to start thinking about it.

My work around is to run ACHILLES with `runCostAnalysis = FALSE` to hopefully ignore the cost table(s) until we are ready.

**Comment by t-abdul-basser** [comment]
Thanks @ericaVoss. Are there issues of which you are ware other than handling the cost tables than make Achilles not CDM 5.0.1-ready?

**Comment by ericaVoss** [comment]
@t-abdul-basser  - not yet.  But I should in the next couple of weeks as we have 2 coming online soon.  I can get back to you on where it chokes.  I think if we runCostAnalysis = FALSE we will be fine - but if we ran the full ACHILLES it would barf on the new tables.

**Comment by t-abdul-basser** [comment]
@ericaVoss Thanks.

**Comment by vojtechhuser** [comment]
Cost pre-computations are not currently used in Achilles Web. I suggest we sequester them into a separate file Achilles-cost-5.0.sql and leave them there until we find health economist research who is willing to re-write existing analyses using 5.0.1.

So an achilles.sql will not have legacy 5.0.0 tables there and no runCostAnalysis workaround has to be used.

**Comment by vojtechhuser** [comment]
For refactoring the main sql code - I would also suggest to formally leave v1.4 as the last version that supports v4 and simply focus on v5 (and all the flavors of it)

**Comment by vojtechhuser** [comment]
CDM workgroup just approved version 5.1 with more changes.
I also suggest we remove sunsetted version 4 now. and point to earlier version of achilles for interested folks.

**Comment by t-abdul-basser** [comment]
Excellent. I agree.

**Comment by cgreich** [comment]
@vojtechhuser: Yes, but: 

We need to probably do that with some more splash. Kind of what Microsoft did with Windows XP. Declaure "Time's up for V4, we no longer support". Then they will scream, and you give them another 6 months grace period.

**Comment by vojtechhuser** [comment]
I though I have already done that with my post about v4 on the forum.
http://forums.ohdsi.org/t/sunsetting-strategy-for-v4/1230


 It is now 4 months after the deadline I posted there.

**Comment by cgreich** [comment]
:) Because we discussed it in some obscure Forum, it hasn't happened. We need to announce it really big.

**Comment by chrisknoll** [comment]
And to be fair, the forum post was a proposal, it needs to go beyond a simple 'What do you think about X?'.  Seems people are in favor of the idea, but it needs to be an official milestone on the development roadmap for Achilles.  Once we retire V4 support, that's the type of thing that would involve a major version number bump to the achilles release version.  In other worsds: dropping v4 support isn't a minor feature change to Achilles.

**Comment by vojtechhuser** [comment]
I created a while ago R code that checks for existence of a table. (for 5.2 - the note nlp table can be checked this way)  (by getting a list of tables in a schema) using database connection function for this. 

Is there opposition for doing this in achilles() R code (and not in SQL)? (the only way)
