### ISSUE TITLE
Incorporate Sentinel Data Quality rules (data checks)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#150]
To improve DQ, it is possible to get inspired by published scripts from other groups doing data quality. One such source is Sentinel.

https://www.sentinelsystem.org/sentinel/data/distributed-database-common-data-model/112

**Comment by vojtechhuser** [comment]
weight vital sight checking now implemented; consensus discussion on the OHDSI weekly meeting may be beneficial for other concept level checks

**Comment by alondhe** [comment]
@vojtechhuser can you list specifically what the DQ rules are here?
