### ISSUE TITLE
Default analysis IDs are broken as of May 13th

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#151]
@vojtechhuser ,
  We recently updated our achilles install from GIT (surprisingly very out of date!) and we had a problem where the default analysis ids were being returned as empty.  The .csv file was updated, but I'll go through how we tracked this down:
1. We looked for how the analysisId parameter to achilles is defalted:
   https://github.com/OHDSI/Achilles/blob/428108d94a96d4759241240faee02d369b6c8404/R/Achilles.R#L93

So, it calls getAnalysisDetails() and returns the value of $ANALYSIS_ID (as a list of IDs)
1. We executed getAnalysisDetails()$ANALYSIS_ID and got back 'NULL'

So we looked at the call to getAnalysisDetails() to see what csv is loaded. It's the file "analysisDetails.csv" in the csv folder.
1. We noticed that the column heads were changed from all upper case to lower case and the NA values were replaced with empty ',,' values in the csv value.

So the case changing of ANALYSIS_ID to analysis_id broke achilles, and it's been broken for quite a while. This change was introduced in commit: a1e7dc3945bb9e23196bdc448015f4631fadcc6e.

So, a few questions:

In your own testing, how did the achilles() ever execute if the call to getAnalysisDetails()$ANALYSIS_ID returned null?

What is the impact of changing the NA values in he CSV to empty column values (represnted by ,, in the csv)?

The fix for this error is to either change getAnalysisDetails()$ANALYSIS_ID to getAnalysisDetails()$analysis_id or to revert the csv file back to it's original value.  I'd like to understand the reasoning behind changing it from using NA as a emtpy value to ,, in the csv tho, maybe there was a reason that I don't understand, and I'd like to do the right thing here.

Please let me know ASAP, this is currently broken for anyone who refreshes Achilles from install_github().

-Chris

**Comment by vojtechhuser** [comment]
getAnalysisDetails is not called by main R function. It only gets called if fetch of a given analysis is invoked.

**Comment by vojtechhuser** [comment]
I think it should be fixed in deH8 as of now.

**Comment by vojtechhuser** [comment]
I wish the info would not live in two places. (in a CSV and in the database). I would vote for removing the insert statements for those in Achilles.sql

**Comment by t-abdul-basser** [comment]
@vojtechhuser Ideally we would add a unit test for #151 so you could run the test locally to confirm and so that the `testthat` harness  could run via Travis on check in to confirm.

**Comment by vojtechhuser** [comment]
I agree.
I would have to know what to set to all those variables. https://github.com/OHDSI/Achilles/blob/master/tests/testthat/test-main-achilles.R#L11

Next step after that would be to request NIH firewall exception for each dbms port.

**Comment by chrisknoll** [comment]
It's not just the case issue, also, all the places where you see ,,,, in the file, used to be NA.  See the commit:
https://github.com/OHDSI/Achilles/commit/a1e7dc3945bb9e23196bdc448015f4631fadcc6e

And as far as storing the values in the database, where did you think that the values in the DB are loaed from? They're specified in the .csv file!  It's not that it's in two places (initially) but when you run achilles on a fresh CDM, the data has to get populated into that table from someplace. The CSV is what does this.

**Comment by vojtechhuser** [comment]
@t-abdul-basser , can you please update master with a CSV file that has the column names as upper case. 
(either from devH8) or also in devH8 - file extras/notes.md has the code for such an update  (NA issue can also be fixed that way (using the code there) 

 (I would do that - but I will rather stay away from master until my skills further improve)

**Comment by t-abdul-basser** [comment]
@vojtechhuser  Yes, I will take care of this a submit in a PR.

**Comment by vojtechhuser** [comment]
@t-abdul-basser , if it would help, I can submit a separate PR just with this. @leeevans (the problems with the build may still be there). Perhaps we don't need to wait with a simple case fix for the Travis fix.

**Comment by t-abdul-basser** [comment]
@vojtechhuser submit a PR for this issue is fine. Please do.

@leeevans @vojtechhuser I am experiment with the use of `travis_wait` in _r-travis_ and will update when I confirm that it behaves as expected.

**Comment by vojtechhuser** [comment]
To separate this case problem from Travis CI, I created a separate issue for that.
