### ISSUE TITLE
Checking R code locally vs. on TravisCI

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#158]
Any contributor to Achilles wants to test the code prior the PR.

In order to execute R check commands in the current check R code, it requires that any developer knows all the environmental variables (with a passwords) for all platforms. E.g.,  postgres server name, oracle user name, etc....

**What is the best way for Ajit or me or Taha to test fully the code that would be executed by TravisCI?**  

Without unfirewalled connection to the test servers and knowing all the passwords - it seems to me impossible.

**Comment by msuchard** [comment]
1. Set environment variables for local DB
2. Run tests

E.g.
```{r}
Sys.setenv(CDM5_POSTGRESQL_USER = "user")
Sys.setenv(CDM5_POSTGRESQL_PASSWORD = "password")
Sys.setenv(CDM5_POSTGRESQL_SERVER = "server")
devtools::test()
```

**Comment by chrisknoll** [comment]
I made an issue in #165 and if this is the steps to run it locally, can we have travis init scripts do this exact same thing during the travis job?
