### ISSUE TITLE
Make env variables available in Travis-CI regardless of source of PR

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#165]
We currently have a problem described in #154 where the build is failing, but the core problem is that the environment variables set here https://travis-ci.org/OHDSI/Achilles/settings do not seem to be available when a PR is submitted from a separate repository. Considering this is the normal case of where external collaborators will submit changes from, we need to make this case work.

Proposal:
In the travis start-up scripts, we have a .sh file which will set the required environment variables needed to run the tests.  This file can be .ignored or just documented that the file should exist in a certain location in order to set the approirate variables so that the tests can work.

We remove the settings from the repository because it doesn't work with external repository PRs

@msuchard , @schuemie , let me know your thoughts.

**Comment by msuchard** [comment]
It is no problem to make Travis-CI environment variables be available from any PR.  Just write them _unencrypted_ in the `.travis.yml` file.  The lack of encryption seems like a very, very bad idea.

**Comment by chrisknoll** [comment]
Yeah, Indeed. So I did some digging here:
https://docs.travis-ci.com/user/pull-requests

Basically you can't trust external pull requests to expose env vars maliciously so they describe in the doc the only place they're available is internal PRs.   

Ok, so here's my next thought: we don't execute Travis on PRs at all.  Instead we have the slightly pain-in-the-ass workflow where to do an external PR that needs travis testing, it gets merged into a local (non-master) pr branch for this purpose (after the origional pull request was checked for non-malicious activity), and then when it's created as a PR in the OHDSI repo, it will trigger the push notification and then travis will run (with the environment vars available).

Thoughts?

**Comment by chrisknoll** [comment]
Follow up: to this end, i went to the travis settings on achilles and turned off 'build on PR'.  I can experiment with the PR you created (#165) where I will turn off pr builds in travis, I'll create the branch for integration in Achilles as a local branch, merge your PR over there, and then have travis execute.  Part of the pain of all of this is if subsequent updates are made to the origional branch, a loop needs to happen:

external PR -> merge to OHDSI brannch -> update to external PR -> merge into OHDSI branch -> etc -> finally no more changes -> merge to master from OHDSI branch.

It's more work but it's the only way to support encrypted repository-local settings.

**Comment by msuchard** [comment]
Things are already set-up for this.  Each test now checks to see if env vars are set and only runs if set.

Env vars can be set in local environments for local testing and on travis for ohdsi-to-ohdsi PRs and pushes.

**Comment by t-abdul-basser** [comment]
@msuchard Thats great. @chrisknoll Should we test this?

**Comment by chrisknoll** [comment]
@msuchard , you're correct but we'd still need to bring the PR from the fork into a local branch in order for it to execute against our own internal travis-ci environment (I don't suggest we take anyone's word for it that it it passed their own tests).  So, your commits are good because it only runs tests where the local dev sets up the appropriate env vars (say one guy only has oracle and another guy only has postresql), but in the end, it needs to be brought into a local OHDSI branch and go through all 3 RDBMS environment tests.

@t-abdul-basser : i'm testing it now in #163.  #163 is a merge of @vojtechhuser pull requests and @msuchard pull reqeusts, and travis-CI is executing using all the env vars available to it in the OHDSI repo.

I'll merge in #163 after all these tests pass.

One outstanding note here: I put in a filter in our tests to only execute on mssql.  This will change once @leeevans determines the cause of the slow execution on postgresql and oracle, and once that's resolved we'll configure the filter to execute all tests again.

**Comment by chrisknoll** [comment]
Ok, I'm closing this out. The preferred approach of dealing with external PRs is as follows:

1. External collaborator creates PR.
2. Internal reviewer reviews code for any security vulnerabilities (such as revealing env vars)
3. Internal reviewer creates a OHDSI repo branch to merge external PR into.  
4. Internal reviewer modifes external PR to point to the new OHDSI repo branch to be the head.
5. PR is accepted and closed
6. New PR is created from internal OHSI branch. Travis will execute on the internal branch against our 3 dbs.
7. Once travis build completes with no errors on internal branch, it can be merged into master.

That's a bit of overhead to protect the credentials, but it is probably worth it.  Also this allows us to bundle our PRs together so that they hit master in one shot which may or may not be desirable (depending on how fresh people want master to be).

**Comment by t-abdul-basser** [comment]
@chrisknoll Thanks, very helpful. Agreed.
