### ISSUE TITLE
START_DATE after END_DATE

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#172]
Where END_DATE is not null, it needs to be after the START_DATE.  Throw error if fails.

Tagging @alondhe .

**Comment by alondhe** [comment]
Looks like we have this rule already:
910	Number of drug eras with end date < start date

**Comment by ericaVoss** [comment]
Yes, this is a test for DRUG_ERA, I think ACHILLES needs a DRUG_EXPOSURE date test.  In reality it should be any time there is a date, for all different domains.

**Comment by ericaVoss** [comment]
@t-abdul-basser or @vojtechhuser - could you assign this ticket to @alondhe

**Comment by t-abdul-basser** [comment]
I can not seem to assign him. @alondhe can you assign yourself?

**Comment by alondhe** [comment]
@t-abdul-basser I think my account role needs to be upgraded. I can't assign anyone.

**Comment by t-abdul-basser** [comment]
Understood. It does not appear that I can gran the appropriate status. Perhaps @vojtechhuser or @pbr6cornell can?

**Comment by vojtechhuser** [comment]
alondhe is not showing up in the list. Patrick needs to make him part of the OHDSI organization perhaps.

**Comment by cgreich** [comment]
I invited alondhe.

**Comment by alondhe** [comment]
Thanks @cgreich @t-abdul-basser @vojtechhuser !

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
