### ISSUE TITLE
Test Types

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#173]
For every domain that has a TYPE field.  Check the Vocabulary the proper type for that domain is used.  Throw error if not.

**Comment by chrisknoll** [comment]
Erica are you saying to fail the entire Achilles process if the type doesn't match (that's what I hear when you say 'throw error'.  

Do you mean to say that this should be recorded in Achilles Heel as an error?

**Comment by vojtechhuser** [comment]
I think she means when visit type concept id is not in the "subset" for visity types - a heel error is shown. So into visit type (9201 is inpatient visit) - I suddenly store there a type of "asthma" as my visit type. @ericaVoss  can you provide a list of type columns that you see as particulary important.

**Comment by ericaVoss** [comment]
@chrisknoll - I mean throw an ACHILLES HEEL item if the concept in the TYPE field is not of type TYPE.  Just like @vojtechhuser's example.

 @vojtechhuser - I think you got it.

- DRUG_TYPE_CONCEPT_ID
-MEASUREMENT_TYPE_CONCEPT_ID
- OBSERVATION_TYPE_CONCEPT_ID
- CONDITION_TYPE_CONCEPT_ID
- DEATH_TYPE_CONCEPT_ID
- COST_TYPE_CONCEPT_ID
- DEVICE_TYPE_CONCEPT_ID
 - NOTE TYPE_CONCEPT_ID

**Comment by vojtechhuser** [comment]
Draft for death type:

```sql

--raw data
select e.death_type_concept_id, count(*) from death e left join concept c on e.death_type_concept_id = c.concept_id
where vocabulary_id <> 'Death Type' and e.death_type_concept_id <> 0
group by e.death_type_concept_id;

--via analysis (interestingly the counts don't agree on synpuf data) (did not investigate further, comments welcome)
select * from achilles_results where analysis_id = 505; --not developed further

--rule


INSERT INTO ACHILLES_HEEL_results (ACHILLES_HEEL_warning,rule_id,record_count)
--INSERT INTO ACHILLES_HEEL_results (ACHILLES_HEEL_warning,rule_id,stratum_1,record_count)
SELECT 
 'ERROR: incorrect death_type_concept_id'  as ACHILLES_HEEL_warning,
  38 as rule_id,
-- e.death_type_concept_id as stratum_1
 count(*) as record_count 
 from death e left join concept c on e.death_type_concept_id = c.concept_id
where vocabulary_id <> 'Death Type' and e.death_type_concept_id <> 0
group by e.death_type_concept_id;


```

**Comment by vojtechhuser** [comment]
existing rule_id = 5 only checks for mere join to the concept table (if it is null or not). rule 5 does not have column specific scope of restriction (e.g., death type as the code above)

**Comment by fdefalco** [comment]
This functionality has been implemented in the DataQualityDashboard and supersedes heel which is deprecated at this time.
