### ISSUE TITLE
Warning: mismatch between Roxygen documentation and function definition

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Achilles#181]
Check throws the warnings below, indicating mismatched between documentation and actual code. For example, the first warning indicated the [achilles function definition](https://github.com/OHDSI/Achilles/blob/428108d94a96d4759241240faee02d369b6c8404/R/Achilles.R#L68) has an argument `sqlOnly` that is not documented in the [Roxygen documentation block](https://github.com/OHDSI/Achilles/blob/428108d94a96d4759241240faee02d369b6c8404/R/Achilles.R#L38).

Undocumented arguments in documentation object 'achilles'
  'sqlOnly'

Documented arguments not in \usage in documentation object 'achillesHeel':
  'sourceName'

Undocumented arguments in documentation object 'exportConditionEraToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportConditionToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportDashboardToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportDataDensityToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportDeathToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportDrugEraToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportDrugToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportHeelToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportMeasurementToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportMetaToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportObservationPeriodToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportObservationToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportPersonToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportProcedureToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportToJson'
  'cdmVersion'

Undocumented arguments in documentation object 'exportVisitToJson'
  'cdmVersion'

**Comment by vojtechhuser** [comment]
These warnings seem to be fixed as of now.
