### ISSUE TITLE
Error with exportToJSON() using a postgres OMOP Db

### ISSUE THREAD

**Issue by laderast** [OHDSI/Achilles#185]
Hi,

We are trying to use the exportToJson() function and are getting the following casting error. I'm attaching the current error report. 

I suspect that this problem is better solved in the DatabaseConnector package.

Thanks,
Ted

[errorReport.txt](https://github.com/OHDSI/Achilles/files/775631/errorReport.txt)

**Comment by chrisknoll** [comment]
No, this is something that needs to be addressed by casting the correct columns in the query.  However, it's strange that this hasn't been reported before, possibly it's an issue with something in your local data.  Could you execute the parts of the sub-queries in the attached error report to determine which column the casting has a problem with?

**Comment by laderast** [comment]
Hi Chris,

Thanks for the response. I will try the subqueries tomorrow when I have the chance. Our original omop instance was in MySQL and we ported it over to postgreSQL when we realized we couldn't run Achilles on the MySQL instance. One of the tables might have been incorrectly ported over. 

Thanks,
Ted

**Comment by chrisknoll** [comment]
Yes, it could be something with the data types that mysql defined, or maybe a int column became varchar.  Let me know how I can help.

-Chris

**Comment by laderast** [comment]
Hi Chris, 
Really dumb mistake. I was using version 4 when our db is version 5. Thanks for all your help.
Ted
