### ISSUE TITLE
PDW: Add specific indexes to achilles_results table

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#188]
Achilles Heel throws an error when creating the heel table off of achilles_results in Microsoft PDW. We've been using the following script manually in creating the achilles_results table:

```
CREATE NONCLUSTERED INDEX idx_ar_aid
   ON dbo.ACHILLES_results (analysis_id ASC);
CREATE NONCLUSTERED INDEX idx_ar_aid_s1
   ON dbo.ACHILLES_results (analysis_id ASC, stratum_1 ASC);
CREATE NONCLUSTERED INDEX idx_ar_aid_s1234
   ON dbo.ACHILLES_results (analysis_id ASC, stratum_1 ASC, stratum_2 ASC, stratum_3 ASC, stratum_4 ASC);
```
We should add this script to the Achilles package when PDW is the target database.

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. Do I since a desire to issue a PR with this implementation? :)

**Comment by alondhe** [comment]
Still learning the Git processes, so bear with me :) I can simply fork, make the change, and then do a PR, right?

**Comment by t-abdul-basser** [comment]
No problem :)  

Yes, you should fork, make your change, test and then issue a PR. @chrisknoll or I will take it from there as per https://github.com/OHDSI/Achilles/issues/165.
