### ISSUE TITLE
Achilles crashes when OBSERVATION_PERIOD table is empty

### ISSUE THREAD

**Issue by twilson650** [OHDSI/Achilles#193]
### Expected behavior
Analysis should run even with incomplete data

### Actual behavior
Crashes with error:
Error:
execute JDBC update query failed in dbSendUpdate ([Amazon](500310) Invalid operation: cannot cast type interval to double precision;)
SQL:
CREATE TEMP TABLE tempResults

AS
WITH  rawData (count_value)  AS 

(

  select count_value

  FROM

  (

    select ( op.observation_period_end_date - op.observation_period_start_date) as count_value,

  	  ROW_NUMBER() over (PARTITION by op.person_id order by op.observation_period_start_date asc) as rn

    from omop_data.OBSERVATION_PERIOD op

	) op

	where op.rn = 1

),

overallStats (avg_value, stdev_value, min_value, max_value, total) as

(

  select CAST(avg(1.0 * count_value) AS FLOAT) as avg_value,

  CAST(STDDEV(count_value) AS FLOAT) as stdev_value,

  min(count_value) as min_value,

  max(count_value) as max_value,

  COUNT(*) as total

  from rawData

),

statsView (count_value, total, rn) as

(

  select count_value, COUNT(*) as total, row_number() over (order by count_value) as rn

  FROM

  (

    select ( op.observation_period_end_date - op.observation_period_start_date) as count_value,

  	  ROW_NUMBER() over (PARTITION by op.person_id order by op.observation_period_start_date asc) as rn

    from omop_data.OBSERVATION_PERIOD op

	) op

  where op.rn = 1

  group by count_value

),

priorStats (count_value, total, accumulated) as

(

  select s.count_value, s.total, sum(p.total) as accumulated

  from statsView s

  join statsView p on p.rn <= s.rn

  group by s.count_value, s.total, s.rn

)

 SELECT
 105 as analysis_id,

  o.total as count_value,

  o.min_value,

	o.max_value,

	o.avg_value,

	o.stdev_value,

	MIN(case when p.accumulated >= .50 * o.total then count_value end) as median_value,

	MIN(case when p.accumulated >= .10 * o.total then count_value end) as p10_value,

	MIN(case when p.accumulated >= .25 * o.total then count_value end) as p25_value,

	MIN(case when p.accumulated >= .75 * o.total then count_value end) as p75_value,

	MIN(case when p.accumulated >= .90 * o.total then count_value end) as p90_value

FROM
 priorStats p

CROSS JOIN overallStats o

GROUP BY o.total, o.min_value, o.max_value, o.avg_value, o.stdev_value

### Steps to reproduce behavior
Run against a model with an empty OBSERVATION_PERIOD table

**Comment by t-abdul-basser** [comment]
Thanks. What version of Achilles are you using? What's RDBMS?

**Comment by twilson650** [comment]
I downloaded the code from the master branch and am running it in RStudio. The RDBMS is redshift.

**Comment by twilson650** [comment]
It looks like the select of count_value is returning no results, and then the query tries to take the average and standard deviation of that empty set, where it encounters a cast error.

**Comment by t-abdul-basser** [comment]
Thanks. That suggests that we could probably fix this issue by testing for empty result before executing the arithmetic. I will look at this.

**Comment by vojtechhuser** [comment]
I thought that some of the test data on travis is also empty.  This may be redshift specific problem. Our obs period table is also empty and I think it runs fine.

**Comment by twilson650** [comment]
I am running against a redshift database. I haven't found a way to apply conditionals around the sql blocks. I was able to run the analysis by commenting out certain blocks, specifically observation_period, visit_occurrence, death, drug_era, condition_era, and note

After doing some research I'm not sure there is a way to check if those tables are empty, and skip the sql blocks if they are. 

Here is the full error report:

DBMS:
redshift

Error:
execute JDBC update query failed in dbSendUpdate ([Amazon](500310) Invalid operation: cannot cast type interval to double precision;)

SQL:
CREATE TEMP TABLE tempResults


AS
WITH  rawData (count_value)  AS 

(

  select count_value

  FROM

  (

    select ( op.observation_period_end_date - op.observation_period_start_date) as count_value,

  	  ROW_NUMBER() over (PARTITION by op.person_id order by op.observation_period_start_date asc) as rn

    from omop_data.OBSERVATION_PERIOD op

	) op

	where op.rn = 1

),

overallStats (avg_value, stdev_value, min_value, max_value, total) as

(

  select CAST(avg(1.0 * count_value) AS FLOAT) as avg_value,

  CAST(STDDEV(count_value) AS FLOAT) as stdev_value,

  min(count_value) as min_value,

  max(count_value) as max_value,

  COUNT(*) as total

  from rawData

),

statsView (count_value, total, rn) as

(

  select count_value, COUNT(*) as total, row_number() over (order by count_value) as rn

  FROM

  (

    select ( op.observation_period_end_date - op.observation_period_start_date) as count_value,

  	  ROW_NUMBER() over (PARTITION by op.person_id order by op.observation_period_start_date asc) as rn

    from omop_data.OBSERVATION_PERIOD op

	) op

  where op.rn = 1

  group by count_value

),

priorStats (count_value, total, accumulated) as

(

  select s.count_value, s.total, sum(p.total) as accumulated

  from statsView s

  join statsView p on p.rn <= s.rn

  group by s.count_value, s.total, s.rn

)

 SELECT
 105 as analysis_id,

  o.total as count_value,

  o.min_value,

	o.max_value,

	o.avg_value,

	o.stdev_value,

	MIN(case when p.accumulated >= .50 * o.total then count_value end) as median_value,

	MIN(case when p.accumulated >= .10 * o.total then count_value end) as p10_value,

	MIN(case when p.accumulated >= .25 * o.total then count_value end) as p25_value,

	MIN(case when p.accumulated >= .75 * o.total then count_value end) as p75_value,

	MIN(case when p.accumulated >= .90 * o.total then count_value end) as p90_value


FROM
 priorStats p

CROSS JOIN overallStats o

GROUP BY o.total, o.min_value, o.max_value, o.avg_value, o.stdev_value



R version:
R version 3.3.3 (2017-03-06)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.4)
- rjson (0.2.15)
- DatabaseConnector (1.9.2)
- RJDBC (0.2-5)
- rJava (0.9-8)
- DBI (0.6)
- SqlRender (1.2.0)

**Comment by pbr6cornell** [comment]
i think we are missing a key issue here though:  a cdm is not valid if the
observation_period table is not populated.  that is fundamental to all
ohdsi analyses.   if a person doesnt have at least one observation period,
then we cannot determine when or how to interpret the absense or presensd
of any of the other timestamped observations within the cdm.

i agree we should have better error handling, but lets not lose sight over
what the errors are actually telling us.

**Comment by twilson650** [comment]
You're right, observation_period should have been populated. Once it was, Achilles ran fine. Thanks.
