### ISSUE TITLE
Add RxNorm Extension to drug exposure report on Achilles web

### ISSUE THREAD

**Issue by kwang2016** [OHDSI/Achilles#196]
End users have been requesting to see both RxNorm and RxNorm Extension on the drug exposure report on Achilles web. It'd be greatly appreciated if this can be implemented quickly.

### Expected behavior
Drugs from both RxNorm and RxNorm Extension vocabulary are displayed on drug exposure report on Achilles web

### Actual behavior
Currently only drugs from RxNorm vocabulary are displayed on drug exposure report on Achilles web

**Comment by c4lm** [comment]
As far as I can tell, this issue applies only to V4 and should be fixed with #198 .
In order to have RxNorm Extension drugs displayed on report pages, the JSON data will have to be re-exported.

**Comment by vojtechhuser** [comment]
So can this be closed than?

**Comment by t-abdul-basser** [comment]
Yes.
