### ISSUE TITLE
There is no query to insert [ACHILLES_results] data to [ACHILLES_results_dist] for [MEASUREMENT] table

### ISSUE THREAD

**Issue by HojunPark** [OHDSI/Achilles#200]
### Expected behavior
  Making json files including summary data about analysis_id of measurement (<b>1805, 1807, 1818</b>)
 1805 : Measurement by Type
 1807 : Measurement Records by Unit
 1818 : Values Relative to Normal Range 

### Actual behavior
 There is no data about them in the json files
(<b>Measurement by Type, Measurement Records by Unit, Values Relative to Normal Range</b>)

### Steps to reproduce behavior
[Achilles/inst/sql/sql_server/export_v5/measurement]

In some exporting queries for measurement, they exports data from <b>[ACHILLES_results_dist] table</b>.

---

<b>1.  sqlMeasurementsByType.sql</b>
select c1.concept_id as MEASUREMENT_CONCEPT_ID, 
  c1.concept_name as MEASUREMENT_CONCEPT_NAME, 
	c2.concept_id as CONCEPT_ID,
	c2.concept_name as CONCEPT_NAME, 
	ar1.count_value as COUNT_VALUE
from (
  select cast(stratum_1 as int) stratum_1, cast(stratum_2 as int) stratum_2, count_value
  <b>FROM @results_database_schema.ACHILLES_results_dist </b>
  where analysis_id = 1805
  GROUP BY analysis_id, stratum_1, stratum_2, count_value 
) ar1
inner join @vocab_database_schema.concept c1 on ar1.stratum_1 = c1.concept_id
inner join @vocab_database_schema.concept c2 on ar1.stratum_2 = c2.concept_id

<b>2. sqlRecordsByUnit.sql </b>
select c1.concept_id as MEASUREMENT_CONCEPT_ID, 
	c1.concept_name as MEASUREMENT_CONCEPT_NAME,
	c2.concept_id as concept_id,
	c2.concept_name as concept_name, 
	ar1.count_value as count_value
from (
  select cast(stratum_1 as int) stratum_1, cast(stratum_2 as int) stratum_2, count_value
  <b>FROM @results_database_schema.ACHILLES_results_dist </b>
  where analysis_id = 1807
  GROUP BY analysis_id, stratum_1, stratum_2, count_value
) ar1
inner join @vocab_database_schema.concept c1 on ar1.stratum_1 = c1.concept_id
inner join @vocab_database_schema.concept c2 on ar1.stratum_2 = c2.concept_id

<b>3. sqlValuesRelativeToNorm.sql</b>
select c1.concept_id as MEASUREMENT_CONCEPT_ID, 
	c1.concept_name as MEASUREMENT_CONCEPT_NAME,
	c2.concept_id as concept_id,
	c2.concept_name + ': ' + ar1.stratum_3 as concept_name, 
	ar1.count_value as count_value
from (
  select cast(stratum_1 as int) stratum_1, cast(stratum_2 as int) stratum_2, stratum_3, count_value
  <b>FROM @results_database_schema.ACHILLES_results_dist </b>
  where analysis_id = 1818
  GROUP BY analysis_id, stratum_1, stratum_2, stratum_3, count_value
) ar1
inner join @vocab_database_schema.concept c1 on ar1.stratum_1 = c1.concept_id
inner join @vocab_database_schema.concept c2 on ar1.stratum_2 = c2.concept_id

---

But, there is no query in [Achilles_v5.sql] to insert [ACHILLES_results] data to [ACHILLES_results_dist] for analysis_id (1805, 1807, 1818)
So, I used prior version of the three sql files.

**Comment by vojtechhuser** [comment]
export to JSON is supported a bit less now. Why? - because webAPI is more dynamic way to get this data. 

however even at our site we don't have webAPI working fully so .JSON files is the only option. Feel free to make a PR and add those to the R code

**Comment by HojunPark** [comment]
@vojtechhuser Thank you for your comments.
Yes, I'm using AchillesWeb. And I'm using ATLAS too.
