### ISSUE TITLE
Don't know how to translate from sql server to Oracle

### ISSUE THREAD

**Issue by mark-velez** [OHDSI/Achilles#206]
Note this is an issue I witnessed when trying to get Achilles working for a group at NYU. They didn't have the vocabulary tables populated but the error may not necessarily be related to that. I will get them set up with the vocabulary and follow-up here.

### Expected behavior
Progress executing the analyses associated with invoking the function `achilles()`.

### Actual behavior
We get the following error (no progress is reported):

    Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
      java.lang.RuntimeException: Don't know how to translate from sql server to Oracle. Valid target dialects are sql server
    In addition: Warning message:
    In renderSql(parameterizedSql[1], ...) :
      Parameter 'vocab_database_schema' not found in SQL

### Steps to reproduce behavior
On Mac OSX, connection details points to an Oracle database with an OMOP CDM instance (no vocabulary data).

**Comment by chrisknoll** [comment]
Try with lowercase 'oracle' as the target dialect.

**Comment by mark-velez** [comment]
@chrisknoll thanks I will check with NYU folks

**Comment by vojtechhuser** [comment]
I think this can be closed now.
