### ISSUE TITLE
Enhance usability of Achilles Heel

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#209]
Cleans up Achilles Heel including

- enhance the text in the Achilles Heels error/warning/notifications for readability
- add category description to each error/warning/notifications
- adding sortability by n
- Organization/developers involved in the implementation

Overlaps with @alondhe [recent efforts](https://github.com/OHDSI/WebAPI/issues/217#issuecomment-321091723).

**Comment by vojtechhuser** [comment]
What do you mean by sortability by n ?  (this is atlas item in my view.
 Achilles simply must have a good table to capture it but display is in atlas.

**Comment by t-abdul-basser** [comment]
Good catch. I meant sort by arbitrary column and yes that should go in Atlas.

**Comment by cukarthik** [comment]
In this refactoring, would it be possible to add the ability for a site to reorganize the Achilles message types? Based on how we populate our data, it would be nice to reclassify some ERRORS as NOTIFICATIONS. For example, we do not populate locations so do not want to have those messages tagged as an error.

**Comment by PRijnbeek** [comment]
I very useful feature would be if the Achilles Heel report would have the option to download the rendered SQL that is behind that query. This would allow you to very easily find the problem instead of first dive into the code base to find the query and then have to render and translate to your own dialect.

**Comment by alondhe** [comment]
Hi @PRijnbeek - there is a sqlOnly option, also, the return value of the achilles or achillesHeel functions does include it

**Comment by vojtechhuser** [comment]
@PRijnbeek ad your question about
>This would allow you to very easily find the problem

please look into file called Rule Drill Down here: https://github.com/OHDSI/Achilles/blob/master/inst/csv/rule_drill_down.csv

For non-umbrella rules, this allows to find exactly what you want. I developed this knowledge base with the goal to display it as a hyperlink in Atlas next to the heel message output.

**Comment by MaximMoinat** [comment]
I was looking into the readability of Achilles Heel output as well. One thing I would really like to do, is sorting on the count. An example of how I now organise the Achilles Heel report:
![image](https://user-images.githubusercontent.com/17825660/40355212-1ed14b12-5db6-11e8-9c9b-8b15a1646117.png)

The count as percentage of total row count would be even better.

**Comment by PRijnbeek** [comment]
@vojtechhuser thanks, yes i had seen that before.

What i have done for our ETL is that i have a sql file with all the errors found in earlier sprints in our SQL dialect that will give me a list of all the patients the are in the count of that error so we can dive deeper.

The drilldown csv is now in T-SQL probably and needs translation with SQLRender.

I like to the idea to have a link or maybe even a button next to the error that will execute the query against the CDM and will show me the (top X) problematic records (with an export function). 

This can be in the Achilles Heel report/sheet itself or maybe we can have a simple Shiny-App the can do this using R and all the nice tools we have there..

**Comment by alondhe** [comment]
The new Shiny app addresses these ideas, closing this ticket, but if there are ideas on how to improve the Shiny app, please feel free to open a new issue.
