### ISSUE TITLE
Current version of Achilles does not support CDM v5.2 and future v6

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Achilles#210]
Code needs to be updated to support the latest version of the [CDM](github.com/ohdsi/commondatamodel)

**Comment by vojtechhuser** [comment]
Can you specify which v5.2 tables and functionality you would like to see supported?  

When we ask for version, we currently expect a single digit number. This is a larger OHDSI issue (same with other packages - like cohortmethod)

**Comment by vojtechhuser** [comment]
After release of v6 - how do we plan to refer to CDM versions '5' or '5.2'.  I suggest version is a string and we look at the first number only in first pass and possibly some logic for second number.

**Comment by t-abdul-basser** [comment]
Addressed in PR #262.
