### ISSUE TITLE
Error installation SqlRender package

### ISSUE THREAD

**Issue by MarcoMattioli** [OHDSI/Achilles#216]
Hi All,
I tried to install Achilles following the instructions in the README file, but I could not manage to install the SqlRender package. The error returned is related to a problem in rJava: 

***** arch - i386
Error: package or namespace load failed for 'SqlRender':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'**

The version of java installed is 1.8.0_144 (64 bit) and I am using RStudio with R version 3.4.0 (64 bit).
I have also added the PATH to the "jvm.dll" file to the system environment variables. 
I tried to install and load the package "rJava" independently from Achilles and I got no problem.

Any idea how to solve this? Many thanks in advance.

**Comment by schuemie** [comment]
This seems to be related to [this issue](https://github.com/OHDSI/Achilles/issues/5). Could you try installing SqlRender and other OHDSI packages using the `--no-multiarch` argument?
```r
install_github("ohdsi/SqlRender", args="--no-multiarch")
```

Alternatively, you could also install a 32-bit Java runtime environment (in addition to the 64-bit environment already present).

**Comment by MarcoMattioli** [comment]
Thank you, that solved the problem!
