### ISSUE TITLE
Use Achilles on local data

### ISSUE THREAD

**Issue by MarcoMattioli** [OHDSI/Achilles#220]
Hi All,

I would like to know of it is possible to use Achilles with OMOP CDM v5  '.csv' data stored on my local disk.
I can not find documentation regarding this topic. (it seems that Achilles can only be used on data stored on a server).

Can anybody clarify this?

Thank you for the help,
Marco

**Comment by alondhe** [comment]
Correct, it'll only work with a database. It's possible to use a service like Amazon spectrum to have CSV data load directly into an Amazon redshift cluster without a lot of heavy ETL, but it does require money and a bit of configuration.

**Comment by schuemie** [comment]
A free option would be [PostgreSQL](https://www.postgresql.org/) which you would have to install, and then load your data into it.
