### ISSUE TITLE
Update readme to background AchillesWeb 

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#221]
### Expected behavior

Current Achilles documentation should present Atlas (rather than AchillesWeb) as preferred and recommended component for viewing Achilles-produced source characterization reports/visualization.

### Actual behavior

Current Achilles documentation present AchillesWeb (rather than Atlas) as preferred and recommended component for viewing Achilles-produced source characterization reports/visualization.

### Steps to reproduce behavior

Review Achilles Readme.

**Comment by vojtechhuser** [comment]
Can you do the readme modification. I don't know enough about webAPI to describe it best. @t-abdul-basser

**Comment by t-abdul-basser** [comment]
Sure.

**Comment by t-abdul-basser** [comment]
Let's push this to a post 1.5 Release.

**Comment by vojtechhuser** [comment]
any update on this?

**Comment by t-abdul-basser** [comment]
I have not finished draft yet.
