### ISSUE TITLE
Drop support for v4 since version 1.5.0

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#228]
We have many unsupported measures for v4 and it is hard to maintain both versions.

I am proposing to already in release 1.5 consider dropping support for CDM v4 and point folks to 1.4 release if they have only CDMv4 data

**Comment by alondhe** [comment]
I agree! Either point them to the old release, or, as in the case of my branch, split the functions into two CDM version specific flavors.

**Comment by vojtechhuser** [comment]
I plan to touch the R code and remove all v4 SQL from the repo. Please let me know if you opose. @t-abdul-basser  @chrisknoll

**Comment by t-abdul-basser** [comment]
I have no objection to the idea but would push this to the next major release 1.6 not the next release 1.5.1. So make the changes submit a PR and we will schedule it together.

**Comment by t-abdul-basser** [comment]
I would like to get the multi threaded version in sooner. Sorry for the delay in testing.

**Comment by vojtechhuser** [comment]
I am ready to work on this but would like to know a clear final action on the multi-threaded version. E.g., by mid December...

**Comment by alondhe** [comment]
The multi-threaded version needs to be merged with the recent changes in 1.5. I'm allotting time next week to do this.

**Comment by vojtechhuser** [comment]
I would like to touch the R code to remove v4 and check for CDM_SOURCE table existence and at least one row there. I will start doing it on Jan 16th @alondhe  @t-abdul-basser

**Comment by t-abdul-basser** [comment]
Sure. Just make changes and submit a PR for review.
