### ISSUE TITLE
Errors with analysis 691, 791, 891, 1891 in Redshift

### ISSUE THREAD

**Issue by c4lm** [OHDSI/Achilles#232]
I have updated Achilles, DatabaseConnector and SqlRender to the latest version (from github).
When I try to run Achilles on V5 CDM I get the following error:

> java.sql.SQLException: [Amazon](500310) Invalid operation: Aggregate window functions with an ORDER BY clause require a frame clause

This implies that analysis queries 691, 791, 891, 1891 use features unsupported by Amazon Redshift.
[Please see errorReport.txt attached.](https://github.com/OHDSI/Achilles/files/1414660/errorReport.txt)

When we tried to alter the query with the default frame clause  for MS SQL

> RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW

we got the following error:

> RANGE clause of window functions not yet implemented

**Comment by anthonysena** [comment]
Hi - I can confirm the issue on RedShift. I was able to modify the query to get it to work properly by changing the SUM() operation in the SELECT clause from:

`sum(count(person_id))	over (partition by procedure_concept_id order by prc_cnt desc) as count_value`

to:

`sum(count(person_id))	over (partition by procedure_concept_id order by prc_cnt DESC ROWS UNBOUNDED PRECEDING) as count_value`

I attempted to re-write the query to eliminate the windowing function all-together but received the following error:

> Invalid operation: aggregate function calls may not have nested aggregate or window function;

So, I suspect we need to add a rule to SqlRender to handle the windowing function to add in the mandatory frame_clause as described here:

http://docs.aws.amazon.com/redshift/latest/dg/r_Window_function_synopsis.html

@c4lm: could you try the work-around I've posted here to see if that works in your environment?

Tagging @schuemie, @chrisknoll and @alondhe for awareness and assistance on this one. I can attempt to make the changes to SqlRender but would appreciate any guidance or thoughts on how to best approach this problem. An example of one of the queries that fails is here: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/Achilles_v5.sql#L3542

**Comment by alondhe** [comment]
Here's a translateSql replacementPattern I have working in a fork of SqlRender, but I'm not too sure if this should be the default replacement for window functions, anyone with more expertise have feedback?

`redshift,"OVER (PARTITION BY @a ORDER BY @b)","OVER (PARTITION BY @a ORDER BY @b DESC ROWS UNBOUNDED PRECEDING)"`

**Comment by vojtechhuser** [comment]
so the problem is gone now?

**Comment by alondhe** [comment]
I'd say not yet. @ganisimov and I are trying to harden the replacement pattern fix we pushed last week, so that we don't have any blind spots with window functions in Redshift.

**Comment by vojtechhuser** [comment]
what is the status of this? can it be closed? @ganisimov

**Comment by alondhe** [comment]
Yes, I think we have it now with SqlRender 1.4.7
