### ISSUE TITLE
Problem with indices creation while trying to run with Netezza

### ISSUE THREAD

**Issue by agackovka** [OHDSI/Achilles#237]
### Expected behavior
successful
### Actual behavior
it cannot create indices:
DBMS:
netezza

Error:
org.netezza.error.NzSQLException: ERROR:  CREATE INDEX not supported in this release

SQL:
CREATE INDEX idx_ar_aid
  ON results.ACHILLES_results (analysis_id)

R version:
R version 3.4.2 (2017-09-28)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.5)
- rjson (0.2.15)
- SqlRender (1.4.7)
- DatabaseConnector (2.0.3)
- devtools (1.13.4)
### Steps to reproduce behavior

**Comment by t-abdul-basser** [comment]
Thanks @agackovka. Please include any stack trace or error messages. Please also describe how Achilles was run so as to produce this behavior (e.g Achilles from docker, Rscript from, etc) and the environment in which it was run.

**Comment by agackovka** [comment]
@t-abdul-basser Netezza® does not support index creation on tables.
https://www.ibm.com/support/knowledgecenter/en/SSBJG3_2.5.0/com.ibm.gen_busug.doc/c_fgl_odiagntz_037.htm
So, while you are trying to run Achilles on Netezza datasource via docker you should set input param createIndices to FALSE.
How can stacktrace help you?

**Comment by t-abdul-basser** [comment]
Thanks for adding the link. Yes, I understand the issue. However the stack trace or error message aids others who may search by error message. It is also requested for completeness so that we can approve the PR.

**Comment by agackovka** [comment]
@t-abdul-basser, description has been updated.
