### ISSUE TITLE
Detect CDM version using heuristic approach

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#244]
This is a proposal for new functionality.

To check if CDM_SOURCE has at least one row (necessary metadata), I plan to add a function that will use tbls<-getTableNames() and if the table exist, it will test if at least one row in the table is present.

To detect CDM version, also existence of METADATA table in tbls can be checked. If user specifies a version but tables are missing, it is a CDM conformance problem.  

The getTableNames is more elegant than SQL options for checking existence of a table.

**Comment by t-abdul-basser** [comment]
Will this be implemented as a new Achilles Heel Rule?

**Comment by vojtechhuser** [comment]
Most likely this would be R code inside function for achilles heel.

**Comment by anthonysena** [comment]
Per @clairblacketer: https://github.com/OHDSI/CommonDataModel/issues/161, we'd like to initialize the CDM with the schema version number in the CDM_SOURCE.cdm_version as part of the DDL used to create the tables. This way the other tools (i.e. WebAPI) can interrogate this table to know the schema version. 

So, I support the idea on this issue - it would be great to have an Achilles Heel check to verify that CDM_SOURCE.cdm_version is populated. And if this information is set at the time of the table creation, it should be a check that automatically passes. Please let me know if I can help with the check or if you have any concerns with this approach.

Tagging @fdefalco, @gklebanov, @leeevans, @pavgra, @chrisknoll as it was recently discussed on the last OHDSI Architecture call.

**Comment by alondhe** [comment]
This is handled in version 1.6, we check the CDM_SOURCE table if no cdm version is provided in the function call.
