### ISSUE TITLE
Checks for SOURCE_CONCEPT_ID

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#248]
### Expected behavior
Achilles checks SOURCE_CONCEPT_IDs

### Actual behavior
Checks don't exist.

In the THEMIS WG3 this came up as an issue.  Somebody was recommending that these checks be added in.  Similar to checking CONCEPT_IDs we want to check SOURCE_CONCEPT_IDs.

**Comment by vojtechhuser** [comment]
Can you elaborate. E.g., in condition occurrence table - if there is source_concept_id of 7  (invalid concept) - you declare error?

Or only diagnostic concepts may appear?  

So not only a valid concept and but also a concept from a valid subgroup of concepts? )

**Comment by alondhe** [comment]
We'll need to add new analysis ids for this feature. Then, Atlas should be able to utilize this when providing RCs/DRCs

**Comment by alondhe** [comment]
We do characterize source_concept_ids now
