### ISSUE TITLE
group by error on Oracle

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#249]
### Expected behavior
no errors in TravisCI

### Actual behavior
group by query error (see most recent closed PR)

### Steps to reproduce behavior
run test on Oracle

best addressed by @wivern

**Comment by chrisknoll** [comment]
This would be faster to track down if you could include the specific query that results in error.

**Comment by vojtechhuser** [comment]
the PR (now closed has the details).

We could also use R more often
#246
