### ISSUE TITLE
Implement Themis WG1 recommendations (units for labs)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#250]
### Expected behavior
Themis group output is implemented

### Actual behavior
No checking for units for measurements.

### Steps to reproduce behavior
n/a

### proposed solution
Use output of the Themis network study (ThemisUnits output) as a basis for checking for units.
A new CSV file would be included in Achilles that lists valid units for lab tests.

View of data that shows units for lab test (analysis 1807)  would be loaded into R memory and compared with CSV file (knowledge base).
(note that the reasoning is done in R (not in SQL) to allow management of knowledge base in a simple CSV file) 

Themis study results are here.
https://github.com/OHDSI/StudyProtocolSandbox/tree/master/themis/extras/partial_results
(see file units-with-tests)

Example view (labs with one unit)
![image](https://user-images.githubusercontent.com/7526119/36604954-3d279030-188d-11e8-833e-6ff3105eafae.png)

Labs with multiple units:

![image](https://user-images.githubusercontent.com/7526119/36605047-8e8b22a2-188d-11e8-8fb7-b22c288bf9df.png)

This approached was discussed in Themis WG1 and vetted (on high level) by the group.

**Comment by MaximMoinat** [comment]
Is it also being considered in this Themis workgroup to add a warning about measurements with a `value_as_number`, but **missing a unit**? Might be a trivial, though useful addition.

**Comment by vojtechhuser** [comment]
Good suggestion. Thanks for input.

**Comment by vojtechhuser** [comment]
@MaximMoinat  There is a convention that says that it is optional. (which is not a convention that encourages data quality)

**Comment by vojtechhuser** [comment]
Themis ratified this in February to advance this to commenting period. But their github is behind and it is not reflected on themis github

**Comment by vojtechhuser** [comment]
this is linked to https://github.com/OHDSI/Themis/issues/4

**Comment by fdefalco** [comment]
superseded by DQD
