### ISSUE TITLE
MS SQL group by error in heel (from forum) 

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#253]
### Steps to reproduce behavior
http://forums.ohdsi.org/t/achilles-heel-installation-error/4079/2

rewrite as subquery

This could also be addressed outside SQL 
I am proposing to use R more (for problems under 30mb of data in memory)

see #246

**Comment by t-abdul-basser** [comment]
Check that, as per @chrisknoll advice, the problem query is re-written so the computed columns that are meant to be grouped-by are instead calculated in a sub-query and then referenced outside as the column:

```
insert into RESULT.DBO.ACHILLES_results_derived (analysis_id, stratum_1, statistic_value,measure_id) 
select 
--100000+analysis_id, 
NULL as analysis_id,
stratum_2 as stratum_1,
sum(count_value) as statistic_value,
CAST(CONCAT('ach_',CAST(analysis_id as VARCHAR),':GlobalCnt') AS VARCHAR(255)) as measure_id
from RESULT.achilles_results 
where analysis_id in(1805,705,605,805,405) group by analysis_id,stratum_2,measure_id
```
should be

```
insert into RESULT.DBO.ACHILLES_results_derived (analysis_id, stratum_1, statistic_value,measure_id) 
select 
--100000+analysis_id, 
NULL as analysis_id,
stratum_1,
sum(count_value) as statistic_value,
measure_id
FROM (
  select stratum_2 as stratum_1, count_value,  
    CAST(CONCAT('ach_',CAST(analysis_id as VARCHAR),':GlobalCnt') AS VARCHAR(255)) as measure_id
  FROM RESULT.achilles_results 
  where analysis_id in(1805,705,605,805,405)
) Q
group by stratum_1, measure_id
```
As per @chrisknoll, confirm that since analysis_id is a static value, it does not need to appear in the group_by clause.

**Comment by chrisknoll** [comment]
> As per @chrisknoll, confirm that since analysis_id is a static value, it does not need to appear in the group_by clause.

That should be correct. if you add a static value (like a int or a null) to the selected columns, you don not need to specify those static values in the group by clause.
