### ISSUE TITLE
Add negative measurement values warning

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#256]
From THEMIS: add a warning for negative measurement values being present in the measurement table. This will help highlight to ETLers that they need to determine whether these values are valid or invalid, and to make some adjustment in their ETL.

@ericaVoss

**Comment by vojtechhuser** [comment]
I think the logic has to be specific to a lab test (not in general).

If specific, I prefer implementing this outside SQL. (in R)

**Comment by t-abdul-basser** [comment]
@alondhe @ericaVoss @vojtechhuser Could you reference the specific THEMIS convention here. Thx,

**Comment by alondhe** [comment]
Let's discuss further in Andrew's DQ initiative
