### ISSUE TITLE
THEMIS: may need to allow 60-day grace period after death

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#257]
Tracking this as a potential change in the death warnings for activity post death. Currently, 30 days are allowed, in THEMIS, we're discussing making this 60 days.

**Comment by vojtechhuser** [comment]
I propose to have a revised strategy for thresholds. Each rule has some short name and the shortname plus threshold suffix is used in a constant, that has some standard location in the code.

Unless we want to have threshold.csv file (which would be even better)

**Comment by vojtechhuser** [comment]
I am trying to find the rule for 30 days after death and in the new structure - it is not easy. Any help would be appreaciated.

E.g., rule_id  44 would be in which file?

I spend some time making the `achilles_rule.csv` file comprehensive and good documentation for the rules.
@alondhe

**Comment by vojtechhuser** [comment]
I am not sure current value is 30. It might be 0 and be in umbrella rule 1 or 2 or 3

**Comment by vojtechhuser** [comment]
change to 60 is done now in file https://github.com/OHDSI/Achilles/blob/multithreaded-plus/inst/sql/sql_server/heels/parallel/heel_results/rule_3.sql
