### ISSUE TITLE
[PDW] analyses 715 and 716: window function bug

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#258]
### Expected behavior
```
statsView (stratum_id, count_value, total, rn) as
(
  select stratum_id, count_value, count_big(*) as total, row_number() over (order by count_value) as rn
  FROM rawData
  group by stratum_id, count_value
)
```

produces the same value consistently

### Actual behavior

In PDW: the row_number() windowing function is ordering by only count_value which in this case means the record set could potentially get sorted differently each time because count_value is not unique across stratum_id’s.  Thus when you do the subsequent joins on rn, it can potentially be different each time. 

### Steps to reproduce behavior

Run Achilles 715 and 716 in PDW

We have the fix from Microsoft, and I've implemented it in my fork:

_To correct this you can either partition the windowing function by stratum_id or add stratum_id as an additional sort value – either method should return consistent results for this dataset but partitioning the windowing function is more scalable and will reduce the overall CPU required to complete the query._

**Comment by t-abdul-basser** [comment]
Thanks @alondhe for bringing this to our attention and for tracking down and summarizing the fix. We lok forward to the PR when it is ready.
