### ISSUE TITLE
Achilles Heel: Sql server - missing join condition

### ISSUE THREAD

**Issue by papaul** [OHDSI/Achilles#260]
Achilles Heel generates the following error. Looks like the join condition is missing for the SQL being executed. Any ideas on how to resolve this issue? 

DBMS:
sql server

Error:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'where'.

SQL:
insert into Achilles_results.dbo.ACHILLES_results_derived (statistic_value,stratum_1,measure_id)    
select
  CAST(100.0*st.val/statistic_value AS FLOAT) as statistic_value,
  CAST('Condition' AS VARCHAR(255)) as stratum_1, CAST(  'UnmappedData:byDomain:Percentage' AS VARCHAR(255)) as measure_id
from Achilles_results.dbo.achilles_results_derived
join (select statistic_value as val from Achilles_results.dbo.achilles_results_derived where measure_id like 'UnmappedData:ach_401:GlobalRowCnt') as st
where measure_id ='ach_401:GlobalRowCnt'

R version:
R version 3.4.4 (2018-03-15)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.5)
- rjson (0.2.15)
- DatabaseConnector (2.0.5)
- SqlRender (1.4.9)
- devtools (1.13.5)

**Comment by t-abdul-basser** [comment]
@papaul Thanks for reporting this. To confirm: Were you running off master or the current release?

**Comment by t-abdul-basser** [comment]
@papaul Thank you. If you used ```install_github```, then I assume that it is the current released version. to my knowledge, this has not been reported in any of the SQL Server test or production systems before. Can you post the SQL server version that you are using?

**Comment by alondhe** [comment]
@t-abdul-basser I've seen this error out in PDW, but not Redshift. I'm pushing the multithreaded PR in a few hours, it has a fix for this.

**Comment by papaul** [comment]
SQL server version: Microsoft SQL Server 2016 (SP1-CU4) (KB4024305) - 13.0.4446.0 (X64)

**Comment by t-abdul-basser** [comment]
@papaul Thanks.

@alondhe Ok. We will wait for the PR.

**Comment by vojtechhuser** [comment]
Hmm. It is probably my code. I confirm that there is no ON x=y part. Again, these could be much less error prone done in R. The fix should not be that hard.

**Comment by SulevR** [comment]
Temporary workaround - use v1.5.0 tag instead of master branch:
install_github("ohdsi/Achilles", repos="http://cran.rstudio.com/", ref="v1.5.0")

**Comment by papaul** [comment]
Thank you!

**Comment by vojtechhuser** [comment]
to add to the hint -  there is notation to refer to latest release with a star
like this
devtools::install_github("OHDSI/OhdsiRTools@*release")

see https://stackoverflow.com/questions/40179493/r-how-can-i-install-a-specific-release-by-install-github
