### ISSUE TITLE
Document Achilles version in result table and execution date of it

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#264]
### Expected behavior
Recepient of Achilles data can know which version was used to compute it
analysis 0 documented it here
https://github.com/OHDSI/Achilles/blob/v1.5.0/inst/sql/sql_server/Achilles_v5.sql#L1297

### Actual behavior
new proposal seems to have it 
https://github.com/OHDSI/Achilles/blob/multithreaded-plus/inst/sql/sql_server/analyses/0.sql

But where is the constant now defined ?

My data quality study depends on it quite a lot. 
If version if pulled from R (what I suspect), than we should also pull from R the execution date (it will be in more uniform format to consume it later across sites)

@alondhe 

This is related to how to manage constants/thresholds now when the code is fragmented in many sql files.

**Comment by alondhe** [comment]
I made it pull from the R package itself, so that it's not hard-coded.

**Comment by vojtechhuser** [comment]
Can you point me to the part of the R code where this would be. What do you think of providing the execution date also from R (and not from database)

**Comment by alondhe** [comment]
sure, I pass it into the SQL here: https://github.com/OHDSI/Achilles/blob/multithreaded-plus/R/Achilles.R#L917

I could add the execution date from R too, perhaps after we review (and definitely fix!) my branch.

**Comment by t-abdul-basser** [comment]
Asked & answered.
