### ISSUE TITLE
TravisCI testing

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#270]
I have to say that we are struggling with TravisCI testing.

Is @chrisknoll the go to expert if we struggle with TravisCI?
I am not sure how to see the errors for the multithreading PR which we desperately would like to commit to master.

In 2019 - will we also use TravisCI? What is the long term plan.

TravisCI can not test all flavors of SQL. Do we keep it in the process or we reform it?

**Comment by t-abdul-basser** [comment]
Lets agree to keep using TravisCI now and decide if we want to replace or more likely extend it later.
