### ISSUE TITLE
Docker image build fails due to missing dependency

### ISSUE THREAD

**Issue by wivern** [OHDSI/Achilles#272]
### Actual behavior
Achilles requires OHDSI/DatabaseConnector which requires urltools, but urltools is missing in r-cran packages installation. And when running docker build it fails with the following message:

`ERROR:` dependency ‘urltools’ is not available for package ‘DatabaseConnector’
`* removing ‘/usr/local/lib/R/site-library/DatabaseConnector’`

Suggestion: add r-cran-urltools to the apt-get install in Dockerfile

**Comment by t-abdul-basser** [comment]
@wivern Thanks for catching this. Adding _r-cran-tools_ makes sense to me. If you want to make this change and submit a PR, we will review and merge.
