### ISSUE TITLE
allReports.rda usage

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#274]
### Expected behavior
When running exportToJson without specifying which reports to export, the package should use the allReports variable, which sits in an .rda file that gets loaded into the system environment on package load.

### Actual behavior
When running exportToJson using an R session that hasn't pre-loaded the Achilles, but instead, explicitly referencing the function with `Achilles::exportToJson()`, allReports doesn't get loaded. 

### Steps to reproduce behavior
Start a fresh R session, then run `Achilles::exportToJson()`, with all the pertinent parameters (except reports) established.

Could we change the rda file to simply a CSV?

**Comment by vojtechhuser** [comment]
If you need CSV - go ahead.  RDA or CSV - either is fine.

Or somehow check if you have the data needed and load them if you don't have what you need.

**Comment by alondhe** [comment]
In the multithreaded-plus branch, I've converted the RDA to a CSV
