### ISSUE TITLE
Create Table Permission Denied

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Achilles#276]
### Expected behavior
I am getting the following error below.  I am using SQL Server windows authentication to connect to our OMOP instance.  **Does the achilles tool need to create a table for the analysis in the schema?**  Is there anyway the analysis can be executed and exported as a csv for those with only select privileges?    Thank you for your help
### Actual behavior

Connecting using SQL Server driver using Windows integrated security
Executing multiple queries. This could take a while

  |                                                                                                                      
  |                                                                                                                |   0%Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: CREATE TABLE permission denied in database 'omop'.
An error report has been created at  \\network/users/user1/errorReport.txt

### Steps to reproduce behavior
connectionDetails <- createConnectionDetails(dbms="sql server", server="..........", 
                            schema="schema_name")
achillesResults <- achilles(connectionDetails, cdmDatabaseSchema="OMOP", 
                       resultsDatabaseSchema="OMOP", sourceName="Achilles", 
                             cdmVersion = "5", vocabDatabaseSchema="OMOP")

**Comment by t-abdul-basser** [comment]
Yes Achilles needs to create tables **in the results schema** so that it can store results in those tables. These results are used by by other OHDSI components, such as WebAPI and (via WebAPI) Atlas as well as by Achilles itself (e.g. for optional export as JSON files). 
Note again that, in the MS SQL server context, you can (and should) create a results schema that is distinct from the CDM schema and configure access to these schema as per data and application security best practices.  Typically, Atlas users , researchers, cohort definers, cohort study executors, etc are allowed write access to the results schema but read only access to the CDM schema. See ["Data Architecture"](http://www.ohdsi.org/web/wiki/doku.php?id=development:data_architecture&s[]=results&s[]=schema) in the OHDSI Wiki.

**Comment by vojtechhuser** [comment]
There is also ongoing Themis issue about how to best organize schemas at an OMOP site

**Comment by anonymous34** [comment]
Thanks @t-abdul-basser 

If there is a results schema how do we create it?  Are there DDLs out there for it?  Is the schema supposed to be included with the OMOP ddls here?

[https://github.com/OHDSI/CommonDataModel](url)

Please let me know because we are trying to do additional validation with this.  Also, does anyone have a link to the discussion @vojtechhuser  talked about above?

**Comment by t-abdul-basser** [comment]
You can create the tables in the results schema using the [results schema DDL](https://github.com/OHDSI/WebAPI/commits/master/src/main/resources/ddl). There is a DDL service in recent versions of WebAPI that provides you with the [Results schema DDL as one OHDSI SQL file](http://54.242.168.196/WebAPI/ddl/results).

The OHDSI Schema is created and updates by WebAPI on startup via it flyway migration capabilties.

You can ask questions about and discuss implementation-related issues in the implementers area at the [OHDSI Forum](http://forums.ohdsi.org/c/implementers).

**Comment by anonymous34** [comment]
Hi thank you @t-abdul-basser for the ddls.

I am trying to understand the OHDSI schema creation via webapi.  After doing some digging, I assume these are the following steps?

1) Create the database:
[http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:sqlserver_installation_guide
](url)

2) Follow these instructions:
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:webapi_installation_guide

**Comment by chrisknoll** [comment]
Yes those steps work, remember it's helpful to crate the administration database user (set in properties: flyway.datasource.username and lyway.datasource.password) separate from the normal user account (set in datasuorce.username and datasource.password).  Also, you can create the ohdsi schema in advance and ensure the flyway user has permissions to create tables, while the normal account only needs read/write.

When WebAPI starts up, if the flyway user has the proper privileges, it will automatically create the required tables. If you later upgrade WebAPI to a newer release which has ohdsi schema changes, it will automatically handle migration to the new tables without losing data.

-Chris
