### ISSUE TITLE
exportToJson JDBC driver not capable

### ISSUE THREAD

**Issue by sebbs121** [OHDSI/Achilles#277]
This bug appears everytime I run exportToJson() on Impala:
[Simba][ImpalaJDBCDriver](500320) Error during translation: code HYC00, type Driver not capable, message Impala only supports left associative joins

Full report:
DBMS:
impala

Error:
java.sql.SQLException: [Simba][ImpalaJDBCDriver](500320) Error during translation: code HYC00, type Driver not capable, message Impala only supports left associative joins

SQL:
select c1.concept_id as CONCEPT_ID, 
	c1.concept_name as CONCEPT_NAME,
	cast(ROUND(CAST((100.0*num.count_value / denom.count_value) AS DOUBLE),0) as int) as Y_NUM_PERSONS,
	num.stratum_2 as X_COUNT
from 
	(select count_value from result.ACHILLES_results where analysis_id = 1) denom,
	(select CAST(stratum_1 as int) stratum_1, CAST(stratum_2 as int) stratum_2, count_value 
	from result.ACHILLES_results 
	where analysis_id = 791) num
	left join 
	omop_cdm.concept c1 
	on num.stratum_1 = c1.concept_id
	order by num.stratum_2
	

R version:
R version 3.4.3 (2017-11-30)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.5)
- rjson (0.2.18)
- DatabaseConnector (2.1.0)
- SqlRender (1.4.10)
- devtools (1.13.5)

I tried to run this with different JDBC driver versions without any result. I also tried replacing inner joins with left, still no success. Any ideas? Did anyone experience this before?

**Comment by sebbs121** [comment]
So basically limiting amount of output rows "solves" this problem. If I find any other workaround, I'll post it here.

**Comment by t-abdul-basser** [comment]
Thank you @sebbs121. Please feel free to add more information about the workaround. 

I am closing this issue given that 1) you have identified a workaround and 2) exportToJson() is expected to be used infrequently since the preferred and recommended use case is that results are retrieved from database and viewed by Atlas (rather by AchillesWeb).  Please re-open this issue if this behavior reappears in spite of workaround.

**Comment by tarunshah** [comment]
@sebbs121  I'm having the same issue. How can i solve this issue? I didn't get the workaround.
