### ISSUE TITLE
Impala: Temp tables remains in database if query failed

### ISSUE THREAD

**Issue by wivern** [OHDSI/Achilles#278]
If one of queries failed for some reason there are number of temporary tables remains in the database.
This is not a problem for MS SQL and some others since temporary tables removing when session is closed, but an issue when using Impala.

**Comment by alondhe** [comment]
In the multithreaded-plus branch, which we are reviewing for a 1.6 release, you can use the dropAllScratchTables function to drop all of the main staging tables. However, we do have some temp tables within analyses that this function does not address. Once we release 1.6, I will fix this function to drop every possible Achilles temp table.

**Comment by chrisknoll** [comment]
This is the same problem we'll see on Oracle.  Cohort Generation proably should have some way to clean up temporary tables in event of execution error, however, if the error is that connectivity failed, you won't be able to reach the server to clean up the temp tables.

This is one of the costs of trying to implement a paradigm of temp tables on environments that don't support them in a certain way.
