### ISSUE TITLE
ANALYSIS_ID 717 - QUANTITY > 600 for DRUG_CONCEPT_ID

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#28]
When we see this error thrown it is often for drugs with fluid volumes (e.g. IV).  I'm just noting that this ERROR should be updated (but probably easier to do in CDM v5).  

Credit to Rupa figuring this one out.

**Comment by chrisknoll** [comment]
We're going to introduce the notion of errors vs. warnings.  We can downgrade this to a warning.

**Comment by vojtechhuser** [comment]
Well, we should distinguish pills from liquid drugs. And the rule should only go after pills.

**Comment by alondhe** [comment]
Yep, this is flagged as a warning instead of as an error
