### ISSUE TITLE
Extra logic in serial Heel rules

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#281]
In review of new parallel plus branch I am proposing the following:

If serial rules are executed one after another (not paralel), why do we have this prefix in all the .sql files.
Would it be possible to simply write (in serial fashion, like before) into the result table directly?

extra piece at the begining
> select *
> into @scratchDatabaseSchema@schemaDelim@tempHeelPrefix_serial_hr_@hrNewId
> from
> (
>   select * from @scratchDatabaseSchema@schemaDelim@tempHeelPrefix_serial_hr_@hrOldId
>   
>   union all

Just to note that we are trying to insert one row into heel results based on true false query against a rather simple table. 

old rule was:

> 
> **INSERT INTO @results_database_schema.ACHILLES_HEEL_results** (ACHILLES_HEEL_warning,rule_id,record_count)
> SELECT 
>  CAST('NOTIFICATION: [GeneralPopulationOnly] Count of distinct specialties of providers in the PROVIDER table is below threshold' AS VARCHAR(255)) as ACHILLES_HEEL_warning,
>   38 as rule_id,
>   cast(statistic_value as int) as record_count
> FROM @results_database_schema.ACHILLES_results_derived d
> where measure_id = 'Provider:SpeciatlyCnt'
> and statistic_value <2; --DataQuality data indicate median of 55 specialties (percentile25 is 28; percentile10 is 2)
>

**Comment by alondhe** [comment]
The main reason was because inserts are painfully slow on MPP systems like PDW and Redshift. It's actually faster to just create a bunch of staging tables and merge them. But the usage of a scratchDatabaseSchema parameter is overkill here, since these serial Heels are all temp tables anyway. I'll change them to temp tables explicitly.

**Comment by alondhe** [comment]
For serial Heels, I've updated the logic to explicitly utilize temp tables rather than use parameters that would've produced temp tables.
