### ISSUE TITLE
New Heel rule for measurements

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#282]
### Expected behavior
measurements that expect coded value will provide a logical value
(where standard_concept='S' and domain_id='Meas Value".)

Not just a possible coded value but a value that makes sense given the measurement_id

**Comment by alondhe** [comment]
@vojtechhuser please provide more detail

**Comment by fdefalco** [comment]
Heel has been superseded by DQD and is no longer under development.
