### ISSUE TITLE
Allow for re-categorization of Heel rules.

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Achilles#283]
It would be nice to provide the ability for a site to reclassify some Achilles Heel message types. For example, we do not populate locations so do not want to have those messages tagged as an ERROR. Instead if would good to reclassify it as a NOTIFICATION.

**Comment by t-abdul-basser** [comment]
Thanks @cukarthik. This is a good idea. I had a related idea. Shall we collaborate and create a proposal and then implementation.

**Comment by cukarthik** [comment]
Sounds good. I talked to @alondhe and we agreed that I'll wait until he gets his refactoring in at the end of the month.

**Comment by vojtechhuser** [comment]
I propose to revisit the current tables that support Achilles messages displayed. (data type, columns, etc) Cris Knoll had strong preferences about their structure but maybe a tweak would be good. Without corresponding Atlas changes, we will get nowhere. So we need a web developer to first give us his specs what he/she would need for fancy Atlas error page (with drill down) and then we can make changes. Making the changes and never implementing the web piece seems OK but not ideal.

**Comment by alondhe** [comment]
Described in #386
