### ISSUE TITLE
Themis and Heel

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#284]
moving email discussion to public github
(read from bottom)

**VOJTECH:**
I agree with Ajit that that is the plan 

Heel is a natural fit for it.

I have to admit that I liked Heel better as strictly non-parallelized software product. I was able to add rules and grasp quickly how it works.

With the re-stitching of the tables after parallel execution – it is trickier.

The paradigm that Heel is always running of Achilles result tables is a problem in the long term vision.

Because some DQ precomputations may have no value for data visualizations.

I think Achilles Heel requires a serious re-design. (custom threshold, ability to mute data error (make it non-issue)  (a whole annotation layer on top of heel current messages)
And keep last precomputations and track delta between ETLs. – as another new layer of doing DQ.

Vojtech

**From: Londhe, Ajit [JRDUS]**
Sent: Tuesday, June 12, 2018 3:24 PM

Subject: Re: [OHDSI Forums] [CDM Builders] Negative values in Lab test records

Heel relies upon the Achilles results tables, so I don't think it could independently certify a CDM. I think we can add THEMIS rules to Heel -- and that's on our roadmap after 1.6 is released. 

________________________________________
**From: Christian Reich**
Sent: Tuesday, June 12, 2018 12:21:39 PM
Subject: [EXTERNAL] RE: [OHDSI Forums] [CDM Builders] Negative values in Lab test records 
 
Friends:
 
If we wanted to use Achilles Heel as a Themis (and generally CDM) certifier independent from Achilles – is that possible?
 
C
 

--------------------

**From: Londhe, Ajit** 
Sent: Tuesday, May 29, 2018 19:31
To: Christian Reich; 'Huser, Vojtech (NIH/NLM/LHC) [E]'
Subject: RE: [OHDSI Forums] [CDM Builders] Negative values in Lab test records
 
Just updating Christian as I replied to the other email thread from Vojtech.
 
I committed some changes to the multithreaded-plus branch of Achilles to help (hopefully) clarify how to add or modify analyses/heels to Achilles: https://github.com/OHDSI/Achilles/blob/multithreaded-plus/README-developers.md.

**Comment by cgreich** [comment]
ok, so that it's more visible:

If we wanted to use Achilles Heel as a Themis (and generally CDM) certifier independent from Achilles – is that possible?

**Comment by cgreich** [comment]
So, should we take out Heel? And refactor it? It should also be incorporated into Arachne. It could run it automatically. AFter each refresh of the data.

**Comment by t-abdul-basser** [comment]
These are all good idea. We can create a n actual proposal in the form of a and issue or two. Marking as an enhancement and labeling as milestone v1.7.0.

**Comment by alondhe** [comment]
So are you proposing that:

1. Achilles remains only the aggregated summary statistics
2. Heel becomes a separate tool that doesn't require Achilles as a prerequisite, but rather, is a tool that evaluates CDM schema compliance, data quality, and THEMIS compliance independently from Achilles.

If this is the proposal, my issue with the 2nd point, is that this new standalone tool will probably need to run queries that are inherently already run in Achilles, right? This would mean that if you want to process Achilles and this new tool, you will be redundantly executing some long-running queries. 

Why can't we simply add THEMIS convention checks to the existing Heel?

**Comment by cgreich** [comment]
I am not sure. Achilles does standard evaluations for all entities in all tables. THEMIS is looking for specifics. Like do you use the right kind of smoking concepts, and are you putting things where they belong, and do you populate certain information the right. I don't see that much overlap.

**Comment by vojtechhuser** [comment]
>Why can't we simply add THEMIS convention checks to the existing Heel?

Consider evaluating data density at visit level or at provider level. This has no value for Achilles/Atlas visualisation but it has value for Data Quality (Themis).

So you run Achilles, then Heel.

And if you want to keep going - you run themis() function. (a deeper dive) (with stuff Atlas does not need).

So some features are added to themis().

And we can decide do it the usual heel way (status quo) or we have a new entity - themis() function inside Achilles package.

**Comment by alondhe** [comment]
This discussion has been superseded by DQ effort led by Andrew. Closing for now
