### ISSUE TITLE
No Data and ACHILLES Plots

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#288]
### Expected behavior
If there is no data, the tool tells the user 

### Actual behavior
Displays empty graphic on Drug Exposure Report

### Steps to reproduce behavior

1. Go to a CDM that contains no drugs in ACHILLES
2. Navigate to Drug Exposure Report
3. System just displays empty chart, maybe making a statement - "No data exists within this CDM"

![image](https://user-images.githubusercontent.com/6305439/42775141-a69e1cca-8901-11e8-8fb4-5998b5aa79e7.png)

**Comment by t-abdul-basser** [comment]
Thanks for making this request @ericaVoss. I agree that this feature would be helpful. However, this enhancement request should be in the Atlas repo, since we are not adding new features to AchillesWeb (it's essentially frozen with the possible exception of release patches).

**Comment by vojtechhuser** [comment]
Yes. This is wrong repo to request this
