### ISSUE TITLE
1.6 release planning

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#289]
Perhaps we can discuss the final mile of the v1.6

Feel free to edit the checklist here
![image](https://user-images.githubusercontent.com/7526119/42950626-729cd6f8-8b42-11e8-9a6f-4a53862ac3fa.png)

**Comment by t-abdul-basser** [comment]
Thank you for putting together this release planning checklist @vojtechhuser. However, the checklist shows up as a image for me. Could you edit the original comment to add the checklist like so
- [ ] Item 1
- [ ] Item 2

I have some question about v4 artifacts but will wait for you to add the checklist to ask. :)

**Comment by t-abdul-basser** [comment]
@vojtechhuser  I have some questions about v4-related task:  
* "delete old rule for v4"?: Are you referring to #265? If so, are there any other such rules? If so, please create an issue and add it to the checklist item as I did with #265.
*  "Delete of all v4 remaining code" Was this not completed in merged PR #242? If not, please create an issue and add to item.
* Did we ever make the announcement that @cgreich mentioned in #147?

**Comment by alondhe** [comment]
Hi @t-abdul-basser -- I noticed you closed #299. Are there any other outstanding items to fix?

**Comment by t-abdul-basser** [comment]
Yes, we have a couple of bugs (e.g. #301 and #290) that came up in the last round of testing.

**Comment by vojtechhuser** [comment]
I will be back from leave aug 28

**Comment by vojtechhuser** [comment]
analyses 1822, 1823 and 822 and 823 are missing in the rc

**Comment by vojtechhuser** [comment]
ajit, can you draft two sentences for readme about derived measures. current text refers to a file that is now deleted.  we have overview of them as csv.

**Comment by vojtechhuser** [comment]
also readme should be pointing folks to install latest release. not master.

**Comment by t-abdul-basser** [comment]
@vojtechhuser 
1. Have a good break!
2. missing analyses:  Thanks. Can you confirm @alondhe?
3. We will review the text prior to release. Hopefully tomorrow :) 
4. readme: good point. I will review.
