### ISSUE TITLE
Service 'achilles' failed to build

### ISSUE THREAD

**Issue by captbilard** [OHDSI/Achilles#292]
I am using docker on Ubuntu 16.04 LTS, and when i try building the image i get this error

ERROR: dependency ‘DatabaseConnector’ is not available for package ‘Achilles’
* removing ‘/usr/local/lib/R/site-library/Achilles’

Service 'achilles' failed to build: The command '/bin/sh -c R CMD INSTALL /opt/app     && rm -rf /tmp/downloaded_packages/ /tmp/*.rds     && find /opt/app -mindepth 1 -not \( -wholename /opt/app/docker-run -or -wholename /opt/app/output \) -delete' returned a non-zero code: 1

Kindly help fix

**Comment by t-abdul-basser** [comment]
Tested locally.
