### ISSUE TITLE
 Some reports that worked with older versions of ATLAS and webAPI will not work with newer versions of ATLAS and webAPI.

### ISSUE THREAD

**Issue by parkdongsu** [OHDSI/Achilles#298]
Atlas Version : 2.4.3
WebAPI version : 2.4.3

Only Dashboard, Data Density, Person, Visit, Death, and Achilles Heel is executed.

Condition Condition Era Procedure Drug Drug Era Measurement Observation is not executed.

help me.

**Comment by t-abdul-basser** [comment]
What do you mean by  not executed. Is an error thrown? Can you include paste screen shots? log excerpts?

**Comment by parkdongsu** [comment]
![error](https://user-images.githubusercontent.com/26498729/44193741-d792d980-a16e-11e8-93d4-64d20b2a1903.PNG)
![error2](https://user-images.githubusercontent.com/26498729/44193793-fd1fe300-a16e-11e8-8eed-1c0c802d50dd.PNG)

I've copied the Achilles' table from the previous version, but in the previous version, the results will work correctly.

**Comment by chrisknoll** [comment]
This looks like an error in atlas or WebAPI fetchign the results.  If you go to the 'network' tab of your browser's console, you'll see the requests that resulted in the result of '500'.  You will be able to click on those to look at the response, and see the full error message. If you could post the issue under the WebAPI repo with the short-form of the error message, (and SQL statement if it is included in the message) then we can address it there.

**Comment by t-abdul-basser** [comment]
Agreed @chrisknoll. 
@parkdongsu Please post to [Atlas](https://github.com/OHDSI/Achilles/issues).
