### ISSUE TITLE
Add docker image execution test to test suite

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#300]
### Expected behavior

Docker image executed during test.

### Actual behavior

Docker image is built but not executed during test execution (e.g. during Travis CI test or R CMD CHECK).

### Steps to reproduce behavior

Run Check from R Studio, R CMD CHECK or commits to branch to kick off CI tests.

**Comment by fdefalco** [comment]
Docker images should be modified in OHDSI in a Box as opposed to in the R package.
