### ISSUE TITLE
Use open-source vocabs to build concept paths

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Achilles#302]
Since OHDSI treats itself as an open-source community, it'd be better to use open-source vocabs as default ones in Achilles.

### Expected behavior
Properly defined concept paths in Treemap reports while using open-source vocabs from Athena.

### Actual behavior
`NA || NA || ...` due to usage of MedDRA, which is a licensed vocab.

### Steps to reproduce behavior
Execute Achilles, open Atlas reports, pick any Treemap report.

**Comment by cgreich** [comment]
@pavgra: I think what you are saying here is not to use a hierarchical system in the Achilles reports that is no available in the Public Domain. I guess that would be MedDRA, correct? In Drug, we use ATC, which is Public Domain. And we don't use anything else anywhere else, correct?

**Comment by pavgra** [comment]
@cgreich, right, I suggest picking some vocabulary available in Public Domain instead of MedDRA.

**Comment by cgreich** [comment]
Yeah. Don't think we have one. SNOMED is not stratified, i.e. there are no defined 5 layers, but randomly up to 21. So, good point, but I have no answer how to solve it.

**Comment by t-abdul-basser** [comment]
I suspected as much but thanks for confirming this @cgreich!

**Comment by vojtechhuser** [comment]
We call this an informatics problem of 'preferred ancestor'. Agree that no substitute for meddra exists.
