### ISSUE TITLE
Drop concept_hierarchy creation from Achilles

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#303]
### Expected behavior
Concept Hierarchy is a table to support the AtlasUI.  Recent updates to WebAPI have included the concept_hierarchy table in the DDL service.  The issue is now that people are executing achilles into the WebAPI schema, they may get an error without turning the 'create concept hierarchy' flag off.

But, even if disabling this flag allows it to execute Achilles without an error, we still have a problem with maintaining 2 sets of scripts to create/initialize the concept_hierarchy table. 

### Actual behavior
concept_hierarchy DDL and init are stored in 2 locations.  You will get an error if you generate concept_hierarchy into the webAPI results schema with 'createHierarchy' flag = true.

### Steps to reproduce behavior
1. Deploy webAPI.
2. Execute Achilles into the WebAPI results schema and leave 'createHeirarchy' = true.

**Comment by vojtechhuser** [comment]
So you want it completely out of Achilles code? (please clarify) (or ideally, point to R file line numbers that you want deleted)

**Comment by chrisknoll** [comment]
I'll make a PR for the change when I get a chance so you can see the entirety of the requested change.

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll. It sounds as though we need to decide which of the two component is going to maintain this feature and the associated script and then proceed accordingly. I suspect that you may be correct about Achilles adding concept hierarchy table creation in order to support the _Atlas | View Data Source_ feature, but we want to confirm that we are not using elsewhere in Achilles before we remove it. In any case, as you suggest a PR would help us focus discussion.

**Comment by alondhe** [comment]
We're not using concept_hierarchy anywhere else in Achilles, so unless there's any objections, I can remove it altogether. But will WebAPI execute the creation and the content generation?

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. Pleas feel free to submit a PR. We will hold off in integrating until a release until we can confirm that WebAPI is handling this properly.

**Comment by alondhe** [comment]
I've made this default to FALSE in my new PR. @chrisknoll -- can we drop it altogether?

**Comment by alondhe** [comment]
Spoke with @chrisknoll and he confirmed we can remove the concept hierarchy functionality. Making this a 1.7.0 milestone

**Comment by t-abdul-basser** [comment]
Excellent. Thanks!
