### ISSUE TITLE
rules for checking data on death (conforming to specs; v6)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#304]
group by query by person_id and count >= 2 triggers error severity notification

**Comment by cgreich** [comment]
@vojtechhuser: You first have to get agreement on the issue. Only afterwards we can put in a constraint.

**Comment by vojtechhuser** [comment]
relevant link https://github.com/OHDSI/Themis/issues/5

**Comment by vojtechhuser** [comment]
specs say single row but Themis seems to say multiple is OK.

**Comment by cgreich** [comment]
Correct. Needs to be fixed.

**Comment by alondhe** [comment]
We'll need more than just the rule, we'll need to add conditional logic for cdm 6 to query observation and person to generate the death analyses.

**Comment by fdefalco** [comment]
Heel has been superseded by DataQualityDashboard and will be removed.
