### ISSUE TITLE
Concept hierarchy contains multiple paths for a single drug

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Achilles#306]
### Expected behavior
Only a single path per a drug.

### Actual behavior
Several paths per a drug, which leads to ambiguous results in Atlas -> Conditions report.

### Suggested solution
Add restriction to include standard concepts only for the Ingredient join:
https://github.com/OHDSI/Achilles/blob/c920e14425d2668a7c5bdca0130c2165b2e0506f/inst/sql/sql_server/ConceptHierarchy_v5.sql#L151

**Comment by t-abdul-basser** [comment]
Thanks @pavgra . We will look at this post-1.6 release.

**Comment by vojtechhuser** [comment]
I think there is also proposal to move this stuff out of Achilles.

**Comment by t-abdul-basser** [comment]
@vojtechhuser  Good point. There is @chrisknoll #303. 
@pavgra It seems fair to assume that this may be moot as an Achilles issue depending on how we proceed of #303 so let backlog this for now.
