### ISSUE TITLE
Achilles Error in Multi-Thread mode

### ISSUE THREAD

**Issue by RogerJCarlson** [OHDSI/Achilles#311]
We had an issue using Achilles in the Single-Thread mode which we posted here:
[Achilles Error in 'Create the Concept Hierarchy'](http://forums.ohdsi.org/t/achilles-error-in-create-the-concept-hierarchy/5003)

Just for fun, I tried running Achilles in the Multi-thread mode.

```
library(Achilles)
    connectionDetails <- createConnectionDetails(
      dbms="sql server", 
      server="DBCLTYt01", 
      schema = "EpicCare.omop",
      extraSettings = "trusted_connection=true")
    
    achilles(connectionDetails, 
             cdmDatabaseSchema = "epiccare.omop", 
             resultsDatabaseSchema="epiccare.omop_results",
         vocabDatabaseSchema = "epiccare.omop",
         
         scratchDatabaseSchema = "epiccare.omop_scratch",
         numThreads = 10,
         
         sourceName = "", 
         cdmVersion = "5.2.0",
         runHeel = TRUE,
         runCostAnalysis = TRUE,
         conceptHierarchy = TRUE,
         dropScratchTables = TRUE
  )
```

This produces a different error: 
> 	Thread 2 returns error:  "Error executing SQL:ncom.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'epiccare.omop_scratch.tmpach_dist_1502'.

And I'm left with a whole bunch of scratch tables that I have to delete manually.  The same thing happens if I use conceptHierarchy = FALSE,

Deleting the files can be done by re-running the code with these modifications:

	         runCostAnalysis = FALSE,
	         conceptHierarchy = FALSE,
	         dropScratchTables = TRUE
	  	
Interestingly, it ends with the following error, which is the same as in the Single thread:

    	Error: Error executing SQL:
     	com.microsoft.sqlserver.jdbc.SQLServerException: The operation failed because an index or statistics with name 'idx_ch_cid' already exists on table 'epiccare.omop_results.concept_hierarchy'

But at least the scratch files are deleted.

**Comment by alondhe** [comment]
Hi @RogerJCarlson, 

So if there's any errors in MT execution, you can run the dropAllScratchTables() function to clean up all the tables. 

Back to your concept_hierarchy issue, I'll try to replicate it on my end and get back to you.

Thanks,
Ajit

**Comment by RogerJCarlson** [comment]
Attached is the error.txt file that I get when I run the single thread mode with 'conceptHierarchy = FALSE' the 2nd time. It has all my package versions, which might be useful.
[errorReport.txt](https://github.com/OHDSI/Achilles/files/2384142/errorReport.txt)
