### ISSUE TITLE
RedShift error - Tuple already updated

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#315]
### Expected behavior
no error when multi thread are used on redshift

### Actual behavior
```
Connecting using Redshift driver
Connecting using Redshift driver
  |==============================================================================================================| 100%
Executing SQL took 2.57 secs
Dropping scratch Achilles tables from schema CMSDESynPUF1kresults
Connecting using Redshift driver
Temporary Achilles tables removed from schema CMSDESynPUF1kresults
Executing multiple queries. This could take a while
  |=================                                                                                             |  15%Thread 22 returns error: "Error executing SQL:njava.sql.SQLException: [Amazon](500310) Invalid operation: tuple already updated by self;nAn error report has been created at  /home/vojtech/two/errorReport.txt" when using argument(s): list(analysisId = 110, sql = "-- 110\tNumber of persons with continuous observation in each month\n-- Note: using temp table instead of nested query because this gives vastly improved performance in Oracle\n\n--HINT DISTRIBUTE_ON_KEY(stratum_1) \nCREATE TABLE CMSDESynPUF1kresults.tmpach_110\n\nDISTKEY(stratum_1)\nAS\nSELECT\n110 as analysis_id,  \n\tCAST(t1.obs_month AS VARCHAR(255)) as stratum_1,\n\tnull as stratum_2, null as stratum_3, null as stratum_4, null as stratum_5,\n\tCOUNT(distinct op1.PERSON_ID) as count_value\n\nFROM\nCMSDESynPUF1k.observation_period op1\njoin \n(\n  SELECT DISTINCT \n    EXTRACT(YEAR FROM observation_period_start_date)*100 + EXTRACT(MONTH FROM observation_period_start_date) AS obs_month,\n    TO_DATE(TO_CHAR(EXTRACT(YEAR FROM observation_period_start_date),'0000FM')||'-'||TO_CHAR(EXTRACT(MONTH FROM observation_period_start_date),'00FM')||'-'||TO_CHAR(1,'00FM'), 'YYYY-MM-DD')\n    AS obs_month_start,\n    LAST_DAY(observation_period_start_date) AS obs_month_end\n  FROM CMSDESynPUF1k.observation_period\n) t1 on\top1.observation_period_start_date <= t1.obs_month_start\n\tand\top1.observation_period_end_date >= t1.obs_month_end\ngroup by t1.obs_month;\n\n\n")


```

**Comment by alondhe** [comment]
What's the content of the errorReport? And are you on the latest DatabaseConnector? We recently updated the Redshift JDBC in it.

**Comment by vojtechhuser** [comment]
DBMS:
redshift

Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: tuple already updated by self;

SQL:
--HINT DISTRIBUTE_ON_KEY(stratum_1) 
CREATE TABLE CMSDESynPUF1kresults.tmpach_110

DISTKEY(stratum_1)
AS
SELECT
110 as analysis_id,  
	CAST(t1.obs_month AS VARCHAR(255)) as stratum_1,
	null as stratum_2, null as stratum_3, null as stratum_4, null as stratum_5,
	COUNT(distinct op1.PERSON_ID) as count_value

FROM
CMSDESynPUF1k.observation_period op1
join 
(
  SELECT DISTINCT 
    EXTRACT(YEAR FROM observation_period_start_date)*100 + EXTRACT(MONTH FROM observation_period_start_date) AS obs_month,
    TO_DATE(TO_CHAR(EXTRACT(YEAR FROM observation_period_start_date),'0000FM')||'-'||TO_CHAR(EXTRACT(MONTH FROM observation_period_start_date),'00FM')||'-'||TO_CHAR(1,'00FM'), 'YYYY-MM-DD')
    AS obs_month_start,
    LAST_DAY(observation_period_start_date) AS obs_month_end
  FROM CMSDESynPUF1k.observation_period
) t1 on	op1.observation_period_start_date <= t1.obs_month_start
	and	op1.observation_period_end_date >= t1.obs_month_end
group by t1.obs_month

R version:
R version 3.5.0 (2018-04-23)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- snow (0.4-2)

**Comment by vojtechhuser** [comment]
> library(devtools)
> session_info()
Warning: Your system is mis-configured: ‘/etc/localtime’ is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to ‘Etc/Universal’ (or equivalent)
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Etc/Universal               
 date     2018-09-20                  

Packages --------------------------------------------------------------------------------------------------------------
 package           * version date       source                                     
 Achilles          * 1.6     2018-09-04 Github (OHDSI/Achilles@d5a0ff7)            
 assertthat          0.2.0   2017-04-11 CRAN (R 3.5.0)                             
 base              * 3.5.0   2018-08-25 local                                      
 bindr               0.1.1   2018-03-13 CRAN (R 3.5.0)                             
 bindrcpp            0.2.2   2018-03-29 CRAN (R 3.5.0)                             
 compiler            3.5.0   2018-08-25 local                                      
 crayon              1.3.4   2017-09-16 CRAN (R 3.5.0)                             
 DatabaseConnector * 2.1.4   2018-08-25 Github (ohdsi/DatabaseConnector@a735f45)   
 DataQuality         3.0     2018-09-14 Github (ohdsi/StudyProtocolSandbox@ce5df3c)
 datasets          * 3.5.0   2018-08-25 local                                      
 DBI                 1.0.0   2018-05-02 CRAN (R 3.5.0)                             
 devtools          * 1.13.6  2018-06-27 CRAN (R 3.5.0)                             
 digest              0.6.16  2018-08-22 CRAN (R 3.5.0)                             
 dplyr             * 0.7.6   2018-06-29 CRAN (R 3.5.0)                             
 glue                1.3.0   2018-07-17 CRAN (R 3.5.0)                             
 graphics          * 3.5.0   2018-08-25 local                                      
 grDevices         * 3.5.0   2018-08-25 local                                      
 hms                 0.4.2   2018-03-10 CRAN (R 3.5.0)                             
 magrittr            1.5     2014-11-22 CRAN (R 3.5.0)                             
 memoise             1.1.0   2017-04-21 CRAN (R 3.5.0)                             
 methods           * 3.5.0   2018-08-25 local                                      
 OhdsiRTools       * 1.5.5   2018-08-25 Github (ohdsi/OhdsiRTools@3337724)         
 OhdsiSharing      * 0.1.3   2018-08-25 Github (ohdsi/OhdsiSharing@757d1d9)        
 pillar              1.3.0   2018-07-14 CRAN (R 3.5.0)                             
 pkgconfig           2.0.2   2018-08-16 CRAN (R 3.5.0)                             
 purrr               0.2.5   2018-05-29 CRAN (R 3.5.0)                             
 R6                  2.2.2   2017-06-17 CRAN (R 3.5.0)                             
 Rcpp                0.12.18 2018-07-23 CRAN (R 3.5.0)                             
 readr             * 1.1.1   2017-05-16 CRAN (R 3.5.0)                             
 rJava               0.9-10  2018-05-29 CRAN (R 3.5.0)                             
 rjson             * 0.2.20  2018-06-08 CRAN (R 3.5.0)                             
 rlang               0.2.2   2018-08-16 CRAN (R 3.5.0)                             
 rstudioapi          0.7     2017-09-07 CRAN (R 3.5.0)                             
 snow                0.4-2   2016-10-14 cran (@0.4-2)                              
 SqlRender         * 1.5.2   2018-08-25 Github (ohdsi/SqlRender@b87d04f)           
 stats             * 3.5.0   2018-08-25 local                                      
 tibble              1.4.2   2018-01-22 CRAN (R 3.5.0)                             
 tidyselect          0.2.4   2018-02-26 CRAN (R 3.5.0)                             
 tools               3.5.0   2018-08-25 local                                      
 triebeard           0.3.0   2016-08-04 cran (@0.3.0)                              
 urltools            1.7.1   2018-08-03 cran (@1.7.1)                              
 utils             * 3.5.0   2018-08-25 local                                      
 withr               2.1.2   2018-03-15 CRAN (R 3.5.0)                             
 yaml                2.2.0   2018-07-25 CRAN (R 3.5.0)

**Comment by vojtechhuser** [comment]
I am seeing some missing analyses if I run 1+ numThreads. E.g., analysis 3 is simply missing in the results table. Weird.

**Comment by alondhe** [comment]
But aren't you unable to run with >1 threads? If an analysis throws an error, then its results won't be found.
