### ISSUE TITLE
Comment on multithreads in readme

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#316]
### Actual behavior
Readme talkes about strategy when to use multi-threading
I did two runs on small database

numThreads = 40  (time 4.5 min)
vs
numThreads = 1 (time 1 min)

Just to mention that on small databases, numThreads = 1 may be faster.

It also avoided a tuple error on Redshift

**Comment by alondhe** [comment]
40 is way too high. A Redshift cluster only has like 15 concurrency slots at most. The strategy for picking numThreads is database platform and hardware specific. 

The tuple error is new to me. We've run MT against multiple Redshift clusters without having seen it. Can you force a full re-install of DatabaseConnector?

**Comment by alondhe** [comment]
Addressed in vignette
