### ISSUE TITLE
Not able to get achilles reports for all existing tables

### ISSUE THREAD

**Issue by keshari333** [OHDSI/Achilles#318]
### Expected behavior
achilles reports for all the tables should get generated

### Actual behavior
only got reports for a few tables like(person, observation period, condition era, dashboard, and data density)

### Steps to reproduce behavior
probable cause for not getting reports for all tables.

**Comment by alondhe** [comment]
Are there any error messages that are created or errorReport.txt in your working directory? Can you post the achilles call you made (without any credentials)?

**Comment by keshari333** [comment]
allReports <- c(
"DASHBOARD",
"OBSERVATION_PERIOD",
"PERSON",
"DRUG_EXPOSURE",
"DRUG_ERA",
"DEATH",
"CONDITION_ERA",
"PROCEDURE_OCCURRENCE",
"CONDITION_OCCURRENCE",
"DATA_DENSITY",
"VISIT_OCCURRENCE",
"META")
 
exportToJson(connectionDetails, cdmDatabaseSchema = " ", resultsDatabaseSchema = " ", outputPath = " ", compressIntoOneFile = TRUE, reports=allReports)

**Comment by alondhe** [comment]
Did Achilles::achilles itself run smoothly before you ran the export?

**Comment by keshari333** [comment]
Thanks for taking out your time and replying here. :)
so, I ran this for Achilles:-
------------------
achilles(connectionDetails, cdmDatabaseSchema = "cdm5_zs_optum", resultsDatabaseSchema = "results_optum", scratchDatabaseSchema = "cdm5_zs_scratch", vocabDatabaseSchema = "cdm5_zs_optum", numThreads = 10, sourceName = "Optum DOD", cdmVersion = "5", analysisIds = subSet1, runHeel = FALSE)
===============
i used the above mentioned command. it ran properly but then it had long paragraphs like
--------------
"] "/********** OBSERVATION **********/\n\n--HINT DISTRIBUTE_ON_KEY(concept_id) \nCREATE TABLE cdm5_zs_scratch.tmpach_ch_observation\n  \nDISTKEY(concept_id)\nAS\nSELECT\nobs.concept_id,\n    obs.concept_name,\n    'Observation' AS treemap,\n    null as concept_hierarchy_type,\n    max(c1.concept_name) AS level1_concept_name,\n    max(c2.concept_name) AS level2_concept_name,\n    max(c3.concept_name) AS level3_concept_name,\n    null as level4_concept_name\n\nFROM\n(\n      SELECT\n        concept_id,\n        concept_name\n      FROM cdm5_zs_optum.concept\n      WHERE domain_id = 'Observation'\n    ) obs\n    LEFT JOIN cdm5_zs_optum.concept_ancestor ca1\n      ON obs.concept_id = ca1.DESCENDANT_CONCEPT_ID AND ca1.min_levels_of_separation = 1\n    LEFT JOIN cdm5_zs_optum.concept c1 ON ca1.ANCESTOR_CONCEPT_ID = c1.concept_id\n    LEFT JOIN cdm5_zs_optum.concept_ancestor ca2\n      ON c1.concept_id = ca2.DESCENDANT_CONCEPT_ID AND ca2.min_levels_of_separation = 1\n    LEFT JOIN cdm5_zs_optum.concept c2 ON ca2.ANCESTOR_CONCEPT_ID = c2.concept_id\n    LEFT JOIN cdm5_zs_optum.concept_ancestor ca3\n      ON c2.concept_id = ca3.DESCENDANT_CONCEPT_ID AND ca3.min_levels_of_separation = 1\n    LEFT JOIN cdm5_zs_optum.concept c3 ON ca3.ANCESTOR_CONCEPT_ID = c3.concept_id\n  GROUP BY obs.concept_id, obs.concept_name;"
----------------------------
like such there were many and then i used the earier mentioned commands for exporting. i got the json files for some tables but not all.
Also, I want to clarify does it work if we separately run for different tables or do we need to run the analysis for all the tables at a time and get reports for all.

**Comment by alondhe** [comment]
Hi @keshari333 -- we've had a few important bugfixes in the last month, can you try re-installing Achilles and re-running?

**Comment by t-abdul-basser** [comment]
Assuming that suggested solution worked and closing due to non-response.
