### ISSUE TITLE
Failed to find conversion function from unknown to text raised 

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#320]
### Expected behavior

Achilles runs without error

### Actual behavior

When Achilles is run the following error is raised:

```
org.postgresql.util.PSQLException: ERROR: failed to find conversion function from unknown to text
An error report has been created at /usr/errorReport.txt

Below is part of the error report:
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: failed to find conversion function from unknown to text

SQL:
CREATE TEMP TABLE s_tmpheel_25
AS
SELECT
analysis_id, stratum_1, stratum_2, sum(count_value) as statistic_value, measure_id
FROM(
--100000+analysis_id,
select
NULL as analysis_id,
stratum_2 as stratum_1,
cast(null as varchar(255)) as stratum_2,
count_value,
CAST(concat('ach_',CAST(analysis_id as VARCHAR), ':GlobalCnt') as varchar(255)) as measure_id
from result_cdm_synpuf_5_2_2.ACHILLES_results
where analysis_id in (1805,705,605,805,405)
) Q
group by analysis_id, stratum_1, stratum_2, measure_id

R version:
R version 3.5.0 (2018-04-23)

Platform:
x86_64-redhat-linux-gnu
```
### Steps to reproduce behavior

Here is the command that I used to run Achilles:

```
achilles(connectionDetails, 
cdmDatabaseSchema = "cdm", 
resultsDatabaseSchema="result",
vocabDatabaseSchema = "cdm",
sourceName = "SUNPUF_1K", 
cdmVersion = "5.2.2",
runHeel = TRUE,
runCostAnalysis = FALSE)
```

**Comment by leeevans** [comment]
@t-abdul-basser and @alondhe 

One of the null casts was missed in the fix for issue  #309 

The solution is to change

` NULL as analysis_id,`

to

`  cast(null as int) as analysis_id,`

in this file

https://github.com/OHDSI/Achilles/blob/07c47f3d642f46840e16beaaafe17d7bb66570bf/inst/sql/sql_server/heels/parallel/results_derived/25.sql

**Comment by alondhe** [comment]
Hi @leeevans -- I've fixed this in my latest PR: https://github.com/alondhe/Achilles/blob/master/inst/sql/sql_server/heels/parallel/results_derived/25.sql.

**Comment by leeevans** [comment]
Thanks! @alondhe I'll close this issue.

**Comment by t-abdul-basser** [comment]
Thanks @leeevans  and @alondhe. I will review PR and merge in prep for minor release ASAP.
