### ISSUE TITLE
Remove 814-Number of observation records with no value

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Achilles#326]
Remove 

"814-Number of observation records with no value (numeric, string, or concept); count () should not be > 0"

as value_as_concept_id/value_as_string/value_as_number are neither mandatory in CDM nor even exist in many Observations.

**Comment by alondhe** [comment]
Thanks @aostropolets -- the analysis (814) will stay, but I can remove the Heel requirement that this have a count > 0. Any objections @vojtechhuser ?
