### ISSUE TITLE
Question or Enhancement: Ability to get at person_ids and/or event ids behind an Achilles Heel warning or error

### ISSUE THREAD

**Issue by kmoralesml** [OHDSI/Achilles#329]
### Question or enhancement...
This is more of a question and/or an RFE if there not a way today to arrive at what is expected. 

Acknowledging that a cdm could be comprised of millions of persons, when a rule is broken, i.e. "Found N number of persons violating violating rule R", is there a way today to get a list of person_ids or other ids that are in violation, behind a warning or error in the Achilles Heel report?

Or is the vision such that, as long as the SQL statement behind a rule can be gotten, the developer can take that SQL, manipulate it, and get a listing of the person_id's or other identifiers?

The context behind this question is a scenario wherein an organization might want to get a list of person_ids to ignore or discount  from consideration moving forward in future work, such as in arriving at a cohort set.  The intent is not to delete, rather to make a decision whether or not to exclude these persons from consideration due to having unreliable/questionable data based upon 1 or more specific rules violated (which ones at the discretion or to be chosen by the organization).

Thank you.

**Comment by alondhe** [comment]
Hi @kmoralesml, 

I'd say the method you mentioned (utilizing the analysis and Heel SQL scripts), would be the best way to see the violating records. The Heel Results Shiny app shows both of these scripts when you click on a Heel result record. You can simply copy both, tweak them slightly, and write the results to your own custom tables to more closely inspect the problem.

I think anything more direct than this approach would require us to store records on person_ids, concept_ids, possibly date fields. 

Thanks,
Ajit

**Comment by kmoralesml** [comment]
Hi @alondhe.
>I think anything more direct than this approach would require us to store records on person_ids, concept_ids, possibly date fields.

Agreed.  Thank you for responding to this.
-K

**Comment by t-abdul-basser** [comment]
@alondhe This is a feature request that we are receiving from multiple sources. I recommend that consider  implementing it. Lets discuss in our meeting.

**Comment by vojtechhuser** [comment]
This is the same idea which is behind drill down functionality. And SQL piloted in the CSV file.

**Comment by alondhe** [comment]
Yep, exactly, but we would provide drill-downs for every Heel issue down to person_ids and potentially even the PKs of the specific records

**Comment by fdefalco** [comment]
Heel has been deprecated and DataQualityDashboard provides queries that return the offending records.
