### ISSUE TITLE
How to submit new analyses for Achilles (which SQL flavor to code)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#33]
In Achilles.sql file thare are many analyses.  (most likely in SQL server flavor) (or what flavor exactly)
These get translated to postgres flavor using R package.

I would like to contribute new analyses. Probably some semi-final SQL code that gets incorporated by core developer.

For authoring new analyses, in which sql flavor should I author them?
(I need rounding of real number to integer and then to multiple of 5)
e.g.,  21 rounded to 20
7 rounded to 5
6.3 rounded to 5

so it will be like x- (x % 5)  (modulo function)

How sophisticated is the flavor translation?

**Comment by t-abdul-basser** [comment]
Asked and answered.
