### ISSUE TITLE
Failed to run Achilles on Impala Database

### ISSUE THREAD

**Issue by wivern** [OHDSI/Achilles#335]
There is some issues when running Achilles on the Impala database:

1. Impala does not support "+" for string concatenation, Suggestion is to use CONCAT instead
1. Impala combine select distinct with aggregate functions or group by, Suggestion is to refactor queries
1. Impala does not allow use subqueries in select list, Suggestion is to use joins

**Comment by t-abdul-basser** [comment]
Thank you for documenting these here @wivern. Noted.
We came across some of these before. Making some of the Impala specific changes that you suggest directly in the Achilles SQL may adversely affect the performance and even the validity of the SQL for other DBs. Should we try to address these impala issues at the SqlRender-level where possible?

**Comment by pavgra** [comment]
@t-abdul-basser , could you point us to the queries with decreased performance (and which DBs we are talking about) and we'll do our best to address it?

**Comment by t-abdul-basser** [comment]
Sure. Let us finish testing and I will let you know.
