### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: relation "idx_ch_cid" already exists

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Achilles#342]
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: relation "idx_ch_cid" already exists

SQL:
create index idx_ch_cid on public.concept_hierarchy (concept_id)

R version:
R version 3.5.1 (2018-07-02)

Platform:
x86_64-apple-darwin15.6.0

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.6.3)
- DatabaseConnector (2.2.0)
- SqlRender (1.5.2)
- devtools (1.13.6)

**Comment by alondhe** [comment]
Doesn't appear to be an issue per our call, but let me know if it pops up again

**Comment by ambuj369** [comment]
Hello @alondhe 
This error popped up on R when I was running the following:
achilles(connectionDetails,
         cdmDatabaseSchema = "omop_cdm",
         resultsDatabaseSchema = "results",
         vocabDatabaseSchema = "omop_cdm",
         numThreads = 1,
         sourceName = "OMOP",
         cdmVersion = "5.3.0"
                          )

In addition to it, when I run the :+1: launchHeelResultsViewer(connectionDetails = connectionDetails,
                        cdmDatabaseSchema = "omop_cdm",
                        resultsDatabaseSchema = "results",
                        scratchDatabaseSchema = "scratch",
                        outputFolder = "/usr/tmp/",
                        numThreads = 1
                        )
The Achilles displayed blank with the error in RED saying "cannot open the connection". I am new to Achilles and Atlas so please bare with me,

**Comment by alondhe** [comment]
@ambuj369 let's focus on the first error for now. Can you try dropping the achilles tables and then re-running?

**Comment by ambuj369** [comment]
@alondhe  that worked, it says 
Done. Achilles results can now be found in schema results
Connecting using PostgreSQL driver
Connecting using PostgreSQL driver
  |================================================================================================================                            |  80%

and its stuck here. the RED circle on R is still there and looks like its doing something there. Shall I keep it like that to finish off? or what should be my next step.

**Comment by alondhe** [comment]
You can check the log file to see which analysis it is working on, and how long it has been going for. 

Can you find this and tell me?

**Comment by ambuj369** [comment]
yes. this is what is present at the end of log_Achilles.txt
2019-03-14 16:48:22	[Main thread]	INFO	Achilles	achilles	Analysis 2201 -- COMPLETE (0.015589 secs)
2019-03-14 16:48:25	[Main thread]	INFO	Achilles	achilles	Merging scratch Achilles tables
2019-03-14 16:48:26	[Main thread]	INFO	Achilles	achilles	Done. Achilles results can now be found in schema results

**Comment by alondhe** [comment]
Perhaps it is taking a while to run the index. Has a new log file for achillesHeel shown up?

**Comment by ambuj369** [comment]
No new file for Heel yet. I haven't run that part after dropping  "achilles" tables.

**Comment by alondhe** [comment]
I would kill the job, I think the R session has become hung up. The Achilles tables finished merging, so they are ready for use.

**Comment by ambuj369** [comment]
@alondhe  it worked smooth now. may be some scripts were not set correctly. So we are all set here and I am able to view the Achilles Heel page.
The another question I have if I have to run any analysis on a analysis id, I have to add the analysis id function within achilles ( ) or achillesheel( ).

**Comment by alondhe** [comment]
You'd list it in the achilles function's analysisIds parameter. Heel will expect all analyses to have been run.

**Comment by ambuj369** [comment]
ok cool. 
I am sorry for asking lot of questions.
And do we have to drop the "achilles" table all the time because everytime I am running achilles( ), I am getting the error: relation "idx_ch_cid" already exists?

Do you have a workflow which I can follow each time I have to run Achilles?


TIA

**Comment by spbima** [comment]
Index _idx_ch_cid_ is creating for _concept_hierarchy_ table. Dropping the "achilles" tables won't help.
I think that needs to add _IF NOT EXIST_ to _CREATE INDEX_ statement.

**Comment by alondhe** [comment]
@spbima we do run an operation like that by trying to drop the index before running the create step. I don't use the explicit if not exist statement because it wasn't translating correctly in SqlRender to all dialects.

**Comment by alondhe** [comment]
> ok cool.
> I am sorry for asking lot of questions.
> And do we have to drop the "achilles" table all the time because everytime I am running achilles( ), I am getting the error: relation "idx_ch_cid" already exists?
> I have selected analysisid = 2 and ran the achilles followed by achillesheel then launchHeelResultsViewer and the viewer shows results for multiple analysisids.
> Do you have a workflow which I can follow each time I have to run Achilles?
> 
> TIA

@ambuj369 -- you shouldn't need to drop the achilles tables every time, the function does that for you if you set createTables to TRUE. If you re-run achilles (with createTables = TRUE), do you still get the index error?

**Comment by ambuj369** [comment]
@alondhe Thank you for your input. 

If I set runCostAnalysis = T, will it run the analysis only for Cost other than what we mention in analysisIds?

Also, running Cost Analysis throws following error:
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "#"
  Position: 12

SQL:
drop table #s_tmpach_Drug_cost_raw

R version:
R version 3.5.2 (2018-12-20)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- tidyr (0.8.3)
- magrittr (1.5)
- DT (0.5)
- shiny (1.2.0)
- Achilles (1.6.5)
- DatabaseConnector (2.3.0)

Any idea on this?

**Comment by alondhe** [comment]
This seems to indicate you may not have the most recent commit to master, as that commit moves the drop raw cost queries to the dropAllScratchTables function and encapsulates them in an "if exists drop table" syntax.

Can you completely remove Achilles from your machine and re-install?

Also, regarding runCostAnalysis, this parameter is used to optionally include or exclude the cost analyses (which can be longer running). 

**Not specifying analysis ids means run everything**
- runCostAnalysis will then directly be referred to by the code

**Specifying analysis ids takes precedence over everything**
- including cost analysis ids in the analysis ids but then having runCostAnalysis = FALSE will result in the code modifying runCostAnalysis to TRUE
- not including cost analysis ids but then having runCostAnalysis = TRUE will result in the code modifying runCostAnalysis to FALSE

**Comment by ambuj369** [comment]
@alondhe 
I removed Achilles and did a fresh install via R and re-run the following code:
achilles(connectionDetails,
         cdmDatabaseSchema = "omop_cdm",
         resultsDatabaseSchema = "results",
         vocabDatabaseSchema = "omop_cdm",
         numThreads = 1,
         sourceName = "OMOP",
         analysisIds = seq(1,2201,by=1),
         cdmVersion = "5.3",
         runHeel = T,
         runCostAnalysis = T,
         dropScratchTables = T,
          createTable = T,
         #tempAchillesPrefix = "tmpach",
         sqlOnly = F,
         outputFolder = "output", 
         verboseMode = TRUE
                  )

which returned the same error which I mentioned in my previous post. Not sure what am I doing wrong, please suggest.

**Comment by alondhe** [comment]
@ambuj369 can you post your log files?

**Comment by ambuj369** [comment]
@alondhe  the error vanishes when I re-ran the script. I will post it when it will be back.
In addition to it, I read that we don't need to run exportToJson function anymore as Atlas will read the data directly from Achilles results.
However, when I tried that, Atlas came up blank on me.
Attached is the screenshot for Atlas. I am using CentOS and deployed Nginx as a webserver to do the inhouse tests of  the tools. Which I was able to do successfully for Achilles, but somehow Atlas is not working as expected.
Let me know your thoughts on it.
![Screenshot from 2019-03-26 20-38-03](https://user-images.githubusercontent.com/47858365/55008609-3b378c00-5007-11e9-96a8-643d68704385.png)

**Comment by alondhe** [comment]
@ambuj369 first thing that I'm seeing: Firefox isn't supported by Atlas. I would definitely switch to Chrome in order to remove that clear issue from the troubleshooting.

Have you set up your source and source_daimon table correctly? There should be a results daimon that points to the results schema that hosts the achilles results tables. 

Have you restarted the web server since running Achilles? The WebAPI needs to restart in order to cache all the data sources.

**Comment by ambuj369** [comment]
@alondhe 
Yes, my bad, I was using firefox. But when I opened it up on Chrome, I am getting the same window.
Please see the screenshot for developers tools of chrome:
![AtlasChrome](https://user-images.githubusercontent.com/47858365/55076419-57950080-50bb-11e9-944c-c1f804b23405.png)
![AtlasWindow](https://user-images.githubusercontent.com/47858365/55076422-57950080-50bb-11e9-887c-d4fbd137ab41.png)

Now, here are the entries for webapi.source and webapi.source_daimon tables, please let me know if you think of anything here. I am stuck :(
1	"CDM"	"omop_cdm"	"jdbc:postgresql://10.70.28.90:5432/omop_cdm?user=omopuser&password=omopuser"	"postgresql"


Source_Daimon:
3	1	2	"results"	2
1	1	0	"omop_cdm"	1
2	1	1	"omop_cdm"	0

Thank you

**Comment by chrisknoll** [comment]
This is the code that results in the achilles heel error:
```
        loadData() {
            this.getData()
                .then(({ data }) => {
                    this.data(data.messages.map((message) => {
```

Data should have been returned with a 'messages' array in it, but it appears that it did not.

Could you refresh the page (with the dev console open) and look on the network tab and filter requests to /cdmresults/?  Can you post what you are seeing in the call to the achillesHeel request?

**Comment by ambuj369** [comment]
@alondhe 
here is what I get:
![Screenshot from 2019-03-27 18-37-09](https://user-images.githubusercontent.com/47858365/55078123-6b426600-50bf-11e9-8b81-bc37b4159ba2.png)
![Screenshot from 2019-03-27 18-37-22](https://user-images.githubusercontent.com/47858365/55078126-6bdafc80-50bf-11e9-9fd5-110e1679c7f2.png)

**Comment by chrisknoll** [comment]
Great, can you go to the preview or response tab so we can see what the payload was?

**Comment by ambuj369** [comment]
@chrisknoll 
This is what I see in Preview for Dashboard and Achillesheel
![Screenshot from 2019-03-27 21-33-25](https://user-images.githubusercontent.com/47858365/55092208-2676f900-50d8-11e9-9100-c6c2ef93b792.png)
![Screenshot from 2019-03-27 21-33-42](https://user-images.githubusercontent.com/47858365/55092210-2676f900-50d8-11e9-93e7-1d7028051841.png)

Is that is what you are looking for?

**Comment by ambuj369** [comment]
@alondhe @chandryou 
I am also unable to view the vocabulary version under configuration section within Atlas, However, the query

select VOCABULARY_VERSION from omop_cdm.vocabulary where VOCABULARY_ID = 'None';

returned : "v5.0 27-FEB-19"

please suggest.

As well as I am unable to view data in Atlas. All the sections shows as NO DATA within.Attaching screenshots.
![Atlas1](https://user-images.githubusercontent.com/47858365/55149260-dcd9ed00-516f-11e9-8b12-9b55a0cfb34b.png)
![Atlas2](https://user-images.githubusercontent.com/47858365/55149261-dcd9ed00-516f-11e9-9c30-b6eef3909b10.png)

TIA

**Comment by alondhe** [comment]
@ambuj369 let's continue this in the forum post
