### ISSUE TITLE
validateSchema - needs to be valid for all of 5.x

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#343]
### Expected behavior
validateSchema works on 5.3.

### Actual behavior
validateSchema function appears to not work with v5.3 due to effective_drug_dose field being deprecated.

### Steps to reproduce behavior
Run validateSchema function on 5.3 CDM

**Comment by leeevans** [comment]
validateSchema() function also appears not to work with v5.3.1 due to CDM DDL replacement of time columns *_time with *_datetime. 

for example validateSchema() is looking for v5.3 CDM column observation.observation_time instead of observation.observation_datetime

See below quoted info at URL:
https://github.com/OHDSI/CommonDataModel/issues/61

> **[Suggest moving forward with fields called *_DATETIME, removing the *_TIME fields. The *_DATE fields will remain required.]**

"

**Comment by ambuj369** [comment]
@alondhe @leeevans 
I am working on OMOP CDM 5.3 and downloaded Achilles master branch using devtools::install_github("OHDSI/ACHILLES")

Now, when I do validate schema with version 5.3 mentioned, it says org.postgresql.util.PSQLException: ERROR: column "qualifier_source_value" does not exist

Checking upon validateSchema.sql, I found that it is referring to procedure_occurrence section in it which is not a part of OMOP CDM 5.3 schema.

My question is , is it a good practice to comment out such steps in validateSchema.sql OR is there is any specific version of Achilles which should be downloaded to prevent such errors.

Thank You.

**Comment by alondhe** [comment]
Hi @ambuj369 - good catch. That should be modifier_source_value. I'll make a PR to fix this.

**Comment by bfurey** [comment]
Against the v5.2.2 schema, I get the following error when running validateSchema
```
Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: column "revenue_code_source_value" does not exist
  Hint: Perhaps you meant to reference the column "cost.reveue_code_source_value".
  Position: 6720
```

**Comment by DaveBarman** [comment]
The procedure_occurrence issue above is persisting with latest I pulled from git today. Also, I get failure on location due to all caps 'STATE' field name. I see that procedure_datetime is also missing from procedure_occurrence check.

**Comment by fdefalco** [comment]
validate schema is being removed from achilles in favor of these validations as part of the DataQualityDashboard checks.
