### ISSUE TITLE
Achilles 1.6.3 not compatible with drug_era and contion_era CDM v6 tables

### ISSUE THREAD

**Issue by tropicalberto** [OHDSI/Achilles#345]
### Expected behavior
Achilles working without errors

### Actual behavior
Achilles is trying to look for drug_era_start_date, drug_era_end_date, condition_era_start_date, condition_era_end_date columns in drug_era and contion_era tables. These columns don't exist anymore in CDM v6.
### Steps to reproduce behavior
Run Achilles in a dataset converted to OMOP CDM v6.0. Specify cdmVersion=6 when running achilles(). 

### Temporal solution
* Create columns drug_era_start_date, drug_era_end_date, condition_era_start_date, condition_era_end_date
* Clone the information from drug_era_start_datetime to drug_era_start_date, drug_era_end_datetime to drug_era_end_date, condition_era_start_datetime to condition_era_start_date, condition_era_end_datetime to condition_era_end_date

**Comment by alondhe** [comment]
Hi @tropicalberto -- yes, this is a known issue, the master branch only supports v5.x right now. We have a branch to support v6 here: https://github.com/OHDSI/Achilles/tree/cdm_v6. I don't have a CDM v6 at my disposal yet, so it is untested. Do you mind trying it?

**Comment by tropicalberto** [comment]
@alondhe sure, I'll give it a try next week

**Comment by tropicalberto** [comment]
@alondhe the function achillesHeel() from this branch works without error if I run it against a CDM without the columns drug_era_start_date, etc. 
But if I try to run achillesheel through the achilles() function, I get this error once I try to run the function: 
```Connecting using PostgreSQL driver
Beginning single-threaded operations
Beginning single-threaded execution
Connecting using PostgreSQL driver
Warning: file("") only supports open = "w+" and open = "w+b": using the former
Error in readChar(pathToSql, file.info(pathToSql)$size) : 
  invalid 'nchars' argument```

**Comment by alondhe** [comment]
Ah, the relative paths aren't established properly now that I have 2 sets of SQL scripts. I'll adjust this. However, it'll be easiest for me to simply get my Synpuf dataset into v6 first, so that I can take care of testing on my side first before posting to the branch.

**Comment by tropicalberto** [comment]
@alondhe okay! if you need someone else to test it you can let me know, we have a dataset fully transformed to cdmv5

**Comment by alondhe** [comment]
Closing this because we have #333 already

**Comment by alondhe** [comment]
@tropicalberto -- we now have a good V6 branch that I'd like help testing. Please refer here for more info: https://forums.ohdsi.org/t/volunteers-needed-to-test-achilles-for-cdm-v6/9752
