### ISSUE TITLE
Heel: CDM conventions: MEASUREMENTS

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#347]
I propose one post in issues per table. I am starting with MEASUREMENTS.
Using precomputations, the drill_down query for 

MEASUREMENTS.14 would be:
edit: (as integer changed to as int)

select stratum_1,min_value from analysis_results where analysis_id=1815 and min_value < 0 
and cast(stratum_1 as int) not in (3003396,3002032,3006277,3012501,3003129,3004959,3007435)

I need help with casting across platforms. In R, I could check it much easier. And it fits the memory just fine.

https://github.com/OHDSI/CommonDataModel/wiki/MEASUREMENT#conventions
https://raw.githubusercontent.com/OHDSI/CommonDataModel/master/Documentation/CommonDataModel_Wiki_Files/StandardizedClinicalDataTables/MEASUREMENT.md

No.|Convention Description|note
:--------|:------------------------------------|---
| 1  | Measurements differ from Observations in that they require a standardized test or some other activity to generate a quantitative or qualitative result. For example, LOINC 1755-8 concept_id 3027035 'Albumin [Mass/time] in 24 hour Urine' is the lab test to measure a certain chemical in a urine sample.|n/a|
| 2  | Even though each Measurement always have a result, the fields VALUE_AS_NUMBER and VALUE_AS_CONCEPT_ID are not mandatory. When the result is not known, the Measurement record represents just the fact that the corresponding Measurement was carried out, which in itself is already useful information for some use cases.|
| 3  | Valid Measurement Concepts (MEASUREMENT_CONCEPT_ID) belong to the 'Measurement' domain, but could overlap with the 'Observation' domain. This is due to the fact that there is a continuum between systematic examination or testing (Measurement) and a simple determination of fact (Observation). When the Measurement Source Value of the code cannot be translated into a standard Measurement Concept ID, a Measurement entry is stored with only the corresponding SOURCE_CONCEPT_ID and MEASUREMENT_SOURCE_VALUE and a MEASUREMENT_CONCEPT_ID of 0.|
| 4  | Measurements are stored as attribute value pairs, with the attribute as the Measurement Concept and the value representing the result. The value can be a Concept (stored in VALUE_AS_CONCEPT), or a numerical value (VALUE_AS_NUMBER) with a Unit (UNIT_CONCEPT_ID). |
| 5  | Valid Concepts for the VALUE_AS_CONCEPT field belong to the 'Meas Value' domain. |TODO|
| 6  | For some Measurement Concepts, the result is included in the test. For example, ICD10 concept_id 45595451 'Presence of alcohol in blood, level not specified' indicates a Measurement and the result (present).  In those situations, the CONCEPT_RELATIONSHIP table in addition to the 'Maps to' record contains a second record with the relationship_id set to 'Maps to value'. In this example, the 'Maps to' relationship directs to 4041715 'Blood ethanol measurement' as well as a 'Maps to value' record to 4181412 'Present'.|
| 7  | The OPERATOR_CONCEPT_ID is optionally given for relative Measurements where the precise value is not available but its relation to a certain benchmarking value is. For example, this can be used for minimal detection thresholds of a test.|
| 8  | The meaning of Concept 4172703 for '=' is identical to omission of a OPERATOR_CONCEPT_ID value. Since the use of this field is rare, it's important when devising analyses to not to forget testing for the content of this field for values different from =.|
| 9  | Valid Concepts for the OPERATOR_CONCEPT_ID field belong to the 'Meas Value Operator' domain.|
| 10 | The Unit is optional even if a VALUE_AS_NUMBER is provided.|almost anti-heel Propose: For a subset of measurements (defined in CSV) a unit is expected. Heel notification is generated. ThemisMeasurement focus|
| 11 | If reference ranges for upper and lower limit of normal as provided (typically by a laboratory) these are stored in the RANGE_HIGH and RANGE_LOW fields. Ranges have the same unit as the VALUE_AS_NUMBER.|
| 12 | The Visit during which the observation was made is recorded through a reference to the VISIT_OCCURRENCE table. This information is not always available.|
| 13 | The Provider making the observation is recorded through a reference to the PROVIDER table. This information is not always available.|
| 14 | If there is a negative value coming from the source, set the VALUE_AS_NUMBER to NULL, with the exception of the following Measurements (listed as LOINC codes):<br><ul><li>1925-7 Base excess in Arterial blood by calculation</li><li>1927-3 Base excess in Venous blood by calculation</li><li>8632-2 QRS-Axis</li><li>11555-0 Base excess in Blood by calculation</li><li>1926-5 Base excess in Capillary blood by calculation</li><li>28638-5 Base excess in Arterial cord blood by calculation</li><li>28639-3 Base excess in Venous cord blood by calculation</li></ul> [THEMIS issue #16](https://github.com/OHDSI/Themis/issues/16) | DONE partially, commented above|

**Comment by cgreich** [comment]
> I need help with casting across platforms.

Can't you use SqLRender?

**Comment by vojtechhuser** [comment]
I do, but again I don't have PhD in SQL flavors. Ajit offered help with moving SQL queries from 90% stage to adding extra code to make it a Heel rule

**Comment by vojtechhuser** [comment]
I would like to work more on this. @alondhe , would you please provide best way to implement item 14? (in the first post?)
