### ISSUE TITLE
fetch analysis results

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#348]
### Expected behavior
make output same as before recent update for function
fetchAchillesAnalysisResults

### Actual behavior
names of columns are kept as stratum_1

My DataQuality code broke due to update of the fetch function.
Old function was renaming columns as specified in KB

see here:
https://github.com/OHDSI/Achilles/blob/v1.5.0/R/AchillesViewResults.R#L77

@alondhe 

(I can also live with no renaming ) @alondhe  (it is less work)

this was the code that broke
https://github.com/OHDSI/StudyProtocolSandbox/blob/master/DataQuality/R/checkThemis.R#L46

**Comment by alondhe** [comment]
Hi @vojtechhuser -- finally fixed this in the new PR
