### ISSUE TITLE
Schema identification suggestion

### ISSUE THREAD

**Issue by GrantLarimer** [OHDSI/Achilles#35]
The documentation for Achilles and Achilles Web has commands that take in arguments for the "names of the schemas holding the CDM data and target results ". This may be the terminology for other DB's, but in SQL Server, these arguments are the DB Name, not necessarily the schema that the tables are in within that DB.

But the more significant issue is that the SQL scripts assume the tables are in the 'dbo' schema within that DB. 'dbo' is either hardcoded into the scripts or no schema is provided, which results in falling back on the users default schema. Within our organization it's specific policy not to use 'dbo', so our implementation uses other schema's for the CDM tables. As a result, I had to modify all those scripts to get our implementation running.

We may be the only ones who face this issue, but would suggest modifying those calls to accept a source and target DB Name AND a source and target schema (perhaps this could default to 'dbo') and adjust the SQL Scripts accordingly. It could make Achilles a bit more flexible.

**Comment by schuemie** [comment]
Started a topic [here](http://forums.ohdsi.org/t/getting-rid-of-dbo-in-our-parameterized-sql/267)

**Comment by chrisknoll** [comment]
Generate and export now accept 2 parameters: cdmDatabaseSchema and resultsDatabaseSchema so that you can set which schemas you want results read/written to.
