### ISSUE TITLE
Docker build fails for v1.6.3

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#350]
### Expected behavior
It's possible to build Docker image for v1.6.3

### Actual behavior
'docker build .' command fails with the following error:

* installing to library ‘/usr/local/lib/R/site-library’
ERROR: dependencies ‘dplyr’, ‘ParallelLogger’ are not available for package ‘Achilles’
* removing ‘/usr/local/lib/R/site-library/Achilles’

### Steps to reproduce behavior

git clone https://github.com/OHDSI/Achilles.git --branch v1.6.3
cd Achilles
docker build  .

**Comment by t-abdul-basser** [comment]
Thank you @konstjar. We are able to reproduce this on my local test environment. Apparently these packages are missing from the docker build file. I will address and update shortly.
