### ISSUE TITLE
Database Connections are more than threads count.

### ISSUE THREAD

**Issue by Hazealign** [OHDSI/Achilles#353]
### Expected behavior

I expected the database connection will be constructed as much as thread created.
 
### Actual behavior

Achilles construct database connections more than created threads.

#### Before Execute Achilles 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/1115741/49773786-bc5b6380-fd35-11e8-8342-a8e95dcb55bd.png">

#### Running Achilles
<img width="681" alt="image" src="https://user-images.githubusercontent.com/1115741/49773741-9b930e00-fd35-11e8-90f0-42a8caa3395d.png">

#### Check Database's Connections (in MS SQL Server)
```sql
SELECT DB_NAME(sP.dbid) AS the_database
  , COUNT (sP.spid) AS total_database_connections
  FROM msdb.sys.sysprocesses sP
  GROUP BY DB_NAME(sP.dbid)
  ORDER BY 1;
```

#### Achilles Code
```r
library(Achilles)

connectionDetails <- readRDS('./credentials/mssql-develop.rds')

achilles(connectionDetails,
         cdmDatabaseSchema = "CDM_NHIS.dbo",
         resultsDatabaseSchema = "NHIS_DB_OHDSI.dbo",
         scratchDatabaseSchema = "NHIS_DB_OHDSI.dbo",
         vocabDatabaseSchema = "CDM_NHIS.dbo",
         numThreads = 64,
         sourceName = "CDM_NHIS",
         cdmVersion = "5.3.2",
         runHeel = TRUE,
         runCostAnalysis = FALSE,
         conceptHierarchy = TRUE,
         createIndices = TRUE)

exportToJson(connectionDetails,
             cdmDatabaseSchema = "CDM_NHIS.dbo",
             vocabDatabaseSchema = "CDM_NHIS.dbo",
             resultsDatabaseSchema = "NHIS_DB_OHDSI.dbo",
             outputPath = "./Achilles",
             compressIntoOneFile = TRUE)
```

**Comment by pavgra** [comment]
Observing the same behavior

**Comment by alondhe** [comment]
Interesting. So you're seeing 168 concurrently active connections when running Achilles, even though you specified to use at most 64. 

There must be some parts of the function that are not closing their connections cleanly. I'll take a look.

**Comment by t-abdul-basser** [comment]
Thanks @alondhe!

**Comment by alondhe** [comment]
I think it may be related to the calls to DatabaseConnector::disconnect. I'm trying to use on.exit() to ensure that those calls are made when each function completes.

**Comment by Hazealign** [comment]
@pavgra @alondhe thanks a lot! :+1:
