### ISSUE TITLE
Use ParallelLogger instead of OhdsiRTools, also for multi-threading

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Achilles#355]
I see many calls to OhdsiRTools (for example [here](https://github.com/OHDSI/Achilles/blob/7bccb474bac5b60138e5481e2099315226133f50/R/Achilles.R#L333)) to support the multi-threading. However, those functions have all been moved to ParallelLogger, and will soon be deprecated (and later removed) in OhdsiRTools. 

Probably a folder-wide find-and-replace of 'OhdsiRTools' with 'ParallelLogger' will do the trick..

**Comment by t-abdul-basser** [comment]
Thanks for the reminder @schuemie!
