### ISSUE TITLE
Docker misses parameter to pass for concept_hierarchy table generation

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#357]
### Expected behavior
There is parameter to enable/disable concept_hierarchy generation for Docker

### Actual behavior
No parameter

### Steps to reproduce behavior
NA

**Comment by t-abdul-basser** [comment]
Please note that as per #303 we expect to drop concept_hierarchy creation from Achilles.  Exposing the requesting parameter in the Docker run interface is therefore inconsistent with development plan.
