### ISSUE TITLE
Update Achilles Wiki page

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#358]
### Expected behavior

OHDSI Wiki - Achilles page is up-to-date

### Actual behavior

OHDSI Wiki -Achilles page is not up-to-date

### Steps to reproduce behavior

View Achilles page

**Comment by alondhe** [comment]
Hi @t-abdul-basser, took a shot at this: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:achilles

**Comment by t-abdul-basser** [comment]
Excellent! Thanks.
