### ISSUE TITLE
Achilles error : Incorrect syntax near ')'

### ISSUE THREAD

**Issue by YangDaeIl** [OHDSI/Achilles#359]
Setting up single thread 

library(Achilles)
connectionDetails <- createConnectionDetails(
  dbms="redshift", 
  server="server.com", 
  user="secret", 
  password='secret', 
  port="5439")
Error when entering
The generated errorreport.

Error:
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ')'.
SQL:
select * into #tempResults
from
(
  select
    t2.count_value*100.0/all_count as statistic_value,
  CAST('Meas:NoNumValue:Percentage' AS VARCHAR(100)) as measure_id
  from
  (
    select sum(count_value) as all_count from CDM_daeil2.dbo.achilles_results where analysis_id = 1820
  ) t1 join (select count_value from CDM_daeil2.dbo.achilles_results where analysis_id = 1821) t2
) t3

I'll be waiting for the reply. Thank you.

**Comment by chrisknoll** [comment]
looks like there's a problem with the t1 join to t2.  There should be an ON clause there...where t1 joins to t2 soemway.  If not, then it should use a CROSS JOIN instead of just a join.

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll. This may be related to #260. May be the results of cross join fixes (#280) that did not make it into multi-thread refactor. Investigating.

**Comment by YangDaeIl** [comment]
Thanks @chrisknoll  If the github statement does not contain an 'on' clause, is it wrong?

**Comment by YangDaeIl** [comment]
> Thanks @chrisknoll If the github statement does not contain an 'on' clause, is it wrong?

Achilles/inst/sql/sql_server/heels/serial/rule_28.sql

**Comment by chrisknoll** [comment]
I'm pretty sure if you use JOIN (LEFT or RIGHT) you require ON.  Otherwise, CROSS JOIN does not.

**Comment by dramacloak** [comment]
I'm seeing this exact issue as well when running Achilles Heel in R for postgresql.

**Comment by t-abdul-basser** [comment]
Noted. PR with fix is in progress.

**Comment by vojtechhuser** [comment]
So I am to blame since this is probably my SQL code - before switching to multithreading. 

It would be easier to author the logic and checking in R. 
No fancy multithreading is required for this and can be done in memory. 
Without translation problems into many SQL dialects.
