### ISSUE TITLE
Single Threaded runs heel twice

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#370]
### Expected behavior
One execution of Achilles Heel
### Actual behavior
Connecting using SQL Server driver using Windows integrated security
Connecting using SQL Server driver using Windows integrated security
  |============================================================================================================================================| 100%
Executing SQL took 0.245 secs
Beginning single-threaded operations
Beginning single-threaded execution
Beginning single-threaded execution
Connecting using SQL Server driver using Windows integrated security
Executing Achilles Heel. This could take a while
Executing Achilles Heel. This could take a while....

The I get this errror:
Done. Achilles Heel results can now be found in synpuf1000_results
Done. Achilles Heel results can now be found in synpuf1000_results
Error: host must be a single element of type 'character'

### Steps to reproduce behavior

I ran this command on a synpuf1000 database.

achilles(connectionDetails, 
         cdmDatabaseSchema = "synpuf1000", 
         resultsDatabaseSchema = "synpuf1000_results",
         scratchDatabaseSchema = "scratch",
         vocabDatabaseSchema = "synpuf1000",
         numThreads = 1,
         sourceName = "Synpuf1000", 
         cdmVersion = "5.3.0",
         runHeel = TRUE,
         runCostAnalysis = FALSE)

**Comment by alondhe** [comment]
Yes, I'm seeing this too. Will investigate
