### ISSUE TITLE
Add execution time as new analyses

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#371]
Add execution times of achilles and achillesHeel functions as new analyses

**Comment by alondhe** [comment]
@vojtechhuser and @t-abdul-basser -- in speaking with @fdefalco, it appears there is interest in having these benchmarks available through achilles tables rather than custom tables, so that Atlas developers can pull these benchmarks into Atlas as a report. Unless you disagree, I was thinking I'd go ahead with the PR that writes these times to the achilles_results and achilles_results_dist tables.

**Comment by vojtechhuser** [comment]
I agree

**Comment by t-abdul-basser** [comment]
Ditto

**Comment by alondhe** [comment]
Added via PR
