### ISSUE TITLE
Should this be @cdmDatabaseSchema.cohort?

### ISSUE THREAD

**Issue by HeathHopkins** [OHDSI/Achilles#372]
https://github.com/OHDSI/Achilles/blob/d5a0ff786ae219d8773d9d45332ca51a682cd017/inst/sql/sql_server/validate_schema.sql#L48

**Comment by chrisknoll** [comment]
No, the results schema's cohorts is where analytical tools write cohort results.  The CDM's cohort table is for standardized cohorts and we do not write to those tables.  In some environments, the CDM schema is set to 'read only' so that's another reason.

**Comment by HeathHopkins** [comment]
Thanks.  I just read the CDM spec and missed that there were two tables in the result schema.
