### ISSUE TITLE
Error Exporting Results

### ISSUE THREAD

**Issue by CartWill** [OHDSI/Achilles#373]
### Expected behavior
Executing the following for BigQuery should generate a file export of the Achilles Results
```
exportToJson(connectionDetails, 
  cdmDatabaseSchema = "synpuf_omop", 
  resultsDatabaseSchema = "achilles_results", 
  outputPath = "c:/Achilles/AchillesExport", 
  compressIntoOneFile = TRUE
  )
```
### Actual behavior
Throws and error:
```
Connecting using BigQuery driver
Generating condition treemap

  |                                                                                                                  
  |                                                                                                            |   0%Error: Error executing SQL:
java.sql.SQLFeatureNotSupportedException: [Simba][JDBC](10220) Driver does not support this optional feature.
```

The SQL generated appears to be trying to concatenate strings with 

`  IFNULL(concept_hierarchy.soc_concept_name,'NA') + '||' + IFNULL(concept_hierarchy.hlgt_concept_name,'NA') + '||' + IFNULL(concept_hierarchy.hlt_concept_name,'NA') + '||' + IFNULL(concept_hierarchy.pt_concept_name,'NA') + '||' + IFNULL(concept_hierarchy.snomed_concept_name,'NA') concept_path`

but it appears BigQuery does not support that.  From their documentation, they want to use a concat function... 

`CONCAT(IFNULL(concept_hierarchy.soc_concept_name,'NA'), '||', IFNULL(concept_hierarchy.hlgt_concept_name,'NA'), '||', IFNULL(concept_hierarchy.hlt_concept_name,'NA'),'||', IFNULL(concept_hierarchy.pt_concept_name,'NA'), '||', IFNULL(concept_hierarchy.snomed_concept_name,'NA')) concept_path`

### Steps to reproduce behavior
Run the export function against BigQuery.  If I swap out the syntax, the query will execute and produce results.

The error output is attached.
[errorReport.txt](https://github.com/OHDSI/Achilles/files/2912646/errorReport.txt)

**Comment by chrisknoll** [comment]
I believe there are oracle rules to convert || to concat, if we want to copy those rules into bigquery in SqlRender.

**Comment by alondhe** [comment]
I've opened an issue in SqlRender: https://github.com/OHDSI/SqlRender/issues/161. Let's handle this there, closing this issue for now.

**Comment by pavgra** [comment]
I would re-open this due to https://github.com/OHDSI/SqlRender/issues/161#issuecomment-470341043

**Comment by alondhe** [comment]
Thanks @pavgra. Re-opening and will investigate changing the + operators

**Comment by AklomDesta** [comment]
Hello, I am facing the same issue with big-query and exportToJson function. I want to check you guys out ,if you guys are still working to make same changes on sqlConditionTreemap.sql.
*********** the error message  *************
No matching signature for operator + for argument types: STRING, STRING. Supported signatures: INT64 + INT64; FLOAT64 + FLOAT64; NUMERIC + NUMERIC at [2:3]

**Comment by CartWill** [comment]
Hello.  We're still experiencing this issue and can't export our results.

**Comment by alondhe** [comment]
Hi @CartWill -- can you try the new concat_2020 branch?

1. Restart R
2. `remove.packages("Achilles")`
3. `devtools::install_github("OHDSI/Achilles", ref = "concat_2020")`

**Comment by t-abdul-basser** [comment]
@CartWill Did the branch that @alondhe mentioned work for you?
