### ISSUE TITLE
Logic of cost_distribution_template

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Achilles#374]
In the `cost_distribution_template.sql` there is the SQL:
```
select 
  subject_id as stratum1_id, 
  CAST(avg(1.0 * @costColumn) AS FLOAT) as avg_value,
  CAST(stdev(@costColumn) AS FLOAT) as stdev_value,
  min(@costColumn) as min_value,
  max(@costColumn) as max_value,
  @costColumn as count_value,
  count_big(*) as total,
  row_number() over (partition by subject_id order by @costColumn) as rn
into @scratchDatabaseSchema@schemaDelim@tempAchillesPrefix_overallStats_@analysisId
from @scratchDatabaseSchema@schemaDelim@tempAchillesPrefix_@domainId_cost_raw
where @costColumn is not null
group by subject_id, @costColumn
;
```

What is the logic in having `min(@costColumn)`, `max(@costColumn)` and `group by @costColumn` at the same time? Not sure whether it makes sense. Shouldn't it only group by subject_id? And shouldn't the `count_value` have aggregation function also?

**Comment by alondhe** [comment]
Hi @pavgra ,

Looks like we have an issue with the translation of the older code (<= 1.5.0) and the newer code (1.6.0+). This query is ultimately meant to help characterize a cost column by patient, but instead, we have a 1-to-many of patient to statistics grouped by cost column values.

I'm working on a bugfix, will make a PR soon.

Thanks,
Ajit

**Comment by t-abdul-basser** [comment]
Thanks @alondhe!
