### ISSUE TITLE
heel rule for PROCEDURE_OCCURRENCE convention 10

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#375]
for PROCEDURE_OCCURRENCE
this SQL should a count of 0 rows with quantity of 0

```select count(*) as cnt from procedure_occurrence where quantity=0```

Help from Ajit is solicited to put this as SQL-logic based rule
@alondhe 

per this themis issue https://github.com/OHDSI/Themis/issues/26

**Comment by fdefalco** [comment]
Heel has been superseded by DQD.
