### ISSUE TITLE
Shorten temp table names for Oracle

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#378]
### Expected behavior
Temp table names should align with all RDBMS requirements

### Actual behavior
We create temp tables that have names that throw SqlRender warnings due to their length:

`Warning: Temp table name '#s_tmpach_statsView_1608' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
`
### Steps to reproduce behavior
Run Achilles

**Comment by ambuj369** [comment]
@alondhe  any fix available for this? I am also receiving the same error.

**Comment by alondhe** [comment]
Not yet, but these aren't errors, these are warnings. And they won't affect anyone using postgres

**Comment by hongwonjun** [comment]
What does 'tmpach' (default value of tempAchillesPrefix) mean?
If there is no special meaning, it would be better to abbreviate this word.
