### ISSUE TITLE
Field missing causing Achilles to crash at 59% complete

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Achilles#38]
I am trying to run Achilles on CDM V5. After following the installation instructions in this page, I managed to get until 59% complete and then I get this error (extracted from the error log)

DBMS:
postgresql

Error:
execute JDBC update query failed in dbSendUpdate (ERROR: column vo1.place_of_service_concept_id does not exist
  Position: 114)

SQL:
insert into results_schema.ACHILLES_results (analysis_id, stratum_1, count_value)
select 200 as analysis_id, 
	vo1.place_of_service_CONCEPT_ID as stratum_1,
	COUNT(distinct vo1.PERSON_ID) as count_value
from
	visit_occurrence vo1
group by vo1.place_of_service_CONCEPT_ID

After looking at the CDM V5 fileds for the visit_occurrence table, the column place_of_service_CONCEPT_ID does not exist. 

Any suggestions? or is there a different way to run the CDMV5 Achilles, other than the instructions found in this page.

Thanks!

**Comment by pbr6cornell** [comment]
Juan:  Did you pull the latest ACHILLES with the v5 code?   The code you're
showing there is for ACHILLES to run on CDMv4.  Cheers, Patrick

**Comment by jmbanda** [comment]
My bad, I assumed the main repo version was the newest one. I found the new version under releases, I will run this one now. 

Thanks.
