### ISSUE TITLE
Error while drop temporary tables in BigQuery

### ISSUE THREAD

**Issue by spbima** [OHDSI/Achilles#380]
### Expected behavior
Temporary Achiles tables removed

### Actual behavior
When Achiles try to remove temporary tables _tmpach_Drug_cost_raw_ and _tmpach_Procedure_cost_raw_ we get errors

![bigquery-achilles](https://user-images.githubusercontent.com/804934/54347153-7628df80-4657-11e9-8bea-d1bb76eaf0de.jpg)

```
cat errorReport.txt
DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100033) Error getting job status.

SQL:
drop table synpuf_2m_cdm_53_results.tmpach_Drug_cost_raw

R version:
R version 3.5.2 (2018-12-20)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.6.5)
- DatabaseConnector (2.3.0)
```

**Comment by alondhe** [comment]
@spbima looks like we are missing an "if table exists" around that drop SQL. I'm making a PR to address this.
