### ISSUE TITLE
Out of date documentation?

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Achilles#381]
I have been referencing the [Achilles vignette](https://github.com/OHDSI/Achilles/raw/master/vignettes/RunningAchilles.pdf) and it details using both the achilles() and achillesHeel functions() however, the achilles() function now has a runHeel boolean operator that is defaulted to TRUE which essentially runs both achilles() and achillesHeel() in one call. Should this be clarified in the documentation?

**Comment by alondhe** [comment]
That parameter has always been there, but you're right, in the vignette, as we're walking through each function separately, we should set runHeel to FALSE.
