### ISSUE TITLE
Make Heel rules be not dependent on CDM v5 or v 6 (or even support PCORNet)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#384]
### Expected behavior
Heel does not need to rewritten for v6
ACHILLES_RESULTS table with pre-computed measures provides an interim layer

**Comment by alondhe** [comment]
I agree that all Heel SQLs are written against achilles results tables, so CDM version should not be consequential. What is the request here?

**Comment by alondhe** [comment]
Closing, since we may roll Heel into DQD
