### ISSUE TITLE
Add configurable issue classifications

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#386]
### Expected behavior
Sites can review only a list of Heel output. Avoid overwhelming the site.

### Actual behavior
No way to exclude a set of rule_ids

**Comment by vojtechhuser** [comment]
Suggested by David B.

**Comment by alondhe** [comment]
@vojtechhuser is the proposal that we would provide a parameter to limit the Heel rules within achillesHeel()?

**Comment by djb2188** [comment]
Yes. For Projects like AOU where they ramp up rules you enable rule deployment. Like you said a you can push out a rule config file which sites import.

**Comment by vojtechhuser** [comment]
Either way implementation is possible.
not run the rules at all.

but I think the rules can still be executed and we would simply not fetch all results in fetchHeel function.

But I am not married to a given choice. As long as we can somehow filter.

**Comment by djb2188** [comment]
That works well. On/Off for fetch.

**Comment by alondhe** [comment]
So to be clear: the proposal is to add a parameter in fetchAchillesHeelResults to limit the returned Heel results, essentially adding a where clause to `select * from achilles_heel_results`. 

We can filter by the following choices (and any combination of them): 
1. analysis_id 
2. rule_id 
3. Heel type (warning, error, notification) -- though this is already possible by using the search in the shiny app launched by launchHeelResultsViewer(). 

Which of these options were you looking for?

**Comment by alondhe** [comment]
Per @cukarthik , the ask is that we allow configurable issue classifications. That is, allow users to pre-define the classifications of heel rules (e.g. error to notification).
