### ISSUE TITLE
Achilles Heel Output - More Information on Specific Issues on Issue Prevelance

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#39]
Right now the Achilles Heel report only gives counts at the CONCEPT_ID level.  Example:  

ERROR: 706 - Distribution of age by observation_concept_ID (count = 16); min value should not be negative.

The count 16 is on the CONCEPT_ID, but that doesn't tell you how prevalent the issue is.  It would be nice to know how many records and how many people it affects.  

This is a feature requested by the Erasmus folks.

**Comment by fdefalco** [comment]
Heel has been superseded by DQD
