### ISSUE TITLE
Invalid object name

### ISSUE THREAD

**Issue by pgallins** [OHDSI/Achilles#391]
I installed OHDSI/WebAPI using Microsoft SQL Server.  I am having trouble running the Achilles analysis.  I have these two R commands:

connectionDetails <- createConnectionDetails(dbms="sql server", server="localhost", user="ohdsi_app_user", password="app1", schema="OHDSI")

achilles(connectionDetails, cdmDatabaseSchema="OHDSI.dbo", cdmVersion=5)

I am getting this error:
ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'OHDSI.dbo.person'.

**Comment by alondhe** [comment]
Can you confirm that the person table exists in the schema?

**Comment by alondhe** [comment]
Closing for now - @pgallins please reply if this is still happening
