### ISSUE TITLE
Query processor error and inconsistent multithreaded behavior on pdw

### ISSUE THREAD

**Issue by AnthonyMolinaro** [OHDSI/Achilles#394]
### Expected behavior
Successful execution of Achilles for 207 analyses.
### Actual behavior
Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: The query processor ran out of stack space during query optimization. Please simplify the query.

### Steps to reproduce behavior
1. Run Achilles using  branch source_concepts.  
2. With the new *25.sql analysis_ids added, there are now a total of 207 and the error above occurs.
3. Setting numThreads  = 2 fixes that problem, but introduces another: approximately 20 rows from each analysis are not inserted into achilles_results.  They do appear in their corresponding tmpach table, but not all the rows make it into achilles_results.  Changing numThreads to 4 fixed that problem.

**Comment by alondhe** [comment]
Since we don't run Achilles on PDW, closing for now
