### ISSUE TITLE
Achilles leaves temp tables for BigQuery

### ISSUE THREAD

**Issue by spbima** [OHDSI/Achilles#400]
### Expected behavior
After Achilles is completed in result scheme in BigQuery haven't temp tables

### Actual behavior
Achilles for BigQuery leaves temp tables after run (last master). The base was clean before launch.

![image](https://user-images.githubusercontent.com/804934/56795472-3722a800-6819-11e9-81f8-754dd99e0ef3.png)

### Steps to reproduce behavior
Run Achilles on clean BigQuery base

**Comment by alondhe** [comment]
Hi @spbima -- does the dropAllScratchTables function help clear this, or no?

Also, in BigQuery, how are temp table prefixes assigned? Is it random?

**Comment by alondhe** [comment]
@leeevans do we have an OHDSI BigQuery instance?

**Comment by mgkahn** [comment]
Colorado does....


________________________________

**Comment by alondhe** [comment]
From Google:

>A temporary table is a randomly named table saved in a special dataset. Temporary tables are used to cache query results. A temporary table has a lifetime of approximately 24 hours. Temporary tables are not available for sharing, and are not visible using any of the standard list or other table manipulation methods. You are not charged for storing temporary tables.

Is there a way to know programmatically what random name is assigned? Without this, I'm not sure how to explicitly drop them without the user actually telling the function. Though it seems BigQuery drops them after 24 hours anyway....

**Comment by alondhe** [comment]
Hi @spbima -- can you weigh in on my last post? I'd like to add appropriate functionality to Achilles to clean up temp tables in BigQuery.

**Comment by alondhe** [comment]
@spbima , @pavgra looking for some BigQuery guidance here. Can you comment on my question above?

**Comment by t-abdul-basser** [comment]
Thanks @alondhe!

**Comment by alondhe** [comment]
I think this has been handled by the .supportsTempTables function giving FALSE for bigquery

**Comment by Andreyyiv** [comment]
@alondhe the same two tables remain in Oracle:
```
%random%SERIAL_HR_44
%random%SERIAL_RD_37
```
Not sure if this should be a separate issue.

**Comment by alondhe** [comment]
@Andreyyiv -- can you raise a new issue?

**Comment by Andreyyiv** [comment]
created https://github.com/OHDSI/Achilles/issues/466
