### ISSUE TITLE
voting on important architecture options

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#401]
Per Patricks  recent forum post, 
http://forums.ohdsi.org/t/a-proposal-for-maturing-our-open-community-development-activities/6728

I found this chapter very nice
https://producingoss.com/en/social-infrastructure.html
(do we have a good BD ?)

We should have a voting strategy for important issues 
https://producingoss.com/en/consensus-democracy.html#when-to-vote

**Comment by alondhe** [comment]
Additionally, I think we should try to nominate a database expert for each supported database platform. Too often, we have developed new functionality for Achilles that can't work across all platforms.

I can be this person for Redshift, PDW, SQL Server, and Postgres, but cannot for MySql, Oracle, and BigQuery. Do we have any experts on those platforms?

**Comment by t-abdul-basser** [comment]
Good idea. Micheal Khan and the Colorado team might be available for BigQuery. I am available as a BigQuery resource.

**Comment by t-abdul-basser** [comment]
@vojtechhuser Thanks for the materials. Let's discuss during the WG meetings.
