### ISSUE TITLE
docker-run redundant parameter cdmVersion  

### ISSUE THREAD

**Issue by acumarav** [OHDSI/Achilles#402]
docker-run script still supply cdmVersion parameter to exportToJson whereas 
R/exportToJson no longer expect it which cause docker mode execution failure
### Expected behavior
Docker execution mode should generate json documents
### Actual behavior
Failure message: unused argument (cdmVersion = env_vars$ACHILLES_CDM_VERSION)
### Steps to reproduce behavior
Run achilles in docker mode

**Comment by alondhe** [comment]
Hi @acumarav -- can you try this again using my fork?
https://github.com/alondhe/Achilles

**Comment by alondhe** [comment]
Recent PR took care of this
