### ISSUE TITLE
Achilles Heel Rule 11 needs to be updated to use "Provider" domain_id instead of obsolete "Provider Specialty"

### ISSUE THREAD

**Issue by cuhrich** [OHDSI/Achilles#404]
### Expected behavior
Achilles Heel Rule 11 should not report an error for specialty_concept_id values that have a domain_id of "Provider".

### Actual behavior
Rule 11 looks for specialty_concept_id values with a domain_id of "Provider Specialty". This domain_id appears to have been changed to "Provider" in a recent release of the vocabularies.

### Steps to reproduce behavior
Run Achilles Heel with provider.specialty_concept_id values for specialty concepts from the "Provider" domain.

### How to fix
Update rule_11.sql to use a domain_id of "provider" in the where clause:

  WHERE or1.analysis_id IN (301)
  	AND or1.stratum_1 IS NOT NULL
  	AND c1.concept_id <> 0 
    AND lower(c1.domain_id) NOT IN ('provider')

**Comment by alondhe** [comment]
Hi @cuhrich -- hmm, I still have it as Provider Specialty in our CDMs. Can you point us to the documentation on where this changed?

**Comment by cuhrich** [comment]
I'm working on a project with All of Us and we refreshed our vocabularies on 4/17/19. It looks like the domain_id for "Provider Speciality" changed in this version to just "Provider" (Athena displays this as the domain ID as well). The name of the domain is still "Provider Specialty", but rule 11 references the domain_id column.
<img width="532" alt="Provider" src="https://user-images.githubusercontent.com/1562085/57587558-a4e6f900-74d4-11e9-8460-e05ddb22fc72.png">

**Comment by cgreich** [comment]
True. We changed the domain_id to "Provider", because it goes higher than just medical specialty of physicians. And then we forgot to change the domain_name. Will fix.

**Comment by alondhe** [comment]
@cgreich -- so we should make this change to use "Provider", correct?
