### ISSUE TITLE
In Heel UI, see successful checks

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#407]
It would be nice to see the successful Heels in the UI

**Comment by alondhe** [comment]
To clarify: this means writing out successful issue checks to the achilles_heel_results table and also changing the logic in the Atlas Data Source UI to handle a new column

**Comment by alondhe** [comment]
Tagging @vojtechhuser -- as this came up during today's DQ call

**Comment by vojtechhuser** [comment]
we can add the column and infrustruture.

we can also assume the checks that did not output error were sucessfull. just a thought. maybe it would not work.

**Comment by fdefalco** [comment]
Heel has been superseded by DataQualityDashboard.
