### ISSUE TITLE
Achilles Heel fails when query planner decides to run `CAST` condition first

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Achilles#408]
Some of Achilles Heel queries have `where` conditions with `CAST`-s:
```
where analysis_id in (3)
and cast(stratum_1  as int64) > EXTRACT(YEAR from CURRENT_DATE())
and count_value > 0
```

In some cases, BigQuery query planner decides to execute the `cast` condition first and therefore it tries to cast e.g. strings which obviously leads to an error:
```
Bad int64 value: condition_occurrence; while executing the filter on column 'stratum_1'
```

This could be avoided by running `where analysis_id in (3)` in a nested subquery or using a `SAFE_CAST` (while I'm not sure whether the latter is available in all DBs)

**Comment by alondhe** [comment]
Hmm, so BigQuery is picking its own order for these where clauses. Interesting. Could you identify all of the Heel scripts that fail?

**Comment by chrisknoll** [comment]
PDW has the same sort of issues.  RedShift as well.

**Comment by fdefalco** [comment]
This issue has been resolved.  Also, Heel has been deprecated and should no longer be run.
