### ISSUE TITLE
Error when running Achilles against CDM v5

### ISSUE THREAD

**Issue by wistephens** [OHDSI/Achilles#41]
I updated my R  install with the latest Achilles and SQLRender packages in order run against a CDM v5 database instance. Everything appears to work fine until I attempt to export the JSON. At this point, the  query appears to be referring to vocabularies via numerical ID a la CDM v4 (1) rather than name (SNOMED)

> exportToJson(pgConnectionDetails,"public", "achilles_results", "/Users/wstephens/ext/OHDSI/AchillesWeb-master/data/Test")
>   |                                                                                                                                |  
> 0%Error executing SQL: Error in .jcall(s, "Ljava/sql/ResultSet;", "executeQuery", as.character(query)[1]): org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = integer
>   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
>   Position: 1075

An error report has been created at  /Users/wstephens/errorReport.txt
Error in value[[3L]](cond) : no loop for break/next, jumping to top level

![screen shot 2015-01-13 at 3 01 59 pm](https://cloud.githubusercontent.com/assets/928908/5728034/464ef3f2-9b35-11e4-9126-2fb85e301502.png)

**Comment by chrisknoll** [comment]
the vocabulary_id = 1 looks like that was from CDMv4. in v5 those are varchars.  Could you ensure that you have the latest code, and that you are running the analysis specifying the correct cdm version?

**Comment by t-abdul-basser** [comment]
No response from OP. No issue raised subsequently.
