### ISSUE TITLE
introduce sets of `analysis_id`s

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#411]
based on this (last column of linked_measure)
https://github.com/OHDSI/Achilles/blob/master/inst/csv/heel/heel_rules_all.csv

Define a constant in the package 
ACHILLES_LEVEL_01 = c(2,3,4,5,101,113,201,202,301,400,404,510,600,716,717,1610,1800,1807,2002)

# Run only a subset of achilles

achilles(connectionDetails, 
  cdmDatabaseSchema = "cdm5_inst", 
  resultsDatabaseSchema="results",
  vocabDatabaseSchema = "vocab",
  numThreads = 1,
  sourceName = "My Source Name", 
  cdmVersion = "5.3.0",
  runHeel = FALSE,
  runCostAnalysis = FALSE
  analysisIds = ACHILLES_LEVEL_01)
  
  
  
achillesHeel(connectionDetails, 
  cdmDatabaseSchema = "cdm5_inst", 
  resultsDatabaseSchema="results",
  cdmVersion = "5.3.0")

**Comment by alondhe** [comment]
@vojtechhuser I think this needs more detail. I know we discussed a bit during our last call, but for transparency's sake:

1. Why do we need levels? 
2.  What are the levels?

**Comment by vojtechhuser** [comment]
Only level 1 is defined at the moment.
L1 defines a small subset of analyses that are used by Heel.

Heel user can only rung L1 of Achilles to arrive at heel results faster

**Comment by alondhe** [comment]
Right, but why? What's the problem this solves? And how do we define what goes in each level?

**Comment by fdefalco** [comment]
Heel has been superseded by DQD.

**Comment by vojtechhuser** [comment]
Here is why: Achilles characterizes a lot of things. A subset of analysis is less "sensitive" to share. I designed Minimum Information about Dataset concept. And created 3 levels. Level 1 only reveals count of patients and ration of male/female.  Having levels of sharing would make people share Achilles results more. Now it seems to be all or nothing. We need a spectrum and levels inbetween all or nothing. @fdefalco

**Comment by fdefalco** [comment]
@vojtechhuser Please take a look at https://github.com/OHDSI/Achilles/pull/544 , it introduces an analysis category in the specification.  Using this categorization people can run various subsets of analyses as they see fit.
