### ISSUE TITLE
Add github.io page

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#414]
Following the convention of other OHDSI Git repos, let's make a nice new Github.io page

**Comment by schuemie** [comment]
FYI: this website can be generated in one command using pkgdown, like [this](https://github.com/OHDSI/CohortMethod/blob/master/extras/PackageMaintenance.R#L40).

This does require you to create a [_pkgdown.yml](https://github.com/OHDSI/CohortMethod/blob/master/_pkgdown.yml) file. 

And add some things to .Rbuildignore
