### ISSUE TITLE
Verify Travis CI has the necessary platforms for testing

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#416]
For the 1.7.0 release, let's ensure we can test the functions against all db platforms (except pdw).

**Comment by schuemie** [comment]
Travis currently has access to the following platforms:

- SQL Server
- Oracle
- PostgreSQL

I'm not sure [this `try`](https://github.com/OHDSI/Achilles/blob/master/tests/testthat/test-achilles_parameterized.R#L32) is a good idea, as it might hide test fails on Travis.

**Comment by alondhe** [comment]
Thanks @schuemie. In terms of platforms, is there no way to gain access to others like Impala or BigQuery?

I'll adjust that test to make errors more transparent.

**Comment by schuemie** [comment]
If someone is kind enough to provide (and maintain) testing instances on those platforms then we could add them.

I think this is part of a bigger discussion about what platforms we support, and which ones we don't.

**Comment by fdefalco** [comment]
Travis use will be discontinued.
