### ISSUE TITLE
Only run certain reports

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#417]
Is there a way to only run for example the analysis in the dashboard, person, and observation_period?  I saw the analysis_ids parameter and the details but how do i know which are in which report?

Thanks.

**Comment by alondhe** [comment]
Hi @PRijnbeek -- the analyses can be found in this CSV: 

https://github.com/OHDSI/Achilles/blob/master/inst/csv/achilles/achilles_analysis_details.csv

**Comment by PRijnbeek** [comment]
Yes I saw that if i need only want to create the .json file for the dashboard I have to go to the dashboard in AchillesWeb and then look up the analysis_ids or can I see which are in which report? Where does that happen in the code?

**Comment by PRijnbeek** [comment]
I could use the logic in the analysis_ids probably right?

**Comment by alondhe** [comment]
Hmm, this isn't a pathway we've programmed for really. But in inspecting the export code, you'd need to run the SQLs in [the inst/sql/sql server/export/person ](https://github.com/OHDSI/Achilles/tree/master/inst/sql/sql_server/export/person) and [inst/sql/sql server/export/observationperiod](https://github.com/OHDSI/Achilles/tree/master/inst/sql/sql_server/export/observationperiod) paths in order for the exportToJson function (with only DASHBOARD selected) to work.

**Comment by PRijnbeek** [comment]
okay thanks that works for me.
