### ISSUE TITLE
Box and Whisker plot labelled incorrectly

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Achilles#419]
### Expected behavior
Box and whisker plot on observation period dashboard shows .5 to represent 6 months

### Actual behavior
Plot is labeled as 500m

![image](https://user-images.githubusercontent.com/12911960/60122883-30021280-9754-11e9-987d-e105c1020368.png)

**Comment by alondhe** [comment]
As we won't be making any changes to AchillesWeb, closing this issue. Atlas Data Sources appears to render this correctly
