### ISSUE TITLE
Provide support for new features in CDMv5

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Achilles#42]
The current version of Achilles does not break when using CDMv5, but it also doesn't use any of the new features. 

Most importantly, it is not outputting statistics on the Measurement table.Other immediately useful information would be the metadata that was introduced in V5. Currently less important (because nobody I know has the information) is reports on devices, specimen, notes, and information on different types of observation periods.

**Comment by ericaVoss** [comment]
Yeah, just needed a SPECIMEN summary and it does not exist.

**Comment by alondhe** [comment]
Closing this, but we will provide reports on all clinical event types in 2.0.
