### ISSUE TITLE
Drug Rollups in export to JSON: NA ATCs

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#420]
### Expected behavior
No duplicate records in the drug exposure rolllups

### Actual behavior
Seeing dupes, with NA ATC codes.

### Steps to reproduce behavior
Export the Drug report to JSON, view in AchillesWeb

Reported by @clairblacketer

**Comment by alondhe** [comment]
@t-abdul-basser says this may occur in Atlas Data Sources, is checking into this

**Comment by alondhe** [comment]
![atc dupes achilles table](https://user-images.githubusercontent.com/8037742/60993496-6f5b6200-a303-11e9-8d91-9325f18d70db.png)

![atc dupes atc treemap](https://user-images.githubusercontent.com/8037742/60993506-72565280-a303-11e9-98fb-0424b1d71ae7.png)

**Comment by alondhe** [comment]
Achilles is working, but the question is do we make this ATC rollup logic more sensitive so that we don't end up with NA ATC values?

**Comment by fdefalco** [comment]
Classification is less important in Achilles as we are primarily performing characterization at the concept level.  As long as existing vocabulary is loaded then the classifications as provided by the vocabulary are sufficient.
