### ISSUE TITLE
cdm_v6 branch not picking up correct sql scripts

### ISSUE THREAD

**Issue by robchallen** [OHDSI/Achilles#421]
### Expected behavior

On a v6 cdm achilles should use sql scripts from the analyses_v6 directory

### Actual behavior

Achilles performs bulk of analysis using scripts from correct directory but throws an uninformative error writing out results to database table.
Root cause is Achilles uses correct directory for finding SQL files for most but not all operations

Not for e.g.
* raw_cost_template.sql (line 315)
* also line 361 and lines 381, 
* critically on line 1237 it doesn;t use it for merge_achilles_tables.sql so all results are dropped

### Steps to reproduce behavior

run achilles installed from github branch cdm_v6 from R on a v6 cdm

I worked around this issue by creating a symbolic link from "analyses_v6" to "analyses" in the 

~/R/x86_64-pc-linux-gnu-library/3.4/Achilles/sql/sql_server

directory

**Comment by alondhe** [comment]
Thanks @robchallen . Currently that branch is inactive, as I don't have a CDMv6 to test against. We are planning on full CDMv6 support for Achilles v1.8.0, due out at the end of August: https://github.com/OHDSI/Achilles/milestone/13.

**Comment by fdefalco** [comment]
Achilles only supports CDM v5.x at this time.  CDM 6 will not be supported as the specification has gone unutilized in the community.  Expect next version support with updated CDM v7 specification.
