### ISSUE TITLE
cdm_v6 sql error in analysis 500

### ISSUE THREAD

**Issue by robchallen** [OHDSI/Achilles#422]
### Expected behavior

Achilles analysis runs on cdm_v6

### Actual behavior

SQL error generated due to incorrect column name in 500.sql

left join @cdmDatabaseSchema.concept CN on C.condition_type_concept_id = CN.concept_id
  and CN.concept_class = 'Death Type'

shoudl be 

left join @cdmDatabaseSchema.concept CN on C.condition_type_concept_id = CN.concept_id
  and CN.concept_class_id = 'Death Type'

### Steps to reproduce behavior

achilles(connectionDetails, 
         cdmDatabaseSchema = "omop.dbo", 
         resultsDatabaseSchema="omopResults.dbo",
         vocabDatabaseSchema = "omop.dbo",
         numThreads = 1,
         sourceName = "My Source Name", 
         cdmVersion = "6.0",
         runHeel = TRUE,
         runCostAnalysis = FALSE,
         # sqlOnly = TRUE,
         outputFolder = "~/Dropbox/tmp/achilles/sql"
         analysisIds = c(500)
         )

**Comment by alondhe** [comment]
As commented in the other issue, CDMv6 support is due out in Achilles v1.8.0: https://github.com/OHDSI/Achilles/milestone/13

**Comment by robchallen** [comment]
Fair enough.

For completeness I found the following other errors in this branch:

Analysis 501 -- ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_class'.
An error report has been created at  /home/robchallen/Dropbox/tmp/achilles/errorReport.txt

Analysis 504 -- ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: The multi-part identifier "p1.gender_concept_id" could not be bound.
An error report has been created at  /home/robchallen/Dropbox/tmp/achilles/errorReport.txt

Analysis 505 -- ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'concept_class'.
An error report has been created at  /home/robchallen/Dropbox/tmp/achilles/errorReport.txt

Analysis 506 -- ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Column 'omop.dbo.person.person_id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
An error report has been created at  /home/robchallen/Dropbox/tmp/achilles/errorReport.txt

**Comment by rpeys** [comment]
@alondhe I see that v6 updates are planned to be completed this november, but I am wondering when they are planned to get underway? I want to know when others will be actively committing code & responding to pull requests, issues, etc. I'm happy to help contribute but want to schedule myself to overlap with others so that pull requests & issues don't just sit... thanks!

**Comment by alondhe** [comment]
Hi @rpeys -- I think after the Symposium is when we'll start developing the v6 support. None of the analytic tools (Atlas, CohortMethod, etc) will be on v6 until end of year. Thanks for helping push this along!

**Comment by fdefalco** [comment]
Achilles only supports CDM v5.x at this time. CDM 6 will not be supported as the specification has gone unutilized in the community. Expect next version support with updated CDM v7 specification.
