### ISSUE TITLE
Achilles cdm_v6 error

### ISSUE THREAD

**Issue by tarunshah** [OHDSI/Achilles#424]
I have installed Achilles using RStudio with devtools as :-

`devtools::install_github("OHDSI/Achilles", ref = "cdm_v6")`
 
after this I'm getting error while running Achilles() after installing from branch Achilles cdm_v6 like:-

```
Warning: 'SqlRender::translateSql' is deprecated.
Use 'translate' instead.
See help("Deprecated")
Warning: file("") only supports open = "w+" and open = "w+b": using the former
Error in readChar(pathToSql, file.info(pathToSql)$size) : 
  invalid 'nchars' argument
```
though the analysis runs with 2201 queries but giving the above error in the end. 

And when running achillesHeel() getting error:-

```
Error in dir.exists(outputFolder) : 
  argument "outputFolder" is missing, with no default
```

**Comment by alondhe** [comment]
@tarunshah that branch is not active right now. I think we will pick back up on that in Q4.
