### ISSUE TITLE
Analysis 424, 624, 724, 1824 failed

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#425]
### Expected behavior
Analysis 424, 624, 724, 1824 are executed 

### Actual behavior
Analysis 424, 624, 724, 1824 are failed on Redshift Database with real data. We are using the latest version from master branch as we need changes related to vocabularies.

The problem is that Redshift fails on the listed sql queries with following message:
```
Analysis 624 -- ERROR Error: Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: Out of Memory
Details:
-----------------------------------------------
  error:  Out of Memory
  code:      1004
  context:   node: 2
  query:     7326779
  location:  fdisk_api.cpp:632
  process:   query2_95_7326779 [pid=2482]
  -----------------------------------------------;
```

Is there any way to optimize the queries in that SQL scripts?

### Steps to reproduce behavior
Run Achilles on Redshift data with 30M+ persons.

**Comment by alondhe** [comment]
Hi @konstjar ,

Does it fail on the temp table creation (#unique_pairs_424) or the insert into the achilles_results?

Tagging @AnthonyMolinaro

**Comment by alondhe** [comment]
We've been running this on Redshift with 140 million patients without issue. @konstjar what cluster type are you using?

**Comment by konstjar** [comment]
@alondhe It looks it fails on first parts of analysis to create temp table. I'm checking the size of cluster as I have limited access to it.

**Comment by konstjar** [comment]
> Hi @konstjar ,
> 
> Does it fail on the temp table creation (#unique_pairs_424) or the insert into the achilles_results?
> 
> Tagging @AnthonyMolinaro

The temp table #unique_pairs_424 (the same for 624, 724, 1824) is not created and finally Achilles fails to load data into achilles_results table as #unique_pairs_424 does not exists.

**Comment by konstjar** [comment]
Here is the full log of execution
[Achilles-Log.txt](https://github.com/OHDSI/Achilles/files/3625725/Achilles-Log.txt)

**Comment by t-abdul-basser** [comment]
Are you still seeing this issue after resizing/increasing resources?

**Comment by konstjar** [comment]
@t-abdul-basser Unfortunately, it still happens sometimes in random order.
Based on this there are following questions:
- First: Right now Achilles fails fully if one analysis was not executed. May be it's reasonable to pass this analysis in such case and let others continue and do not fail on final data merging?
- Second: It would be great to have an option to restart Achilles from last failed analysis. I know it might be big development, but I had few requests already.

**Comment by alondhe** [comment]
@konstjar we'll start to review these queries to optimize. 

Regarding the second idea, I'd like to brainstorm this a bit more. To allow restarting Achilles from last failed analysis, we may need to switch from temp tables to staging tables completely, so that all progress is available after the connection status changes.
