### ISSUE TITLE
Password using special char @

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/Achilles#427]
I have a DB with a password that uses the char @. For example, if the next line has web@pi as password:

-e ACHILLES_DB_URI=postgresql://webapi:web@pi@localhost:5432/ohdsi \

I could confuse Achilles. In this case, how do I specify the password? I tried 'web@pi' and "web@pi" without success. Or, should I stop using @ for passwords?

Thx

**Comment by alondhe** [comment]
Hmm, maybe try using percent (URL) encoding for the @ symbol: %40

**Comment by jcabrerazuniga** [comment]
Tried and not working.... This could also make the use of the special char % forbidden for passwords.

**Comment by jcabrerazuniga** [comment]
yes

**Comment by alondhe** [comment]
Can you post an issue in the DatabaseConnector git? It's not an Achilles issue, and putting it there will be better in terms of fixing the issue.

**Comment by jcabrerazuniga** [comment]
Do you have the link to the repo? first time I hear about it! Thx

**Comment by alondhe** [comment]
https://github.com/OHDSI/DatabaseConnector
