### ISSUE TITLE
Different result on Analyses query 108

### ISSUE THREAD

**Issue by tarunshah** [OHDSI/Achilles#428]
### Expected behavior
On running analyses query 108 in achilles->sql->sql_server->analyses I should be getting same result every time I ran the query

### Actual behavior
On running analyses query 108 in achilles->sql->sql_server->analyses I should be getting different result every time I ran the query

### Steps to reproduce behavior

```
select
    floor(DATEDIFF(dd, op1.observation_period_start_date, op1.observation_period_end_date)/30) as stratum_1,
    COUNT_BIG(distinct p1.person_id) as count_value
  from person p1
    inner join
    (select person_id,
      OBSERVATION_PERIOD_START_DATE,
      OBSERVATION_PERIOD_END_DATE,
      ROW_NUMBER() over (PARTITION by person_id order by observation_period_start_date asc) as rn1
       from observation_period
    ) op1
    on p1.PERSON_ID = op1.PERSON_ID
    where op1.rn1 = 1
  group by floor(DATEDIFF(dd, op1.observation_period_start_date, op1.observation_period_end_date)/30)
  order by floor(DATEDIFF(dd, op1.observation_period_start_date, op1.observation_period_end_date)/30)
```

I ran this query to understand the cumulative observation in observation_period dashboard.

**Comment by alondhe** [comment]
@tarunshah -- so you run Achilles only with analysis 108 and each iteration you have different results, is that correct?

**Comment by alondhe** [comment]
@tarunshah -- can you post an example of the different results and how you got them?
