### ISSUE TITLE
Mixed case in SQL Tests

### ISSUE THREAD

**Issue by DaveBarman** [OHDSI/Achilles#429]
### Expected behavior
Expectation for SQL to be in syntax and context of the CDM following the expected conventions for names
### Actual behavior
SQL for tests appear to have mixed case for field names. This causes errors where case sensitivity is implemented in the RDMBS

EX: 
select 3 as analysis_id,  CAST(year_of_birth AS VARCHAR(255)) as stratum_1, 
cast(null as varchar(255)) as stratum_2, cast(null as varchar(255)) as stratum_3, cast(null as varchar(255)) as stratum_4, cast(null as varchar(255)) as stratum_5,
COUNT_BIG(distinct person_id) as count_value
into @scratchDatabaseSchema@schemaDelim@tempAchillesPrefix_3
from @cdmDatabaseSchema.person
group by YEAR_OF_BIRTH;

### Steps to reproduce behavior
Install and execute Achilles against a CDM in an RDBMS with collation set to be case sensitive

**Comment by alondhe** [comment]
What case is your platform expecting?

**Comment by DaveBarman** [comment]
lower case

**Comment by DaveBarman** [comment]
Issue is with database collation setting affecting queries on columns and tables. This is not an issue with the package.
