### ISSUE TITLE
Achilles execution fails on scratch table Merge in SQL Server

### ISSUE THREAD

**Issue by DaveBarman** [OHDSI/Achilles#430]
### Expected behavior
Merge scratch table script completes successfully by utilizing default named temp tables 
### Actual behavior
Temp tables are being assigned none-default names and failure message is 
Error executing SQL: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name '#s_tmpach_0'.

When identifying the actual temp table names they appear as:
#@schemadelim@tempachillesprefix_2201_______________________________________________________________________________0000000018A3

and so-forth.

### Steps to reproduce behavior

achilles(connectionDetails, 
         cdmDatabaseSchema = "<DATABASE>.OMOPCDM", 
         vocabDatabaseSchema = "<DATABASE>.VOCAB",
         resultsDatabaseSchema = "<DATABASE>.RESULTS",
         scratchDatabaseSchema = "<DATABASE>.RESULTS",
         sourceName = "JacksonHinds",
         outputFolder = "C:\\Users\\dbarman\\Documents\\results",
         cdmVersion = "5.3",
         numThreads = 1,
         tempAchillesPrefix = "tmpach",
         sqlOnly = FALSE,
         runHeel = FALSE,
         runCostAnalysis = FALSE)

When issuing the sqlOnly execution and reviewing the SQL, it does not populate the supplied parameters in the output.

**Comment by DaveBarman** [comment]
Issue identified with how the scripts were adjusted to compensate for DB collations, unrelated to Achilles.

**Comment by t-abdul-basser** [comment]
Thanks for following up with a helpful note on this issue.
