### ISSUE TITLE
Achilles Package Execution Failed on Error

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Achilles#432]
### Throws this error and stops the execution
```
Executing multiple queries. This could take a while
  |================================================================================================================================================================================================| 100%
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 65 did not have 6 elements
```

### Steps to reproduce behavior
1) Set up ConnectionDetails
2) Run the package

The R log does not have anymore details on this error so I do not know where to go from here.  Can someone explain this error and what the issue is?  What log should I be looking at for this to troubleshoot?  Only the ACHILLES_analysis table was created.  I believe there are other tables that should be created too.  Plus hundreds of scratch tables are still there.

**Comment by alondhe** [comment]
Can you provide your connection details (with credentials removed) and your script that called achilles?

**Comment by anonymous34** [comment]
Yes here they are.  
library(Achilles)
connectionDetails <- createConnectionDetails(
  dbms="sql server", 
  server="computer name", 
  user="username", 
  password='password', 
  port="1433")

achilles(connectionDetails, 
  cdmDatabaseSchema = "databasename.dbo", 
  resultsDatabaseSchema = "databasename.results",
  scratchDatabaseSchema = "databasename.scratch",
  vocabDatabaseSchema = "databasename.dbo",
  numThreads = 10,
  sourceName = "CDM", 
  cdmVersion = "5.3.1",
  runHeel = TRUE,
  runCostAnalysis = TRUE)

**Comment by alondhe** [comment]
Not seeing the issue. Can you re-run, but limit it to 1 or 2 threads? 10 threads is really only ideal with Redshift, PDW, or other MPP systems.

**Comment by ericaVoss** [comment]
@alondhe I'm guessing we don't know the resolution to this?  I'm running into the same issue with @r-degroot

**Comment by r-degroot** [comment]
@ericaVoss "PostgreSQL 12.1 (Debian 12.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit" is this what you mean by environment set up? 

`install.packages("devtools")
installed.packages("usethis")
library(devtools)
library(usethis)

if (!require("devtools")) install.packages("devtools")

# To install the master branch
devtools::install_github("OHDSI/Achilles")

install.packages("DatabaseConnector")

# To install latest release (if master branch contains a bug for you)
# devtools::install_github("OHDSI/Achilles@*release")  

# To avoid Java 32 vs 64 issues 
# devtools::install_github("OHDSI/Achilles", args="--no-multiarch")  

library(Achilles)
connectionDetails <- createConnectionDetails(
  dbms="postgresql", 
  server=". . ./. . .", 
  user=". . .", 
  password='. . .', 
  port=". . .")

#Single-threaded mode
achilles(connectionDetails, 
         cdmDatabaseSchema = "cdm5_inst", 
         resultsDatabaseSchema="results",
         vocabDatabaseSchema = "cdm5_inst",
         numThreads = 1,
         sourceName = "COVID 19 data warehouse", 
         cdmVersion = "5.3.1",
         runHeel = TRUE,
         runCostAnalysis = FALSE) #Set to TRUE or FALSE

#Multi-treaded mode
achilles(connectionDetails, 
         cdmDatabaseSchema = "cdm5_inst", 
         resultsDatabaseSchema = "results",
         scratchDatabaseSchema = "scratch",
         vocabDatabaseSchema = "cdm5_inst",
         numThreads = 10,
         sourceName = "COVID 19 data warehouse", 
         cdmVersion = "5.3.1",
         runHeel = TRUE,
         runCostAnalysis = FALSE) #Set to TRUE or FALSE

#To use AchillesWeb to explore the Achilles statistics
exportToJson(connectionDetails, 
             cdmDatabaseSchema = "cdm5_inst", 
             resultsDatabaseSchema = "results", 
             outputPath = "C:/Users/rdgro/Documents/R/AchillesExport", 
             compressIntoOneFile = TRUE) # creates gzipped file of all JSON files

#To optimize Atlas cache during achilles execution, use the following command:
achilles(connectionDetails, 
         cdmDatabaseSchema = "cdm5_inst", 
         resultsDatabaseSchema="results",
         vocabDatabaseSchema = "vocab",
         numThreads = 1,
         sourceName = "CVOID 19 data warehouse", 
         cdmVersion = "5.3.1",
         runHeel = TRUE,
         optimizeAtlasCache = TRUE) # creates additional table to store results for Atlas cache`

**Comment by alondhe** [comment]
Hi @r-degroot,

Are you running all of those commands? That isn't necessary. Please just run the below commands. With Postgres, multi-threading isn't a good idea, so use just single-threaded. 

```
library(Achilles)
connectionDetails <- createConnectionDetails(
dbms="postgresql",
server=". . ./. . .",
user=". . .",
password='. . .',
port=". . .")

#Single-threaded mode
achilles(connectionDetails,
cdmDatabaseSchema = "cdm5_inst",
resultsDatabaseSchema="results",
vocabDatabaseSchema = "cdm5_inst",
numThreads = 1,
sourceName = "COVID 19 data warehouse",
cdmVersion = "5.3.1",
runHeel = TRUE,
runCostAnalysis = FALSE,
optimizeAtlasCache = TRUE)
```

Thanks,
Ajit

**Comment by r-degroot** [comment]
Hi @alondhe I got this error below. The error report also mentions missing results.achilles_results_dist. I tried adding the table myself and running Achilles again, but the table is gone and I received the same error.

g scratch Achilles tables [ERROR] (Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: relation "s_tmpach_dist_1815" does not exist
  Position: 42226
An error report has been created at  C:/Users/rdgro/Documents/errorReportSql.txt
)
Done. Achilles results can now be found in schema results
Connecting using PostgreSQL driver
  |===================================================================================================                                                            |  62%Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: relation "results.achilles_results_dist" does not exist
An error report has been created at  C:/Users/rdgro/Documents/errorReportSql.txt

**Comment by alondhe** [comment]
Looks like analysis 1815 is failing. Therefore the achilles_results_dist table cannot be created as it needs 1815.

Analysis 1815 is this one: https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/1815.sql.

Can you verify you have a measurement table?

**Comment by r-degroot** [comment]
Hi @alondhe 

The measurement table seems to be compliant with v5.3.1 of the CDM. I used this code to create the CDM: https://github.com/OHDSI/CommonDataModel/blob/v5.3.1_fixes/PostgreSQL/OMOP%20CDM%20postgresql%20v5_3_1%20ddl.sql

I also tried to run analysis 1815 in Postgres. I had to change count_big to count and change stdev to stddev in order to run it succesfully.

**Comment by ericaVoss** [comment]
@alondhe 

The SQL runs fine and I think we are on CDM V5.3.1.  Any other recommendations?

Otherwise I think we will roll-back to V16.1 and try that.

**Comment by fdefalco** [comment]
I was informed this has been resolved.
