### ISSUE TITLE
Analysis 1425 Break on Markscan Dataset

### ISSUE THREAD

**Issue by djb2188** [OHDSI/Achilles#433]
### Expected behavior
Payer_play_period, if populated,  it should aggregated as specified in analysis 1425
### Actual behavior
DDL from .net ETL Builder seems to vary from expected DDL and we experience a break.
### Steps to reproduce behavior
- run achilles available in master for analysis(1425) on .net builder for marketscan
- review sql for analysis 1425. It calls for concept id. See below ddl for MarksetScan DDL

### DDL
CREATE TABLE [dbo].[PAYER_PLAN_PERIOD](
	[PAYER_PLAN_PERIOD_ID] [bigint] NOT NULL,
	[PERSON_ID] [bigint] NOT NULL,
	[PAYER_PLAN_PERIOD_START_DATE] [date] NOT NULL,
	[PAYER_PLAN_PERIOD_END_DATE] [date] NOT NULL,
	[PAYER_SOURCE_VALUE] [varchar](50) NULL,
	[PLAN_SOURCE_VALUE] [varchar](50) NULL,
	[FAMILY_SOURCE_VALUE] [varchar](50) NULL,
 CONSTRAINT [xpk_payer_plan_period] PRIMARY KEY NONCLUSTERED 
(
	[PAYER_PLAN_PERIOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

### Notes
See perfortune branch in my fork if you would like. I have cut down on run duration by adding in some additional temp tables and indexes. I also added in columnstores.
[log_achilles.txt](https://github.com/OHDSI/Achilles/files/3785720/log_achilles.txt)

**Comment by alondhe** [comment]
Hi @djb2188 can you raise this in the ETLCdmBuilder repo? It needs to be updated to use the correct DDL for the Marketscan project. Tagging @clairblacketer

**Comment by djb2188** [comment]
@alondhe  I can. I emailed Anton. Does he monitor? Can I turn off this analysis (1425) in interim ? Thanks for responding so quickly. I am attaching the log in a moment.

**Comment by alondhe** [comment]
Sure, you can use this code and then pass it in for the analysisIds param:

```
df <- Achilles::getAnalysisDetails()
analysisIds <- df$ANALYSIS_ID[df$ANALYSIS_ID != 1425]
```

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. I was about to suggest this!

@djb2188 The above code runs all analyses exlcuding 1425. You would run as something like the followng
```
df <- Achilles::getAnalysisDetails()
analysisIds <- df$ANALYSIS_ID[df$ANALYSIS_ID != 1425]
achilles(...,analysisIds=analysisIds)
```

**Comment by djb2188** [comment]
@alondhe FYI this is sitting in the current live log.
2019-10-29 17:28:04	[Thread 2]	INFO	Achilles	fun	[Main Analysis] [START] 207 (Number of visit records with invalid person_id)
**2019-10-29 17:29:31	[Thread 8]	FATAL			Error in unserialize(node$con) : error reading from connection Calls: local ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize** 
2019-10-29 17:31:47	[Thread 2]	INFO	Achilles	fun	[Main Analysis] [COMPLETE] 207 (3.721856 mins)

**Comment by djb2188** [comment]
Here is the code @alondhe  @t-abdul-basser 
Seems to run until you look at the logs.
See attached files
[errorReport.txt](https://github.com/OHDSI/Achilles/files/3786354/errorReport.txt)
[log_achilles.txt](https://github.com/OHDSI/Achilles/files/3786357/log_achilles.txt)
[log_dropScratchTables.txt](https://github.com/OHDSI/Achilles/files/3786358/log_dropScratchTables.txt)

**Comment by djb2188** [comment]
Thank you all. I created an empty 5.3 Payer Period table.

@alondhe I am seeing this in the achilles log.

Error in unserialize(node$con) : error reading from connection Calls: local ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize

**Comment by t-abdul-basser** [comment]
> @alondhe FYI this is sitting in the current live log.
> 2019-10-29 17:28:04 [Thread 2] INFO Achilles fun [Main Analysis] [START] 207 (Number of visit records with invalid person_id)
> **2019-10-29 17:29:31 [Thread 8] FATAL Error in unserialize(node$con) : error reading from connection Calls: local ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize**
> 2019-10-29 17:31:47 [Thread 2] INFO Achilles fun [Main Analysis] [COMPLETE] 207 (3.721856 mins)

@djb2188 This is an [error that raised when memory limits are exceeded in parallelizing scenarios](http://gforge.se/2015/02/how-to-go-parallel-in-r-basics-tips/). Try a smaller number of thread e.g.  
```
achilles(connectionDetails,
         cdmDatabaseSchema = "cdm_mdcd.dbo",
         resultsDatabaseSchema = "cdm_mdcd.results",
         vocabDatabaseSchema = " cdm_mdcd.dbo",
         numThreads =2, #keep this low for now
         sourceName = "CDM_mdcd",
         analysisIds <- analysisIds ,
         cdmVersion = "5",
         runHeel = TRUE,
         runCostAnalysis = FALSE)
```

**Comment by djb2188** [comment]
@alondhe we have run all analyses successfully. As @t-abdul-basser  is aware we are running into an issue during the final the final merge. I am please see the logs attached for everyone's review. I am not excluding anything.

**Comment by alondhe** [comment]
Thanks to @hongwonjun , we now have conditional logic for analysis 1425. If you're using a cdm version < 5.3, we do not run this analysis any more. 

Can you retry with the new commit and maybe 1 or 2 threads?
