### ISSUE TITLE
Which Analyses are tied directly to Atlas Domain TreeMaps?

### ISSUE THREAD

**Issue by djb2188** [OHDSI/Achilles#438]
- Which Analyses are tied directly to the  Atlas Domain specific  Tree Maps? 

- I am working off of Achilles\master, completing a successful Achilles run on Truven Dataset but our Domain Specific Tree maps are erroring out.

Thanks David

@cukarthik  @t-abdul-basser @alondhe

**Comment by t-abdul-basser** [comment]
We found that the `concept_hierarchy` table was missing.
