### ISSUE TITLE
The condition report is not classifiying the condition by families.

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [OHDSI/Achilles#439]
### Expected behavior  Actual behavior
The condition report is not classifiying the condition by families. 
Colums SOC and HLT show NA for all the conditions 

### Steps to reproduce behavior
On the example in the web demo I see the same for the data base:  CMS_SYNPUF_synthetic_data

Can it be that im using ICD10(WHO) ??

**Comment by alondhe** [comment]
@javier-gracia-tabuenca-tuni is this occurring in AchillesWeb or Atlas Data Sources or both?

**Comment by javier-gracia-tabuenca-tuni** [comment]
thansk @alondhe 
On AchillesWeb demo happens with CDM_SYMPUF data. 
On Atlast happes to both data shources. 
For my data, happens on AchillesWeb, and in haven;t try yet on Atlast

**Comment by alondhe** [comment]
We think this is related to #420. If the vocab doesn't have higher level terms for the standard concept, you'll see NA values.

**Comment by javier-gracia-tabuenca-tuni** [comment]
hey @alondhe , 

I'm using ICD10 which has higher level terms. However, I'm not sure if Achilles uses an other jerarchy. What does the colums SOC and HLT stand for ??

![image](https://user-images.githubusercontent.com/54809193/70414131-d2dbee00-1a61-11ea-8d8e-6db0d2717860.png)

For the issue you refer, in my case the medicines clasification works well. Perhaps in #420 they forgot to include the ATC vocabulary to their data base ??

**Comment by fdefalco** [comment]
SOC and HLT are abbreviations for System Organ Class and High Level Term from the MedDRA hierarchy.  This issue occurs if the vocabulary tables have not been populated but is not an issue with the package itself.
