### ISSUE TITLE
Atlas Data Sources - Drug era treemap contains duplicates

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/Achilles#442]
### Expected behavior
No duplicate records in the drug exposure roll ups in Atlas Data Sources

### Actual behavior

Seeing dupes

### Steps to reproduce behavior

View in Atlas Data Sources

![Atlas-DS-dups](https://user-images.githubusercontent.com/8838320/70177637-c0039b00-16a8-11ea-8b67-3db910cb234c.PNG)

**Comment by fdefalco** [comment]
This issue is no longer occurring with updates to ATLAS since 2019.
