### ISSUE TITLE
Drugs that are mapped to vocabulary 82 (RxNorm Extension) concept ids are not showing up in our Achilles drug exposure Report

### ISSUE THREAD

**Issue by mpolupar** [OHDSI/Achilles#444]
The drugs that are mapped to vocabulary 82 (RxNorm Extension) concept ids are not showing up in our Achilles drug exposure Report.  We are using version 4 of OMOP .

**Comment by alondhe** [comment]
Hi @mpolupar -- are those drugs captured in the achilles_results table in stratum_1? Try seeing if they are in analysis 700 or 701.

I just want to confirm that those drugs are indeed being characterized, and that it's just the treemap export causing the issue.
