### ISSUE TITLE
Spark - NOT IN performance

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Achilles#447]
### Expected behavior
Queries using NOT IN <subquery> syntax complete in Databricks Spark.

### Actual behavior
Queries using NOT IN <subquery> syntax do not complete in Databricks Spark.

### Steps to reproduce behavior
Run Achilles against Databricks Spark.

In my branch, I've changed this to use left joins with a where clause. Might be good to use throughout.

**Comment by vojtechhuser** [comment]
is spark now a suported dbms?

**Comment by alondhe** [comment]
Nope, I just have a branch of DatabaseConnector and SqlRender for it at this time. I expect to propose them for merging later this year.

**Comment by alondhe** [comment]
Added to develop branch
