### ISSUE TITLE
Achilles with Impala

### ISSUE THREAD

**Issue by tarunshah** [OHDSI/Achilles#449]
I'm trying to get achilles result using impala as data source. I'm able to connect Impala with my R Studio (referred this [Link](https://github.com/tomwhite/Achilles/blob/impala/README-impala.md)).
I imported achilles with ref = 'impala' and when I tried to run achilles its giving me error after completing 100%

`Error in rJava::.jcall(metaData, "Ljava/sql/ResultSet;", "getSchemas",  : 
  java.sql.SQLException: [Simba][ImpalaJDBCDriver](500004) Error getting schema information: Metadata Initialization Error.`

![Achilles1](https://user-images.githubusercontent.com/18749045/73943728-48a3ef00-4917-11ea-8057-49ba485b6eb9.JPG)

**Comment by alondhe** [comment]
This may be more of a DatabaseConnector issue, not sure. Can you execute queries (using DatabaseConnector::executeSql or DatabaseConnector::querySql) without this error?

**Comment by tarunshah** [comment]
I tried executeSql 
first I got below result with the actual query provided by OHDSI

![Achilles2](https://user-images.githubusercontent.com/18749045/74005002-7f244d00-499d-11ea-9dab-c99c1ad9d6cc.JPG)


I tried it with count rather than count_big as it's not supported, then i got this

![Achilles3](https://user-images.githubusercontent.com/18749045/74005066-babf1700-499d-11ea-95b8-d5b8b300f490.JPG)


As, +, Count_big, Date etc are not supported in impala, can you tell me which branch or version should i import for smooth result from Achilles.
I had already configured Achilles, webApi + atlas with my SQL server and it works perfectly fine. But now we want to move to impala and after trying multiple versions (with impala fixes) and manually changing some queries, its still not feasible to get results from Achilles.

**Comment by alondhe** [comment]
@tarunshah right, these SQL patterns are to be translated to Impala SQL through the SqlRender library. In your first query, you didn't pass the SQL query through SqlRender. When you do, the query will be translated and the count_big will become a count().

Can you confirm your SqlRender library is up to date by removing it completely, terminating R, and then re-installing it?

`devtools::install_github("OHDSI/SqlRender")`

**Comment by alondhe** [comment]
Closing due to no recent response
