### ISSUE TITLE
no VISIT_DETAIL analysis in v6

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#450]
### Steps to reproduce behavior

see
https://github.com/OHDSI/Achilles/blob/cdm_v6/inst/csv/achilles/achilles_analysis_details.csv

**Comment by alondhe** [comment]
Hi @vojtechhuser -- restarting the V6 development in the cdm_v6_2020 branch. What types of analyses would you like to see for visit_detail?

**Comment by vojtechhuser** [comment]
well, at least the usual enchilada we do with every table and field

**Comment by fdefalco** [comment]
Achilles only supports CDM v5.x at this time. CDM 6 will not be supported as the specification has gone unutilized in the community. Expect next version support with updated CDM v7 specification.
