### ISSUE TITLE
replacement has 1 row, data has 0 - Error while multithread execution

### ISSUE THREAD

**Issue by Ak784** [OHDSI/Achilles#451]
Hello Everyone,

I was executing the below code to run Achilles on my data.  Our cdm version is 5.3.1 and we use postgresql db.

My R code is given below

`achilles(connectionDetails, cdmDatabaseSchema = "cdm", 
         resultsDatabaseSchema = "results",scratchDatabaseSchema = "scratch",
         vocabDatabaseSchema = "vocab",numThreads = 3,sourceName = "mysource",  
         cdmVersion = "5.3.1",runHeel = TRUE,runCostAnalysis = FALSE)`

When I ran the above code, my execution terminated with the below error message

> Error in $<-.data.frame(*tmp*, “runTime”, value = NA) :
> replacement has 1 row, data has 0

I do see some SO [related](https://stackoverflow.com/questions/56122494/r-error-in-data-frame-c-temp-replacement-has-items-need) to this error but as achilles is a package not sure, how to resolve this?

btw this happens only for multi-thread execution. For single thread execution, the code works fine and generates Analysis

Can you help us with this?

**Comment by alondhe** [comment]
@Ak784 -- can you provide more details:

- which DBMS
- do the logs provide any more info?

**Comment by Ak784** [comment]
This issue can be closed. It is due to multithread things for classic db like postgres
