### ISSUE TITLE
Gracefully handling failed analyses during merging

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Achilles#453]
### Expected behavior
If a few analyses fail, then report this on the command line and in the log, continue with the other analysis and output a valid Achilles result. 

### Actual behavior
If an analysis fails, Achilles report this and continues with executing the other analyses. So far so good. But during the execution of 'merging schratch tables', Achilles will exit with the error `ERROR:  relation "cdm_medicaid_results.tmpach_<failed_analysis_id>" does not exist ...`. No valid Achilles output is produced and the whole procedure has to be restarted. (or do a manual merge of scratch tables)

Would it be possible to skip the merging of failed analyses?

### Steps to reproduce behavior
Execute Achilles on a schema with an invalid OMOP CDM (e.g. missing the cost table).

**Comment by alondhe** [comment]
Thanks @MaximMoinat -- I fully agree. However, closing this as #446 covers this
