### ISSUE TITLE
DQ 39 Notification

### ISSUE THREAD

**Issue by denyskaduk** [OHDSI/Achilles#455]
### Expected behavior
In https://github.com/OHDSI/Achilles/blob/55ea9d66dfb8734047d99bf44e480ab2144734e0/inst/sql/sql_server/heels/parallel/results_derived/24.sql#L17 need to be sum of death counts.
 
### Actual behavior
At this time in script count rows with death counts

### Steps to reproduce behavior
Run Achilles, bug in
https://github.com/OHDSI/Achilles/blob/55ea9d66dfb8734047d99bf44e480ab2144734e0/inst/sql/sql_server/heels/parallel/results_derived/24.sql#L17

How to fix, change _count(count_value) as died_cnt_ to _sum(count_value) as died_cnt_

**Comment by vojtechhuser** [comment]
so you are saying the notification has a logical bug, right? can you submit PR directly?
