### ISSUE TITLE
Heel: Analysis-SUB-IDs

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#46]
When Heel uses previous data, it checks for various variations, but the variation is not assigned a subID.

It is hard to identify if the problem is events prior birth or events after death.
They all get the same analysisID 101

101  <0
101 >100

This is quite key quality indicator and if it has the same ID, it is not good for tracking quality.

See the problem here:

> filter(dsets,msgID==101)
Source: local data frame [9 x 2]

  msgID                                                                                                   msg
1   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=1,869)
2   101   Number of persons by age, with age at first observation period; should not have age < 0, (n=21,924)
3   101 Number of persons by age, with age at first observation period; should not have age > 100, (n=10,836)
4   101     Number of persons by age, with age at first observation period; should not have age > 100, (n=42)
5   101      Number of persons by age, with age at first observation period; should not have age > 100, (n=6)
6   101                                                                     Number of persons by age  (n=338)
7   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=8,549)
8   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=1,100)
9   101     Number of persons by age, with age at first observation period; should not have age > 100, (n=15)

**Comment by vojtechhuser** [comment]
Code has been modified last week to introduce analysis sub-ID.
I would like to propose a convention for producing error text. Current errors do not follow a single pattern. I plan to fix the most "firing" rules. The convention will be:

*PATTERN*
analysisID - quality rule subID | main text of the rule ; additional detail about the rule |attribute(eg, count=)|VALUE1|VALUE2

*EXAMPLE*
700 - 1| Number of persons with at least one drug exposure, by drug_concept_id;concepts in data are not in correct vocabulary|count=|1,284|RxNorm

**Comment by chrisknoll** [comment]
This is covered in #27

**Comment by vojtechhuser** [comment]
This has been now solved.
Analysis_ID with Rule_ID provide unique primary key
