### ISSUE TITLE
Reporting dashboard 

### ISSUE THREAD

**Issue by vagarwal77** [OHDSI/Achilles#460]
Hey, 

I am trying to build the dashboards on top of OMOP schemas and loved to see what is available @ 
http://www.ohdsi.org/web/achilles/#/OHDSI_Sample_Database/observationperiods

Can you please suggest in which OHDSI git repo i can get the reference code for these reporting dashboards which can get leveraged for my project? 

Thanks in advance!!

**Comment by alondhe** [comment]
The dashboards themselves are in the AchillesWeb repo: https://github.com/OHDSI/AchillesWeb. The data extraction / aggregation is done here in Achilles.
