### ISSUE TITLE
Error in Parallel Execution

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#462]
### Expected behavior
Merge is performed

### Actual behavior
5 Parallel queries. I get the following error: [ERROR] (Error in ParallelLogger::clusterApply(cluster = cluster, x = mergeSqls, : Error(s) when calling function 'fun', see earlier messages for details

There are no earlier messages for details so not sure what that is. I did see many tmp tables.

### Steps to reproduce behavior
Not sure, test on Postgresql possibly. run twice to check and reprodicible. Rerunning in single thread to see if this works.

**Comment by alondhe** [comment]
With Postgres, I wouldn't run it with more than 2 threads

**Comment by alondhe** [comment]
Also, @PRijnbeek -- did the log file indicate any of the individual analyses failed?

**Comment by PRijnbeek** [comment]
Why not run with more than 2 threads? I did not see a failed analysis.

**Comment by alondhe** [comment]
Performance wise, from my experience, it tends to lock up the postgres server. But it depends on the hardware being used. 

Could you send me the log file?

**Comment by PRijnbeek** [comment]
I do not have that log anymore sorry. I can try it again if it helps you tomorrow
