### ISSUE TITLE
Bug in results generation when running subset

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#463]
### Expected behavior
achilles(connectionDetails, 
         cdmDatabaseSchema = cdmDatabaseSchema, 
         resultsDatabaseSchema = "results",
         scratchDatabaseSchema = "scratch",
         vocabDatabaseSchema = cdmDatabaseSchema,
         numThreads = numThreads,
         sourceName = cdmSourceName, 
         cdmVersion = "5.3.1",
         runHeel = TRUE,
         runCostAnalysis = FALSE,
         analysisIds = c(500,501,502,504,505,506,509,510,511,512,513,514,515,525))

I expect to see only these ids

### Actual behavior
![image](https://user-images.githubusercontent.com/7252105/81572801-f8b84680-93a3-11ea-8503-4141e6df48a1.png)

### Steps to reproduce behavior
execute the call.

**Comment by alondhe** [comment]
Hi @PRijnbeek - those other records are the execution benchmarks. So analysis id 2000504 shows it took 0.585 seconds to run analysis 504, etc. The benchmarks are not used in any of the visual tools (AchillesWeb, Atlas).

**Comment by PRijnbeek** [comment]
Ahah :) that explains thanks.
