### ISSUE TITLE
Analysis 110: incorrect results in Oracle

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/Achilles#465]
### Expected behavior
The[ analysis 110](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/110.sql) uses `EOMONTH` substitution to define the single month period that should cover the entire month. The `EOMONTH` should return the true end of the month.

### Actual behavior
In Oracle, the `DATE` type can have the time component with the seconds precision.
The `EOMONTH` implemented as `last_day(date)` returns the last day of the month + whatever the original time component was. This creates multiple distinct periods for the given month.

### Steps to reproduce behavior

```
SELECT
    date_,
    last_day(date_) AS eomonth_current,
    TO_DATE(to_char(last_day(date_), 'YYYY-MM-DD')
        || ' 23:59:59', 'YYYY-MM-DD HH24:MI:SS') AS eomonth_correct
FROM (
    SELECT TO_DATE('2020-01-01 12:34:56', 'YYYY-MM-DD HH24:MI:SS') AS date_
    FROM dual
)
;
-- 01-JAN-2020 12.34.56
-- 31-JAN-2020 12.34.56
-- 31-JAN-2020 23.59.59
```

**Comment by alondhe** [comment]
Resolved in SqlRender develop branch
