### ISSUE TITLE
Temporary tables remain in Oracle

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/Achilles#466]
### Expected behavior
Achilles creates the result tables, cleans up all temporary tables.

### Actual behavior
Two temporary tables remain

```
%random%SERIAL_HR_44
%random%SERIAL_RD_37
```

### Steps to reproduce behavior
Run Achilles Heel with multiple threads against Oracle database. Very similar to https://github.com/OHDSI/Achilles/issues/400.

**Comment by Andreyyiv** [comment]
It seems the the dropAllScratchTables function [only cleans the parallel tables](https://github.com/OHDSI/Achilles/blob/ecb62550e4b17a43d7ef4db892608b57b7b953ef/R/Achilles.R#L996).

**Comment by alondhe** [comment]
@Andreyyiv -- ah, I see. As Oracle does not use true temp tables, the serial tables persist. I'll add some logic to drop the serial tables.
