### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by ornithos** [OHDSI/Achilles#467]
The README mentions explicitly that MySQL is supported, but from reading further around it appears that OHDSI does not support this platform.

* DatabaseConnector [dropped support for MySQL](https://github.com/OHDSI/DatabaseConnector/issues/30#issuecomment-392543237) back in 2018.
* SqlRender [does not support MySQL](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html).
* There's no corresponding DDL file in the [CommonDataModel](https://github.com/OHDSI/CommonDataModel/tree/master).
* A few comments in the forums state that OHDSI does not support it (e.g. [here](https://forums.ohdsi.org/t/unable-to-run-achilles-on-mysql-database/7396/3) or [here](https://forums.ohdsi.org/t/database-platform-support-revisited/8701/9)).

I'm asking as I installed MySQL in order to test Achilles locally, and ran into a number of issues with connection and translation of SQL. It may be that I'm doing something wrong, or it may simply be unsupported. (There's also some tests kicking around, e.g. [`test-achilles_parameterized.R`](https://github.com/OHDSI/Achilles/blob/ecb62550e4b17a43d7ef4db892608b57b7b953ef/tests/testthat/test-achilles_parameterized.R#L5) which appear to test Achilles on MySQL instances.) If it is somehow still supported -- great, I'll carry on going, but my suspicion from everything else is that it's not.

I appreciate all the work you guys do -- this is a fantastic resource.

**Comment by alondhe** [comment]
Hi @ornithos -- sorry about that, I think we neglected to remove MySQL from the documentation. You're right, it's not supported in DatabaseConnector or SqlRender, therefore it's not supported in Achilles either.

We'll remove this from the docs.

**Comment by ornithos** [comment]
No problem; thanks for the quick reply @alondhe!
