### ISSUE TITLE
Oracle issue with table name length

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#468]
Below is errorReport.txt from R for the code in master. @alondhe Could you please point me to the ACHILLES version that should work on Oracle?

DBMS:
oracle

Error:
java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long
ORA-06512: at line 7

SQL:
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE RESULTS.r9ygbh94s_tmpx_Procedure_cost_raw';
  EXECUTE IMMEDIATE 'DROP TABLE RESULTS.r9ygbh94s_tmpx_Procedure_cost_raw';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;

R version:
R version 3.6.3 (2020-02-29)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- rstudioapi (0.11)
- Achilles (1.6.7)
- DatabaseConnector (2.4.2)

**Comment by alondhe** [comment]
That looks like a new bug. In all non-cost analyses, the table names should conform with Oracle's table name restriction, but the cost analyses appears to have this issue.

Just to confirm, does it work if you set runCostAnalyses = FALSE? 

I'm going to rename these tables to have shorter names.

**Comment by konstjar** [comment]
@alondhe Thanks, it helped. But we got other issue on 1700 and 1701 analysis. I saw on other dialects there is a check for `cohort` table and it looks it does not work for Oracle.

**Comment by AnthonyMolinaro** [comment]
The shorter table names work as expected on Oracle.  The issue mention on June 2 is just a warning, not an error, and is expected behavior when the COHORT table doesn't exist.
