### ISSUE TITLE
#Error loading report #Atlas few reports not loaded in OHDSI CDM  V5 DB  #postgres

### ISSUE THREAD

**Issue by MeherDassThota** [OHDSI/Achilles#469]
### Expected behavior
in Atlas UI --> DataSource --> ODDSI  CDM V5 Database --> Drug era: Report loaded without error message 

### Actual behavior
i have setting up the Atlas and followed the Installation Guide which we used to install current OHDSI instance # DB used: Postgres #Error log "Ohdsi.Concept_hierarchy doesnot exist" --> Atlas UI --> DataSource --> ODDSI  CDM V5 Database --> Drug era Error loading report

**Comment by alondhe** [comment]
Hi @MeherDassThota -- we no longer create concept hierarchy in Achilles. It's a step you'll need to run manually when deploying your CDM. 

If you go to your results endpoint of WebAPI and fill in your results schema name and your database dialect, you can get the full results table deployment your CDM will need:

<WebAPI endpoint>/ddl/results?schema=**results**&dialect=**postgresql**

Of interest here is the concept_hierarchy table creation.
