### ISSUE TITLE
Heel: version of Heel used to generate the errors

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#47]
When Heel messages are generate, it would be  nice to have msgID=0, version of Heel used was 1.1

That way, one can know what to expect in the data

See problem here  - data set 6 used probably an earlier version of Heel.

> filter(dsets,msgID==101)
> Source: local data frame [9 x 2]

  msgID                                                                                                   msg
1   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=1,869)
2   101   Number of persons by age, with age at first observation period; should not have age < 0, (n=21,924)
3   101 Number of persons by age, with age at first observation period; should not have age > 100, (n=10,836)
4   101     Number of persons by age, with age at first observation period; should not have age > 100, (n=42)
5   101      Number of persons by age, with age at first observation period; should not have age > 100, (n=6)
6   101                                                                     Number of persons by age  (n=338)
7   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=8,549)
8   101    Number of persons by age, with age at first observation period; should not have age < 0, (n=1,100)
9   101     Number of persons by age, with age at first observation period; should not have age > 100, (n=15)

**Comment by alondhe** [comment]
We do store Achilles version in the achilles tables (analysis 0)
