### ISSUE TITLE
Analysis 109 is incorrect in Oracle if the time component is present

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/Achilles#473]
The `DATE` datatype in Oracle might contain the time component. The [analysis 109](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/109.sql) constructs the end of the year date as December 31 with the default time component of 00:00:00. The actual end of the year should be December 31 23:59:59.

**Comment by alondhe** [comment]
@Andreyyiv -- we will need DATETIMEFROMPARTS handled for all dialects in SqlRender before we can change it here.
