### ISSUE TITLE
Achilles docker build - CRAN mirror broken

### ISSUE THREAD

**Issue by lopsided** [OHDSI/Achilles#477]
The CRAN mirror at http://cran.cnr.berkeley.edu/src/contrib is now taken down. The page there says:

```
 The CRAN mirror at UC Berkeley's College of Natural Resources is no longer available to off campus users and has been removed from the CRAN mirror list. The load on our server was too much.

Berkeley folks can continue to access the mirror from on-campus networks or from within the VPN.

The rest of the R community: Sorry, but you'll have to please choose a different CRAN mirror. 
```

The Dockerfile just needs the link changing to one of from here: https://cran.r-project.org/mirrors.html. I'm happy to PR, any preferences?

**Comment by alondhe** [comment]
Thanks @lopsided! I think the default mirror (0-cloud) should suffice.

**Comment by t-abdul-basser** [comment]
Thanks @lopsided!
