### ISSUE TITLE
Achilles docker - ParallelLogger fails, XML R package not available for R version 3.4.4

### ISSUE THREAD

**Issue by lopsided** [OHDSI/Achilles#479]
Docker build fails with the following erro:

```
* installing *source* package ‘DatabaseConnector’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (DatabaseConnector)
Downloading GitHub repo OHDSI/ParallelLogger@master
jsonlite (1.6 -> 1.7.0) [CRAN]
Skipping 1 packages not available: XML
Installing 2 packages: XML, jsonlite
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: Failed to install 'ParallelLogger' from GitHub:
  (converted from warning) package ‘XML’ is not available (for R version 3.4.4)
ERROR: Service 'achilles' failed to build:..
```

Indeed the XML package shows it requires R version >=4.0 here: https://cloud.r-project.org/web/packages/XML/index.html

I'm a complete R-novice so not sure how to fix this. I guess trying a base container at R version 4.x might cause other problems but can't figure out how to pin an older version of the XML package. Thanks.

**Comment by satwinderbanipal** [comment]
Hello @lopsided, I'm also facing this issue while doing the build. Are you still facing this issue or were able to get any Breakthru?

**Comment by alondhe** [comment]
Looping in @t-abdul-basser as he knows more about Docker

**Comment by t-abdul-basser** [comment]
Thanks @alondhe. I was able to reproduce and will address.

**Comment by satwinderbanipal** [comment]
@alondhe @t-abdul-basser, Thank you so much for your time, I'll be waiting for your further updates on this page.

**Comment by t-abdul-basser** [comment]
[R4.0.1 is the supported version for the Hades packages](https://ohdsi.github.io/Hades/rSetup.html) (such as ParallelLogger) so we should update the DockerFile accordingly.
