### ISSUE TITLE
Heel (DQ): add % of missing data for each data domain (Dx, Proc, Meas, Obs)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#48]
A paper by Kahn http://repository.academyhealth.org/egems/vol3/iss1/7/
outlines very nice 20 item list.

For item 13 bullet 1 - Achilles should add
- **% of rows in drug exposure table mapped to concept 0** (not mapped) (perhaps even stratified by year)

and similarly for all other tables like Dx, Proc, Measurement and Observations

**Comment by vojtechhuser** [comment]
This can be done by query on analysis 401, rule 6 currently gives a warning but not "depth of the problem"


> select analysis_id,sum(count_value) from achilles_results where analysis_id in (401) group by analysis_id;

**Comment by vojtechhuser** [comment]
Iris beta part is analyzing this

**Comment by alondhe** [comment]
Added in recent commits
