### ISSUE TITLE
Data Density & Measurement

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#486]
### Expected behavior
Measurement data over time in the Data Density Plot

### Actual behavior
Data Density does not have measurement data

![image](https://user-images.githubusercontent.com/6305439/92272524-b4ebce80-eeb7-11ea-901c-1be85032d8ae.png)

I think ACHILLES predates that table.

### Steps to reproduce behavior
Go to the data density plot in ATLAS and see if there is a line for measurement.

**Comment by alondhe** [comment]
Hi @ericaVoss -- sorry for the delay. Thanks @hongwonjun for the fix, it's now in master. It should flow through into AchillesWeb. This won't affect Atlas, though, as Atlas doesn't use the JSON files.
