### ISSUE TITLE
Analysis 1803 fails, and results are not written to db.

### ISSUE THREAD

**Issue by KalleMedisapiens** [OHDSI/Achilles#494]
### Expected behavior
Analysis 1803 would finish and results be written in achilles_results.

### Actual behavior
Analysis is working for a while and then fails. See ErrorReportSql.txt for details.
1803.txt for execution logs.
finish.txt for final output of achilles.
achilles_results table is not created to the cdm.

Running the 1803 analysis via sql server management studio works and takes 17 minutes (If I remember correct).

[1803.txt](https://github.com/OHDSI/Achilles/files/5354297/1803.txt)
[ErrorReportSql.txt](https://github.com/OHDSI/Achilles/files/5354299/ErrorReportSql.txt)
[finish.txt](https://github.com/OHDSI/Achilles/files/5354300/finish.txt)

### Steps to reproduce behavior
Fill measurement table with 26580868 entries and run analysis 1803.

**Comment by alondhe** [comment]
This is analysis 1803 failing, not 1083 (there is no 1083). Can you verify you have a fully compliant CDM V5.3.1 version of the measurement table?

**Comment by KalleMedisapiens** [comment]
Hi,

I fixed the typo in my first comment.

Here is my create table sql. 

```
CREATE TABLE cdm.measurement
(
	measurement_id INTEGER NOT NULL ,
	person_id INTEGER NOT NULL ,
	measurement_concept_id INTEGER NOT NULL ,
	measurement_date DATE NOT NULL ,
	measurement_datetime DATETIME2 NULL ,
	measurement_time VARCHAR(10) NULL,
	measurement_type_concept_id INTEGER NOT NULL ,
	operator_concept_id INTEGER NULL ,
	value_as_number FLOAT NULL ,
	value_as_concept_id INTEGER NULL ,
	unit_concept_id INTEGER NULL ,
	range_low FLOAT NULL ,
	range_high FLOAT NULL ,
	provider_id INTEGER NULL ,
	visit_occurrence_id INTEGER NULL ,
	visit_detail_id INTEGER NULL ,
	measurement_source_value VARCHAR(50) NULL ,
	measurement_source_concept_id INTEGER NULL ,
	unit_source_value VARCHAR(50) NULL ,
	value_source_value VARCHAR(50) NULL
)
;

```

The table may not have had primary and foreign keys or indexes defined yet. I will hopefully get to test it soon.

Is there a timeout in Achilles analyses or in jdbc driver? There is unlikely to be a timeout in the database, as all other queries that take even longer than this one work.

Like I mentioned, this sql runs fine but takes a while in sql management studio.
https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/1803.sql

Kalle

**Comment by alondhe** [comment]
@KalleMedisapiens -- ah okay. So this is SQL Server? Are you running with more than 1 thread?

**Comment by KalleMedisapiens** [comment]
Only one thread.

```
achilles(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = "cdm",
  resultsDatabaseSchema = "cdm",
  vocabDatabaseSchema = "cdm",
  sourceName = "",
  cdmVersion = 5.3,
  numThreads = 1,
  runHeel = TRUE)
```

**Comment by KalleMedisapiens** [comment]
I found a workaround to this. With parameter sqlOnly=TRUE I can generate an sql file that does the same thing.
I had to add one GO statement to make it work, but I now get achilles results tables by running that sql.

**Comment by alondhe** [comment]
Where did you add the GO statement?

**Comment by KalleMedisapiens** [comment]
I did not notice the question mark previously. Yes, I'm working with sql server.

And the Go statement went here right after drop table #tempResults.

The problem was, that #tempResults is created in rule 28, and it persists when running rule 29 even when it is clearly dropped.

The way I understand this, adding GO executes the sql above separately from what comes after. This way the #tempResults table is actually dropped before the next select into attempts to create it.

I guess renaming the #tempResults in rule 29 section to something else would also fix the issue.

`
--rule28 DQ rule
--are all values (or more than threshold) in measurement table non numerical?
--(count of Measurment records with no numerical value is in analysis_id 1821)


select * into #tempResults
from 
(
  select 
    t2.count_value*100.0/all_count as statistic_value,
  CAST('Meas:NoNumValue:Percentage' AS VARCHAR(100)) as measure_id
  from 
  (
    select sum(count_value) as all_count from cdm.achilles_results where analysis_id = 1820
  ) t1 cross join (select count_value from cdm.achilles_results where analysis_id = 1821) t2
) t3
;

select * into #serial_rd_28
from
(
  select * from #serial_rd_27
  
  union all
  
  select  
    cast(null as int) as analysis_id,
    cast(null as varchar(255)) as stratum_1,
    cast(null as varchar(255)) as stratum_2,
    statistic_value,
    measure_id
  from #tempResults
) Q
;



SELECT *
into #serial_hr_28
FROM 
(
  select * from #serial_hr_27
  
  union all
  
  select  
    cast(null as int) as analysis_id,
    CAST('NOTIFICATION: percentage of non-numerical measurement records exceeds general population threshold ' AS VARCHAR(255)) as ACHILLES_HEEL_warning,
  	28 as rule_id,
  	cast(statistic_value as int) as record_count
	from #tempResults t
    --WHERE t.analysis_id IN (100730,100430) --umbrella version
  WHERE measure_id = 'Meas:NoNumValue:Percentage' --t.analysis_id IN (100000)
  --the intended threshold is 1 percent, this value is there to get pilot data from early adopters
  	AND t.statistic_value >= 80
) Q
;


--clean up temp tables for rule 28
truncate table #tempResults;
drop table #tempResults
GO
;

--end of rule 28

IF OBJECT_ID('tempdb..#serial_rd_27', 'U') IS NOT NULL DROP TABLE #serial_rd_27;

IF OBJECT_ID('tempdb..#serial_hr_27', 'U') IS NOT NULL DROP TABLE #serial_hr_27;

--rule29 DQ rule
--unusual diagnosis present, this rule is terminology dependend

with tempcnt as(
	select sum(count_value) as pt_cnt from cdm.achilles_results
	where analysis_id = 404 --dx by decile
	and stratum_1 = '195075' --meconium
	--and stratum_3 = '8507' --possible limit to males only
	and cast(stratum_4 as int) >= 5 --fifth decile or more
)
select pt_cnt as record_count 
into #tempResults
--set threshold here, currently it is zero
from tempcnt where pt_cnt > 0;


--using temp table because with clause that occurs prior insert into is causing problems 
--and with clause makes the code more readable

SELECT *
into #serial_hr_29
FROM 
(
  select * from #serial_hr_28
  
  union all
  
  select 
    cast(null as int) as analysis_id,
    CAST('WARNING:[PLAUSIBILITY] infant-age diagnosis (195075) at age 50+' AS VARCHAR(255)) as ACHILLES_HEEL_warning,
    29 as rule_id,
    cast(null as bigint) as record_count
  from #tempResults
) Q;

truncate table #tempResults;
drop table #tempResults;
--end of rule29
`

**Comment by fdefalco** [comment]
temp table handling has been revamped and this issue is no longer relevant
