### ISSUE TITLE
Install Version Issue

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/Achilles#495]
If I install it, it will be installed as version 1.6.7.
How can I install version 1.6.3?

**Comment by alondhe** [comment]
@SungJun9212 you can install 1.6.3 using this command:

`devtools::install_gitub("OHDSI/Achilles", ref = "v1.6.3")`

**Comment by SungJun9212** [comment]
thank you.
But I encountered the following error.

Failed to install 'Achilles' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpMuPLfO/file99a54952ede2/Achilles_1.6.3.tar.gz’ had non-zero exit status


This command works fine.
devtools::install_gitub("OHDSI/Achilles")
//(v=1.6.7)

**Comment by alondhe** [comment]
@SungJun9212 -- sorry, typo:

`devtools::install_github("OHDSI/Achilles", ref = "v1.6.3")`

**Comment by SungJun9212** [comment]
The typo was corrected and written, but even if it is written correctly, it is the same error...

**Comment by alondhe** [comment]
Try installing OhdsiRTools, which is now deprecated, but was a dependency for that version:

`devtools::install_github("OHDSI/OhdsiRTools")`

**Comment by SungJun9212** [comment]
As you told me, in order to install ohdsirtools, you need to install openxlsx.
openxlsx is also terminated with non-zero status.
Is there any other way?

**Comment by alondhe** [comment]
What's the full error when installing openxlsx?

**Comment by SungJun9212** [comment]
Is this error.

error: package ‘zip’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
ERROR: lazy loading failed for package ‘openxlsx’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/openxlsx’

**Comment by SungJun9212** [comment]
The reason for asking this question is
I'm running Achilles(v1.6.7), but I get the error below and I'm trying to try a different version of Achilles.
---------------------
(Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: relation “s_tmpach_8” does not exist
Position: 4411
An error report has been created at /home/ubuntu/errorReportSql.txt
)
Done. Achilles results can now be found in schema webapi
Connecting using PostgreSQL driver
| | 0%에러: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: relation “webapi_hansan.achilles_results” does not exist
An error report has been created at /home/ubuntu/errorReportSql.txt
-----------------------

And this is a errorReport.
-------------------------
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: relation “webapi_hansang.achilles_results” does not exist

SQL:
create index idx_ar_aid on webapi_hansang.achilles_results (analysis_id)

R version:
R version 3.6.3 (2020-02-29)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
stats
graphics
grDevices
utils
datasets
methods
base
Other attached packages:

Achilles (1.6.7)
DatabaseConnector (3.0.0)

**Comment by alondhe** [comment]
> Is this error.
> 
> error: package ‘zip’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
> ERROR: lazy loading failed for package ‘openxlsx’
> 
> * removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6/openxlsx’

This appears to be an issue with the zip package in your OS. Try install.packages("zip")

**Comment by alondhe** [comment]
> ## The reason for asking this question is
> I'm running Achilles(v1.6.7), but I get the error below and I'm trying to try a different version of Achilles.
> ## (Error: Error executing SQL:
> org.postgresql.util.PSQLException: ERROR: relation “s_tmpach_8” does not exist
> Position: 4411
> An error report has been created at /home/ubuntu/errorReportSql.txt
> )
> Done. Achilles results can now be found in schema webapi
> Connecting using PostgreSQL driver
> | | 0%에러: Error executing SQL:
> org.postgresql.util.PSQLException: ERROR: relation “webapi_hansan.achilles_results” does not exist
> An error report has been created at /home/ubuntu/errorReportSql.txt
> ## And this is a errorReport.
> DBMS:
> postgresql
> 
> Error:
> org.postgresql.util.PSQLException: ERROR: relation “webapi_hansang.achilles_results” does not exist
> 
> SQL:
> create index idx_ar_aid on webapi_hansang.achilles_results (analysis_id)
> 
> R version:
> R version 3.6.3 (2020-02-29)
> 
> Platform:
> x86_64-pc-linux-gnu
> 
> Attached base packages:
> stats
> graphics
> grDevices
> utils
> datasets
> methods
> base
> Other attached packages:
> 
> Achilles (1.6.7)
> DatabaseConnector (3.0.0)

This is due to an underlying staging table not completing correctly. Can you re-run with createIndices = FALSE to see what analysis failed?

**Comment by SungJun9212** [comment]
Achilles 1.6.3 has been installed, and it is still the same problem even when running 1.6.3.

When I put createIndices=false and run it, I get two warnings below just before it stops.

Warning: deprecatedWarning: 'SqlRender::renderSql' is deprecated.
Use 'render' instead.
See help("Deprecated")

Warning: deprecatedWarning: 'SqlRender::translateSql' is deprecated.
Use 'translate' instead.
See help("Deprecated")

**Comment by alondhe** [comment]
> Achilles 1.6.3 has been installed, and it is still the same problem even when running 1.6.3.
> 
> When I put createIndices=false and run it, I get two warnings below just before it stops.
> 
> Warning: deprecatedWarning: 'SqlRender::renderSql' is deprecated.
> Use 'render' instead.
> See help("Deprecated")
> 
> Warning: deprecatedWarning: 'SqlRender::translateSql' is deprecated.
> Use 'translate' instead.
> See help("Deprecated")

Those warnings are fine; SqlRender's renderSql and translateSql functions have been renamed to render and translate, but the old functions still work for now.

**Comment by SungJun9212** [comment]
![image](https://user-images.githubusercontent.com/31676950/96538758-41214c00-12d4-11eb-9ae0-996e7b26cc66.png)

But there are only warnings.

**Comment by SungJun9212** [comment]
And this is errorreport.

![image](https://user-images.githubusercontent.com/31676950/96538832-79c12580-12d4-11eb-88ad-22370c5a4795.png)

**Comment by alondhe** [comment]
Can you post the log_achilles.txt file?

**Comment by SungJun9212** [comment]
Where is the file?
