### ISSUE TITLE
Error while executing Achilles command.

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/Achilles#496]
=====================================
I'm ran this command.
---------------------------------------------------------------
achilles(connectionDetails, cdmDatabaseSchema = "cdm",resultsDatabaseSchema="result", vocabDatabaseSchema = "voca",sourceName = "cdm", cdmVersion = "5.2",numThreads=1,runHeel=False)
=====================================

=====================================
I met numerous warnings.
---------------------------------------------------------------
Warning: This function is deprecated. Use 'render' instead.
Warning: This function is deprecated. Use 'translate' instead.
Warning: This function is deprecated. Use 'render' instead.
Warning: This function is deprecated. Use 'translate' instead.
Warning: This function is deprecated. Use 'render' instead.
Warning: This function is deprecated. Use 'translate' instead.
.
.
.
Warning: This function is deprecated. Use 'render' instead.
Warning: This function is deprecated. Use 'translate' instead.
=====================================

=====================================
and error has occured.
---------------------------------------------------------------
Error: 'makeCluster' is not an exported object from 'namespace:OhdsiRTools'
=====================================

what is 'makeCluster'?

**Comment by schuemie** [comment]
I think you're running an old version of Achilles? Newer versions don't depend on OhdsiRTools.

**Comment by SungJun9212** [comment]
I am using achilles version 1.6.3 with webapi and atlas version 2.6.0.

**Comment by schuemie** [comment]
That is the latest version, but it is over two years old. Maybe install from the master branch?

```r
devtools::install_github("OHDSI/Achilles")
```

**Comment by alondhe** [comment]
Latest is 1.6.7, please install the latest from master

**Comment by SungJun9212** [comment]
There was a problem with the version. Thank you.
