### ISSUE TITLE
Acchillies Analysis Issue

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/Achilles#497]
Getting the following error when running the analysis. 
Thread 1 returns error: "invalid format '%d'; use format %s for character objects" when using argument(s): list(analysisId = "Drug", sql = "DROP TABLE IF EXISTS scratch.tmpach_Drug_cost_raw;\n\n\n  --HINT DISTRIBUTE_ON_KEY(cost_event_id) \nCREATE TABLE #rawCost\n  \nDISTKEY(cost_event_id)\nAS\nSELECT\ncost_event_id,\n    paid_patient_copay,paid_patient_coinsurance,paid_patient_deductible,paid_by_payer,paid_by_primary,paid_by_patient,total_paid,paid_ingredient_cost,paid_dispensing_fee,total_cost\n  \nFROM\nCMSDESynPUF100k.cost\n  where cost_domain_id = 'Drug'\n  ;\n\n\n--HINT DISTRIBUTE_ON_KEY(subject_id) \nCREATE TABLE scratch.tmpach_Drug_cost_raw\n\nDISTKEY(subject_id)\nAS\nSELECT\nB.Drug_concept_id as subject_id,\n  paid_patient_copay,paid_patient_coinsurance,paid_patient_deductible,paid_by_payer,paid_by_primary,paid_by_patient,total_paid,paid_ingredient_cost,paid_dispensing_fee,total_cost\n\nFROM\n#rawCost A\njoin CMSDESynPUF100k.drug_exposure B \n  on A.cost_event_id = B.drug_exposure_id and B.Drug_concept_id <> 0\n;\n\ntruncate table #rawCost;\ndrop table #rawCost;")
  |===========================================================================================| 100%
Error in OhdsiRTools::clusterApply(cluster = cluster, x = rawCostSqls,  : 
  Error(s) when calling function 'fun', see earlier messages for details

Can somebody let me know what is causing this and how to resolve that.

**Comment by alondhe** [comment]
That looks like an older version. Can you install from master?

`devtools::install_github("OHDSI/Achilles")`
