### ISSUE TITLE
Drug records mapped to CVX concepts are not showing up in Achilles web

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Achilles#499]
I haven't yet checked the achilles tables but the achilles web application does not show any drug records that have been mapped to CVX concepts (vaccines).

**Comment by alondhe** [comment]
AchillesWeb is deprecated in favor of Atlas Data Sources. Is it showing the same issue in Atlas?

**Comment by clairblacketer** [comment]
@alondhe it is a problem with the queries only grabbing RxNorm so it occurs in Atlas too.

@PRijnbeek are you using AchillesWeb for EHDEN? Do we need to bring up the question of continued development?

**Comment by PRijnbeek** [comment]
No we do not use it in EHDEN we built our own dashboards for our Catalogue. Thanks.

**Comment by alondhe** [comment]
Can you share a few concept examples?

**Comment by fdefalco** [comment]
Achilles analyzes drugs as identified through the query that builds the treemap visualization (this is the inherent problem).  The query (https://github.com/OHDSI/Achilles/blob/80e6ae9363dd76992c73360c61e3b6afb9a9e5df/inst/sql/sql_server/export/drug/sqlDrugTreemap.sql) does not return the drugs in CVX so this issue will persist in Achilles / Web / Datasources (ATLAS).
