### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#5]
Installing the package package below fails. I am on Win7 in RStudio.
The other 2 packages install fine.

Maybe other users see the same error....

Here is the error
>install_github("ohdsi/SqlRender")

Installing SqlRender
"C:/PROGRA~1/R/R-31~1.0/bin/x64/R" --vanilla CMD INSTALL  \
  "C:\Users\huserv\AppData\Local\Temp\1\Rtmp4OBuft\devtools38a45b0c7062\SqlRender-master"  \
  --library="C:/Users/huserv/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'SqlRender' ...
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="SqlRender.dll" OBJECTS="RcppExports.o RcppWrapper.o SqlRender.o SqlSplit.o SqlTranslate.o stringUtilities.o"' had status 127

ERROR: compilation failed for package 'SqlRender'

* removing 'C:/Users/huserv/Documents/R/win-library/3.1/SqlRender'
Error: Command failed (1)

**Comment by phanikumarpingali** [comment]
I am trying to run "install_github("ohdsi/SqlRender")" on windows 7, 64-bit with jdk 7 (64- bit), R version 3.1.2 and R-GUI (64-bit).

I am getting the following error:

> library("devtools")
Warning message:
package ‘devtools’ was built under R version 3.1.3 
> install_github("ohdsi/SqlRender")
Downloading github repo ohdsi/SqlRender@master
Installing SqlRender
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/PPingali/AppData/Local/Temp/RtmpMtqVJl/devtools1318104472eb/OHDSI-SqlRender-cc551a2"  \
  --library="C:/Users/PPingali/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'SqlRender' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/PPingali/Documents/R/win-library/3.1/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/PPingali/Documents/R/win-library/3.1/SqlRender'
Error: Command failed (1)

Please help me out in fixing this issue...
Thanks in advance.....

**Comment by schuemie** [comment]
The problem might be that you only have a 64-bit version of Java, but `install_github` is trying to build both the 32-bit and 64-bit version of the package. For some reason the simple JRE from Oracle does not have this problem, but the JDK does. You can try one of two things:

1. Install a 32-bit Java version next to your 64-bit one

2. Install all OHDSI packages using the `args="--no-multiarch"` option, so for example
```r 
install_github("ohdsi/SqlRender", args="--no-multiarch")
```

**Comment by phanikumarpingali** [comment]
Thanks for the reply... Its working fine now !!!

**Comment by devincwru** [comment]
Hi, 
I run  the command in Windows, install_github("ohdsi/SqlRender", args="--no-multiarch"). Still get the following error:
Error: package or namespace load failed for 'SqlRender':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/yxt30/Documents/R/win-library/3.5/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Could you please help? -Thanks!
