### ISSUE TITLE
Column "paid_copay" does not exist

### ISSUE THREAD

**Issue by tlecarrour-ee** [OHDSI/Achilles#500]
Hi,

### Expected behavior

Achilles analysis completes.

### Actual behavior

Crashes with the following error:

```
Loading required package: DatabaseConnector
Connecting using PostgreSQL driver
Warning: Cohort table not found, will skip analyses 1700 and 1701
Beginning single-threaded execution
Connecting using PostgreSQL driver
  |======================================================================| 100%
Executing SQL took 0.276 secs
Warning: Temp table name '#s_tmpach_Drug_rawCost' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
Warning: Temp table name '#s_tmpach_Drug_cost_raw' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
Warning: Temp table name '#s_tmpach_Procedure_cost_raw' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
Warning: Temp table name '#s_tmpach_Procedure_rawCost' is too long. Temp table names should be shorter than 22 characters to prevent Oracle from crashing.
[Raw Cost] [START] 15000
  |==========                                                            |  14%Error: Error executing SQL:
org.postgresql.util.PSQLException: ERROR: column "paid_copay" does not exist
  Position: 116
An error report has been created at  /home/ohdsi/errorReportSql.txt
```

### Steps to reproduce behavior

Install Achilles from master (80e6ae9, if I install the latest tagged version I hit #497) and run it on CDM v5.3.1 (GNU/Linux Debian 10 + PostgreSQL 11).

The column that does exist in the CDM is `paid_patient_copay`.  This deprecation is listed in `/inst/csv/achilles/achilles_cost_columns.csv`, but it's not taken into account.

Any help welcome!

**Comment by alondhe** [comment]
@tlecarrour-ee is this after setting the cdmVersion parameter to "5.3.1"?

**Comment by tlecarrour-ee** [comment]
Hi @alondhe 

Indeed, I was using the default version, "5"! I'm re-running the analysis and I'll re-open the issue only if the problem persists!

Thanks

**Comment by sushant097** [comment]
Hi @tlecarrour-ee how would you solve this problem I got this error too: 
![image](https://user-images.githubusercontent.com/30827903/125031849-e079af80-e0ac-11eb-9cb2-c64ce13d82e5.png)

**Comment by tlecarrour-ee** [comment]
Hi @sushant097,

> Hi @tlecarrour-ee how would you solve this problem I got this error too:

Seems that fixing the version solved the problem for me, for I haven't had this error since.
