### ISSUE TITLE
Missing cost=1 for analysis 1425

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#501]
### Expected behavior
1425 is not run when i set runCostAnalysis = FALSE
### Actual behavior
it is run and then an error in the merge occurs

1425 | 0 | 0 |   | Number of payer_plan_period records by payer_source_concept_id
-- | -- | -- | -- | --

should be

1425 | 0 |1 |   | Number of payer_plan_period records by payer_source_concept_id
-- | -- | -- | -- | --

Error:  Invalid object name 'scratch.tmpach_1425'

### Steps to reproduce behavior
set runCostAnalysis = FALSE

**Comment by alondhe** [comment]
This isn't considered a cost analysis as it doesn't touch the cost table. Does your CDM not have a payer_plan_period table?

**Comment by PRijnbeek** [comment]
ok was not aware of that definition of cost analysis. However, that still does not explain the error i got.

My cdm has a  payer_plan_period table indeed.

**Comment by alondhe** [comment]
Does your Achilles log file (not the DatabaseConnector error file) mention the specific error when trying to run analysis 1425?

**Comment by fdefalco** [comment]
I'm unable to replicate this error.  Is it still occurring? If so can you provide the full achilles log?
