### ISSUE TITLE
inconsistent limitation to observation_period

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Achilles#511]
In the queries that are use for the data density plot i like to suggest a change on this line:

https://github.com/OHDSI/Achilles/blob/5d60fa02db53fda776afdb7f9cc9a74a2e99e286/inst/sql/sql_server/analyses/420.sql#L13

This allows events that started before the observation_period and have an end in the observation_period to be returned. This has unwanted effects on the plot (e.g. procedures etc that are in history records that mess up the x-axis). Also this is not consistent with the explanations of these queries that suggest these are starts per month:

420	Number of condition occurrence records by condition occurrence start month

Suggest to remove the is.null and replace by a check only on the start_date.

note this needs to be fixed for the other domain query as well.

**Comment by alondhe** [comment]
@PRijnbeek I agree we have to limit to observation periods, and am working on this in the develop branch. 

However, I'm not sure I agree with your interpretation for analysis 420 that this allows events starting before an observation period.

In 420, we check to see all of the following:

- if the condition start date is before or on an observation period end date
- if the condition end date is after or on an observation period start date 
   - if there is no condition end date (which is fine, this is a nullable field), then we simply check that the condition start date occurs after or on an observation period start date

**Comment by fdefalco** [comment]
Tangentially related I found an issue with analysis 117 which is the denominator for a number of analyses throughout in which sparse data might have limited results with similar visualization consequence and sometimes results being omitted entirely.

https://github.com/OHDSI/Achilles/pull/517/commits/54a043119819786ba6dfda3264155c507ee37072

**Comment by ericaVoss** [comment]
@alondhe I would just do the CONDITION_START_DATE, otherwise you end up pulling in old data with long durations.

We are using the ACHILLES results to help us troubleshoot EHDEN DB, would this be something we could patch ACHILLES soon with?

**Comment by alondhe** [comment]
@ericaVoss happy to patch issues in the develop branch ASAP. 

But, sorry, I'm not following on this one. How does constraining the count to condition events that are wholly within an observation period result in pulling in old data?

**Comment by AnthonyMolinaro** [comment]
Closed by #551
