### ISSUE TITLE
Does not seem to work on SQL Server

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/Achilles#512]
Because of all the issues with OMOP v6, we created an OMOP v5.3.1 version of our database. When I run the latest master of Achilles on that database, I get a very long error dump. I attached it to this issue.

[achilles.txt](https://github.com/OHDSI/Achilles/files/5776655/achilles.txt)

This is how I run achilles:

```R
achilles(connectionDetails, 
         cdmDatabaseSchema = "omop_v5", 
         resultsDatabaseSchema = "omop_dq",
         vocabDatabaseSchema = "omop_v5",
         numThreads = 12,
         sourceName = "lynxcare_nlp", 
         cdmVersion = "5.3.1",
         runHeel = TRUE,
         runCostAnalysis = FALSE)
```

**Comment by alondhe** [comment]
Please attach the log_achilles file, it has more granularity.

Also, using more than 1 thread is only recommended for MPP systems like Redshift, BigQuery, and MS PDW.

**Comment by sdebruyn** [comment]
Thanks for picking this up! Where can I find the log file?

**Comment by alondhe** [comment]
It saves it to log_achilles.txt under the outputFolder

**Comment by sdebruyn** [comment]
Thanks, running it single threaded worked
