### ISSUE TITLE
Column Discrepancies between ACHILLES and CDM?

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#530]
![image](https://user-images.githubusercontent.com/6305439/107660668-83d9ac00-6c56-11eb-9414-439dcf17ef5b.png)

Here are the 2 discrepancies between the DDL code on github and Achilles. The left pane shows [the DDL scripts on github](https://github.com/OHDSI/CommonDataModel/tree/master/Sql%20Server), whereas the right pane shows the code that Achilles v1.6.7 tries to run. I believe the DDL has the correct column name here, since there is a modifier_concept_id on the procedure_occurrence table but no mention of any qualifiers.

however I don't know if we have a V5.3.0 issue vs a V6.0 issue here.

https://github.com/OHDSI/Achilles/blob/80e6ae9363dd76992c73360c61e3b6afb9a9e5df/inst/sql/sql_server/validate_schema.sql#L338-L358

**Comment by clairblacketer** [comment]
@fdefalco this is similar to the issue you were talking about yesterday in the development meeting where we have DDLs hardcoded all over the place

**Comment by alondhe** [comment]
I'd like to axe the validateSchema function from Achilles. If we're moving DQ out of Achilles and focusing just on summary stats, no need for it.

**Comment by fdefalco** [comment]
I am in agreement with Ajit that validation should be handled in DQD.
