### ISSUE TITLE
117 report fails on BigQuery

### ISSUE THREAD

**Issue by konstjar** [OHDSI/Achilles#532]
### Expected behavior
Report 117 is working fine

### Actual behavior
SQL error

### Steps to reproduce behavior
Regular execution.

See report attached
[achillesError_117.txt](https://github.com/OHDSI/Achilles/files/5989774/achillesError_117.txt)

**Comment by fdefalco** [comment]
I don't have access to a bigQuery environment but found the following recommendations.  Could you let me know if either of the options listed in this article works as a solution in your environment?

https://sql.info/d/solved-bigquery-left-outer-join-cannot-be-used-without-a-condition-that-is-an-equality-of-fields-from-both-sides-of-the-join

**Comment by konstjar** [comment]
@fdefalco We will investigate and provide PR

**Comment by mgkahn** [comment]
Maybe relevant, maybe not. I ran into exactly this same issue in a different context. After pursuing the LOJ for hours and hours, I stumbled on the solution, which had **NOTHING** to do with the LOJ. See attached SLACK conversation. In my case, the error was a non-existing column being referenced in a DELETE statement. I have no clue if this is what's happening here. Mostly a warning that what BQ complains as a LOJ issue may or may not be related to the LOJ at all. 

Hours and hours and hours of pursuing the wrong issue....... sigh.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/3923918/108088028-3c2b9980-7035-11eb-88f0-716207831114.png">

**Comment by fdefalco** [comment]
@konstjar Any update on this issue?

**Comment by konstjar** [comment]
@fdefalco could you please assign on @ssuvorov-fls, he is investigating it.

**Comment by fdefalco** [comment]
Is there an update to this issue?
