### ISSUE TITLE
Set up automated Docker builds on the registry

### ISSUE THREAD

**Issue by aerinblue** [OHDSI/Achilles#54]
This would automatically build the docker image of Achilles every time the repo is updated, using the recently added Dockerfile, and store that image on the Docker Hub service (the registry). The advantages are two-fold:
1. Automatic monitoring of build process and notification of failures.
2. Removal of the local build step when running Achilles using Docker.

**Comment by fdefalco** [comment]
I would like to suggest that this Achilles repository is intended to maintain an R package.  I do not believe it should contain a docker image configuration and suggest we remove it.  If there is a need for a docker image that provides an environment that includes Achilles, I propose this should be managed separately.  Any objections?
