### ISSUE TITLE
Analysis 109 - Spotty OBS_PERIOD_STARTS made odd report

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Achilles#573]
https://github.com/OHDSI/Achilles/blob/68b3642bb5c7f825ca30f6980bcd211b03758b59/inst/sql/sql_server/analyses/109.sql#L5-L11

Have an example of a DB where the bulk of data starts in 2004 and then in 2010.  No one has OBSERVATION_PERIOD_START_DATEs in between those years.  meaning when the CROSS JOIN is run there are some years not checked.

This is an edge case, but might be worth thinking about a potential solution.

**Comment by AnthonyMolinaro** [comment]
@ericaVoss  Hey Erica, thanks for the heads up.  Earlier this year, @fdefalco found a similar issue in [analysis 117](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/117.sql) and implemented a clever fix.  @fdefalco , do you think the approach you used for 117 would work here as well?

**Comment by fdefalco** [comment]
Yes, I think using that same solution would be worth a try.
