### ISSUE TITLE
Achilles shows last dataset but current label if the data folder is incorrect

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/Achilles#58]
I noticed this behavior today when I was adding a new dataset to review using Achilles directly in Firefox. Note that I am manually configuring Achilles by editing the datasources.json file. The new dataset was a sub-population of one I had already configured so I expected a much smaller number of patients. However, even though Achilles showed the new datasets name, the data it showed was from the larger dataset that I had viewed earlier in the morning. I found out that I had misspelled the data folder in datasources.json. Once corrected, I refreshed Achilles from the browser and the correct data was shown. 

Obviously, this is fundamentally an "operator error" however, I think that Achilles behavior when the data folder name is incorrect should be to report an error or show no data at all so that users don't accidentally review a previously viewed dataset thinking that it's the new one.

thanks for all the great work!
-R

**Comment by chrisknoll** [comment]
We will try to address this by implementing some sort of 'file not found' check when switching datasource.
