### ISSUE TITLE
Use of Achilles for ETL checking (counts by source value for only selected columns)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#581]
For ETL of CMS Medicare and for MIMIC, we often want to run a count by source values.

E.g., 301 and 325 are overviews by specialty.

But in original data, we check things on xxxx_source_value (not concept, since some are not mapped and appear as concept 0)

We envision that as new analysis   (pick a number e.g., x45 and have it as 345,445,545  etc).

`specialty_source_value`
`visit_source_value`

**Comment by fdefalco** [comment]
These values are now characterized by analysis 1900.
