### ISSUE TITLE
Achilles exited with code 0

### ISSUE THREAD

**Issue by sandu9618** [OHDSI/Achilles#587]
Hi All,

I was setting up achilles using the docker image  thehyve/ohdsi-achilles I am able to connect the postgresql database.

The following is the what I have written in the docker-compose for Achilles.

achilles:
image: thehyve/ohdsi-achilles
hostname: achilles
environment:
ACHILLES_SOURCE: DEFAULT
ACHILLES_DB_URI: postgresql://postgres:1234@postgres/OHDSI
ACHILLES_CDM_SCHEMA: cdm5
ACHILLES_VOCAB_SCHEMA: cdm5
ACHILLES_RES_SCHEMA: webapi
ACHILLES_CDM_VERSION: 5
depends_on:
- webapi
- postgres
networks:
- default
- ohdsi_network

The following results are displayed.

**achilles_1 | Generating procedure treemap
|======================================================================| 100%
achilles_1 | Generating procedure reports
|======================================================================| 100%
achilles_1 | Generating visit_occurrence treemap
|======================================================================| 100%
achilles_1 | Generating visit reports
|======================================================================| 100%
achilles_1 | Generating dashboard report
|======================================================================| 100%
achilles_1 | Export took 7.27 secs
achilles_1 | JSON files can now be found in ./output/DEFAULT/2021-06-13T20.56.54
achilles_1 | There were 50 or more warnings (use warnings() to see the first 50)
ohdsi-docker_achilles_1 exited with code 0**

Achilles just exit without showing any errors

There are no any other errors.

I cannot figure out the reason for the exit of the program.

This is run in docker desktop - Windows 10
Postgresql is set up with postgres docker image.
WebAPI is setup with uwcarg/ohdsi-webapi:2.6.0-postgres docker image.

Can someone please tell me what I’m doing wrong?

Thank you.

**Comment by fdefalco** [comment]
What is it you are expecting that is not happening?  It appears as if Achilles finishes the export and exits normally.  If there is an issue with the docker image, that would have to be addressed by thehyve.
