### ISSUE TITLE
Fatal error when running Achilles on RStudio instance - OHDSIonAWS

### ISSUE THREAD

**Issue by EndlessMe** [OHDSI/Achilles#593]
Every time I run Achilles using the database connector to connect to Amazon Redshift, I receive a fatal error before the entire run can complete that states the following:
`Error: 'makeCluster' is not an exported object from 'namespace:OhdsiRTools'`

Below are the parameters used when running Achilles:
```
achilles(connectionDetails = connectionDetails,
         cdmDatabaseSchema = "study",
         resultsDatabaseSchema = "studyresults",
         scratchDatabaseSchema = "studyresults",
         vocabDatabaseSchema = "study",
         createTable = TRUE,
         createIndices = TRUE,
         cdmVersion = 5.3,
         numThreads = 1,
         dropScratchTables = TRUE,
         runHeel = FALSE)
```
From what I can see, the makeCluster object is from the ParallelLogger package, and this package should only be utilized when running in multi-thread mode. There must be some sort of bug that is causing this behavior.

I am using Achilles version 1.6.3

**Comment by fdefalco** [comment]
makeCluster has been moved from OhdsiRTools to ParallelLogger package. Updating packages should resolve the issue.

**Comment by EndlessMe** [comment]
I rebuilt my entire stack today from scratch, reloaded the data into Redshift. I confirmed that I'm using Achilles version 1.6.3 and OhdsiRTools 2.0.0, but I'm stil getting the same error message as reported above.

**Comment by fdefalco** [comment]
@AnthonyMolinaro Looks like in the drop table function, makeCluster is getting called regardless of if threads = 1 or not.  This should not be happening.

@EndlessMe What is odd about the error that you are getting is that ParallelLogger does in fact export makeCluster (https://github.com/OHDSI/ParallelLogger/blob/master/R/Cluster.R)  and OhdsiRTools::makeCluster is not called by Achilles.

Could you try updating to the master branch of Achilles?

remotes::install_github("OHDSI/Achilles")

This is a beta version of Achilles 1.7.

**Comment by EndlessMe** [comment]
UPDATE: I found the source of my secondary problem and resolved it on my own. I think we're safe to say that this can now be closed, at least for me! Thanks again for all the help.
