### ISSUE TITLE
Analysis 117 does not run on our servers.

### ISSUE THREAD

**Issue by lofung** [OHDSI/Achilles#599]
observation_period is one of the simplest tables in our databases. Previous runs look successful on the same table. I just do not understand why 117 does not run.

-----------------
![1628331221(1)-4](https://user-images.githubusercontent.com/53417646/128674537-dc343e9c-8cd4-40d5-82f5-9c7c84281008.png)

Not sure if it has anything to do with our database.

![image](https://user-images.githubusercontent.com/53417646/128674712-58de2014-7872-4f87-adec-4aafede198cd.png)

**Comment by James-D-Rudd** [comment]
I'm having some similar issues and I'm running Achilles against the [Eunomia](https://github.com/OHDSI/Eunomia) dataset (to verify setup). Although it runs, it takes like 5 minutes and all the other analyses take less than .1 seconds, so something seems to be up with that.

**Comment by fdefalco** [comment]
We have tested this analysis across different database platforms and configurations and haven't found out of the ordinary run times.
