### ISSUE TITLE
Unable to connect Achilles to SQL server

### ISSUE THREAD

**Issue by papaul** [OHDSI/Achilles#60]
I've copied both drivers jtds-1.2.7.jar and sqljdbc4.jar to the C:\Program Files\R\R-3.2.0\library\DatabaseConnector\java directory. Can anyone help in figuring out how to resolve this issue?

SQL Server authentication:
>connectionDetails <- createConnectionDetails(dbms="sql server", server="localhost", schema="OMOP", user="xyz",pasword="123")
>conn <- connect(connectionDetails)

Connecting using SQL Server driver
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLException: I/O Error: DB server closed connection.

Windows authentication: The error message received is 
Connecting using SQL Server driver using Windows integrated security
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:4434edbb-347f-4373-b285-3c44636caeb9
> 

Thanks!

**Comment by papaul** [comment]
Restarting the application fixed the problem. Thanks!

**Comment by schuemie** [comment]
Maybe the problem was the typo in the word 'password'?
```sql
pasword="123"
```
