### ISSUE TITLE
Threads fail with "object 'user' not found" message in multithreaded mode

### ISSUE THREAD

**Issue by KalleMedisapiens** [OHDSI/Achilles#606]
Hi, we get a lot of errors like this when running Achilles in multi threaded mode.

Thread 2 returns error: "object 'user' not found" when using argument(s): DROP TABLE IF EXISTS cdm_achilles.tmpach_101;

Here are our parameters.

achilles(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = "cdm",
  resultsDatabaseSchema = "cdm_achilles",
  scratchDatabaseSchema = "cdm_achilles",
  vocabDatabaseSchema = "cdm",
  sourceName = "OHDSI CDM V5 Database",
  cdmVersion = 5.3,
  numThreads = 10,
  runHeel = TRUE,
  sqlOnly=FALSE,
  outputFolder="."
)

Database is PostgreSQL version 11.13

I attached the log file.

The same problem comes up with Data Quality Dashboard.

[log_achilles.txt](https://github.com/OHDSI/Achilles/files/7185283/log_achilles.txt)

**Comment by fdefalco** [comment]
We are not able to reproduce this error, it appears as it if might be a local permissions error.
