### ISSUE TITLE
Analyse 1833 : SQLServer error - 'GREATEST' is not a recognized built-in function name.

### ISSUE THREAD

**Issue by CGDM-LRocher** [OHDSI/Achilles#607]
Hi,

Usage of GREATEST in Analyse 1833 produce an error with SqlServer.

https://github.com/OHDSI/Achilles/blob/1db677b6e6df607387e558142796f2f3687c17a3/inst/sql/sql_server/analyses/1833.sql#L16

According Microsoft documentation, GREATEST is only availlable on SQL Azure : [Fonctions logiques - GREATEST (Transact-SQL)](https://docs.microsoft.com/fr-fr/sql/t-sql/functions/logical-functions-greatest-transact-sql?view=sql-server-ver15)

In this particular case, it possible to use a simple IIF : 

```sql
	                  THEN 1 ELSE 0 END)/IIF(count(*) > 1, count(*), 1) AS NUMERIC(7,6)) AS VARCHAR(255)) AS stratum_3, 
```

But, i don't know if it's compatible with other database engine

**Comment by ted9219** [comment]
Thanks. This is helpful.
