### ISSUE TITLE
Achilles Check Rule Error

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/Achilles#612]
**In Achillesheel 301-rule_11**
![image](https://user-images.githubusercontent.com/45930454/140874267-818d5253-16d7-44b2-ad11-9187460af628.png)

「PROVIDER's domain_id='provider specialty' 」 it is old version.

Now, all  specialty_concept_id's domain_id is "Provider".(bellow image is a sample in ATHENA)
![image](https://user-images.githubusercontent.com/45930454/140874890-f6df6ea7-bbdc-4bb7-b34c-367b18e7022c.png)

SO  Achillesheel Rule Should be fix.

**Comment by fdefalco** [comment]
AchiilesHeel was deprecated and will be removed from the Achilles package.
