### ISSUE TITLE
Add number of records by drug_type_concept_Id

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Achilles#615]
It would be really nice to have a report that calculates number of drug records by drug_type_concept_id

**Comment by fdefalco** [comment]
clarifying that you are looking for an overall drug summary level stratification by drug_type_concept_id as the drug_type_concept_id stratification exists on the concept level drug report?

**Comment by fdefalco** [comment]
fixed in https://github.com/OHDSI/Achilles/commit/edbf6abbeac5ff8f087d21dd794952c63102bbdc
