### ISSUE TITLE
AchillesError_2004  too short varchar length 

### ISSUE THREAD

**Issue by HarryM2** [OHDSI/Achilles#621]
**Describe the bug**
Running Achilles generates an achillesError_2004.txt file, due to too short of a varchar being set for one of the queries. 

1-22 06:49:01	Analysis 2004 -- ERROR Error in FALSE: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error converting numeric to data type varchar.
An error report has been created at  D:/R/WorkingDirectory/achillesError_2004.txt 

The erroring line:
       cast((1.0 * personIntersection.count_value / totalPersonsDb.totalPersons) as varchar(6)) as stratum_2,
should be at a minimum a VARCHAR(14) to work in our testing.

**To Reproduce**
Achilles 1.6.7

Contents of AchillesError_2004.txt begins as:
              DBMS:
              sql server
              
              Error:
              com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error converting numeric to data type varchar.
              
              SQL:
              with rawData as (
              select 2004 as analysis_id,
                     '0000001' as stratum_1,
                     cast((1.0 * personIntersection.count_value / totalPersonsDb.totalPersons) as varchar(6)) as stratum_2,
                     CAST(NULL AS VARCHAR(255)) as stratum_3,
                     CAST(NULL AS VARCHAR(255)) as stratum_4,
                     CAST(NULL AS VARCHAR(255)) as stratum_5,
                     personIntersection.count_value
                    from
                    (select count(*) as count_value from(select person_id from #obs) as subquery) as personIntersection,
                (select count(distinct(person_id)) as totalPersons from OMOPICB.dbo.person) as totalPersonsDb UNION ALL
              select 2004 as analysis_id,
                     '0000010' as stratum_1,
                     cast((1.0 * personIntersection.count_value / totalPersonsDb.totalPersons) as varchar(6)) as stratum_2,
                     CAST(NULL AS VARCHAR(255)) as stratum_3,
                     CAST(NULL AS VARCHAR(255)) as stratum_4,
                     CAST(NULL AS VARCHAR(255)) as stratum_5,
                     personIntersection.count_value
                    from
                    (select count(*) as count_value from(select person_id from #prococ) as subquery) as personIntersection,
                (select count(distinct(person_id)) as totalPersons from OMOPICB.dbo.person) as totalPersonsDb UNION ALL

and continues for all the unions.

**Expected behavior**
No Error file should be generated, and the sql query should not return an error of 

**Screenshots**
![image](https://user-images.githubusercontent.com/51327205/142859319-f8ebce9c-0eb3-4b4f-9c72-2b8e720548b8.png)

**Desktop (please complete the following information):**
OS: Windows 10 or Windows Server 2019
SQL Server : Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   
R: 4.1.1
RStudio-2021.09.0-351

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aandryc** [comment]
PR submitted to address this issue.  Increased VARCHAR to 255.
