### ISSUE TITLE
update performance logging behavior

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Achilles#626]
current behavior logs results with a 'secs' unit text, this should be removed.

	paste0(round(as.numeric(strsplit(logs[1,]$runTime," ")[[1]][1]),2)," secs")

update generateAOAchillesPerformanceReport function to include the category as analysis_category column, this will roll up to network performance reporting.  requires update of column name in function and update to sql query

export/performance/sqlAchillesPerformance.sql

**Comment by AnthonyMolinaro** [comment]
fixed via #634
