### ISSUE TITLE
Document process for proposing new statistics/reports to Achilles

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Achilles#64]
There is interest in the community to add new queries/statistics/reports to Achilles, but not a lot of information about how this should be done.

Propose new wiki pages to guide through this process, possibly with videos.

**Comment by vojtechhuser** [comment]
Well, the main issue for this is support for v4 and v5. And how to best do it via GitHub

**Comment by vojtechhuser** [comment]
If a suggesting person is capable of implementing it, most effective would be to propose a code change via github and "code master" would approve the marge with master.
