### ISSUE TITLE
ParallelLogger and rJson require R v4.0.0 or higher

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/Achilles#640]
**Describe the bug**
The README and documentation states that Achilles 
> Requires R (version 3.6.0 or higher).

However installation of Achilles on R v3.6.1 fails with:
```R
> remotes::install_github("OHDSI/Achilles")
Downloading GitHub repo OHDSI/Achilles@HEAD
Skipping 2 packages not available: ParallelLogger, rjson
Running `R CMD build`...
* preparing ‘Achilles’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘Achilles_1.7.tar.gz’
Installing package into ‘R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependencies ‘rjson’, ‘ParallelLogger’ are not available for package ‘Achilles’
* removing ‘/home/afernandez/R/x86_64-pc-linux-gnu-library/3.6/Achilles’
```

Both `rJson` and `ParallelLogger` require R version >=4.0.0

**To Reproduce**
1. Run `remotes::install_github("OHDSI/Achilles")` on R version >3.6.0 and <4.0.0

**Expected behavior**
Either update the documentation or add support for R version 3.6 and higher.

**Comment by stefpiatek** [comment]
If you're running the Broadsea-Methods-Library I've made a [PR](https://github.com/stefpiatek/Broadsea-MethodsLibrary) for updating the image to R 4.1.2 and it's on dockerhub if that's useful [stefpiatek/broadsea-methodslibrary](https://hub.docker.com/r/stefpiatek/broadsea-methodslibrary)
