### ISSUE TITLE
github pages site giving 404

### ISSUE THREAD

**Issue by actualben** [OHDSI/Achilles#644]
**Describe the bug**

The github pages site <https://ohdsi.github.io/Achilles/> is currently giving 404. This site is linked from <https://github.com/OHDSI/Achilles#user-documentation>

**To Reproduce**

1. Go to <https://ohdsi.github.io/Achilles/>
2. See 404 response: <https://web.archive.org/web/20220314073530/https://ohdsi.github.io/Achilles/>

**Expected behavior**

I expected to see the R package documentation for Achilles, such as <https://ohdsi.github.io/Achilles/reference/achilles.html>

**Comment by actualben** [comment]
It looks like the last deployment failed: <https://github.com/OHDSI/Achilles/actions/runs/1918845403>.

**Comment by fdefalco** [comment]
I believe this had to do with the renaming of the master branch to main, pages appear to be published again now. Thanks for pointing this out.
