### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Achilles#645]
**Describe the bug**
I'm not sure if this is a bug because the documentation says it works on RedShift and PDW. However, I tried running Achilles on MS SQL Server. When running the multi-threaded version of Achilles on MS Sql Server, it seems to error at the merge step. I set the number of threads to 10 and the output shows that all analyses were run as shown below:

```
	Executing multiple queries. This could take a while
  |================================================================| 100%
```

However, after this step I get the following error in the console window in Studio:

```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 27 did not have 6 elements
```

In the log file I see this error message:

```
[Main thread]	FATAL	utils	read.table	line 27 did not have 6 elements
```

**Comment by fdefalco** [comment]
Does the error occur when running in single-threaded mode? I avoid multi-threaded because I typically have no luck with its execution.
