### ISSUE TITLE
concat function

### ISSUE THREAD

**Issue by moshe2590** [OHDSI/Achilles#648]
Hi all,

The achilles function "exportToJson" runs few sql scripts. 
In some of them concat function is used in the following way:

concat(isNull(concept_hierarchy.soc_concept_name,'NA'),
'||', isNull(concept_hierarchy.hlgt_concept_name,'NA'),
'||', isNull(concept_hierarchy.hlt_concept_name,'NA'),
'||', isNull(concept_[hierarchy.pt](http://hierarchy.pt/)_concept_name,'NA'),
'||', isNull(concept_hierarchy.snomed_concept_name,'NA'))

But i get an error :
function concat(character varaying "unknown" , character varaying "unknown", character varaying "unknown"...) does not exist.

I searched for a solution in google and it seems it needed to replace concat with || operator for concatination. 

I wanted to check this solution so i copied the script and ran it  with the replacing the concat and it seems to work..

Is this a known issue? I would like to get help with this.

I'm working in redshift tables. 
Thank you.

**Comment by fdefalco** [comment]
Are you specifying the redshift dbms platform when you are running the package?  SqlRender should be translating the query so it runs properly on redshift.  If you can share the code you are using to run Achilles that might help debug.

**Comment by moshe2590** [comment]
The code I am running is as follows:
Sys.setenv("DATABASECONNECTOR_JAR_FOLDER" = "########")

connectionDetails <- createConnectionDetails(
dbms="postgresql",
server="#################/##############",
user="#####",
password="######",
port="5439",
pathToDriver="#########"
) 

Achilles::achilles(connectionDetails =connectionDetails , cdmDatabaseSchema = "####", resultsDatabaseSchema = "####",
outputFolder = "####", cdmVersion = 5, analysisIds = analysisIds, createIndices = False)

Achilles::exportToJson(connectionDetails , "####", "####","####/AchiillesWeb/data/ANTHEM")

As you can see the dbms set to postgresql. I have tried to run it using dbms = redshift, but then i got the error: java.lang.NoClassDefFoundError: org/antlr/v4/runtime/CharStream

The achilles function is working perfect, but exportToJson failes with the error I mentioned in the first message.
