### ISSUE TITLE
ReadMe reference to Vignette:Running Achilles On Your CDM is invalid

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Achilles#649]
**Describe the bug**
Reference is to "https://github.com/OHDSI/Achilles/raw/master/vignettes/RunningAchilles.pdf" results in "Page not found"

**To Reproduce**
1. Go to readme
2. Click on Vignette:Running Achilles On Your CDM (Note: link to Running  Achilles vignette appears in two places in ReadMe)
3.  404 Page not found

**Expected behavior**
Link to Running Achilles vignette

**Comment by fdefalco** [comment]
thanks @don-torok.  I've updated the readme to point to the github.io documentation directly.  The vignette will still be available within the package when installed.
