### ISSUE TITLE
docker-compose build fails due to openjdk-6-jdk

### ISSUE THREAD

**Issue by dtabacco** [OHDSI/Achilles#66]
$ sudo docker-compose build

 ---> Running in 5cb42fa9dd4e
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [177 kB]
Get:3 http://http.debian.net sid InRelease [253 kB]
Ign http://http.debian.net jessie InRelease
Get:4 http://http.debian.net jessie-updates InRelease [142 kB]
Get:5 http://http.debian.net jessie Release.gpg [2,373 B]
Get:6 http://http.debian.net sid/main amd64 Packages [10.1 MB]
Get:7 http://http.debian.net jessie Release [148 kB]
Get:8 http://http.debian.net jessie/main amd64 Packages [9,035 kB]
Get:9 http://http.debian.net jessie-updates/main amd64 Packages [3,614 B]
Fetched 19.9 MB in 2s (7,089 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package openjdk-6-jdk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apt

E: Package 'openjdk-6-jdk' has no installation candidate
Service 'achilles' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y     libssl-dev     libcurl4-openssl-dev     libxml2-dev     openjdk-6-jdk     && rm -rf /var/lib/apt/lists/*     && R CMD javareconf' returned a non-zero code: 100

Have you seen this before during builds?

$ uname -a
Linux ip-54-40-17-252 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aaron0browne** [comment]
This is probably because the underlying debian version of the docker image changed and has migrated to openjdk-7-jdk. Try replacing the 6 with a 7 in your local copy of the Dockerfile and testing the build.

**Comment by dtabacco** [comment]
That did the trick.  Thank you!
