### ISSUE TITLE
Docker using Oracle require pre-requisite driver installation?

### ISSUE THREAD

**Issue by dtabacco** [OHDSI/Achilles#67]
I have my env_vars configured to connect to an Oracle Database (using oracle://).  When i run, I get this error:

ubuntu@ip-54-40-17-252:~/Achilles$ docker-compose run achilles
Loading required package: SqlRender
Loading required package: DatabaseConnector
Loading required package: RJDBC
Loading required package: methods
Loading required package: DBI
Loading required package: rJava
Loading required package: rjson
Connecting using Oracle driver
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  :
  java.lang.UnsatisfiedLinkError: no ocijdbc11 in java.library.path
Calls: achilles ... .valueClassTest -> is -> is -> .local -> .jcall -> .jcheck -> .Call
Execution halted

Has this been tested with Oracle?  Are there any other steps required?

**Comment by aaron0browne** [comment]
Not surprised you ran into that issue. You need to add the Oracle drivers for yourself in a custom Dockerfile, since they are licensed. In my experience, if you put the versions of Oracle instantclient basic and sdk in a `lib` directory at the project root and then add the following to your Dockerfile, it should work.

Below line 8 (just before the `# Install java and clean up.` comment:

```
# Install Oracle client C header files.
COPY lib/ /app/lib/
RUN apt-get -qq update && apt-get -qq install -y unzip
RUN unzip -qq /app/lib/instantclient-basic-linux.x64-11.2.0.4.0.zip \
    -d /usr/local/lib
RUN unzip -qq /app/lib/instantclient-sdk-linux.x64-11.2.0.4.0.zip \
    -d /usr/local/lib
RUN ln -s /usr/local/lib/instantclient_11_2/libclntsh.so.11.1 \
    /usr/local/lib/instantclient_11_2/libclntsh.so

# Set Oracle environment variables
ENV ORACLE_HOME /usr/local/lib/instantclient_11_2
ENV LD_LIBRARY_PATH /usr/local/lib/instantclient_11_2

```

Below line 15 (in the `apt-get` install list):

```
    libaio1 \
```

**Comment by dtabacco** [comment]
I added those steps.  It builds successful, but I still get an error when I run:

$ sudo docker-compose build
Warning: the mapping "achilles_output:/opt/app/output:rw" in the volumes config for service "achilles" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./achilles_output:/opt/app/output:rw"
Building achilles...
Step 0 : FROM r-base:3.1.2
 ---> c04052b3ddd2
Step 1 : MAINTAINER Aaron Browne <brownea@email.chop.edu>
 ---> Using cache
 ---> dd0528aef095
Step 2 : RUN echo '' > /etc/apt/apt.conf.d/default
 ---> Using cache
 ---> ce4f023fe0ec
Step 3 : COPY lib/ /app/lib/
 ---> Using cache
 ---> 41c1b59944f6
Step 4 : RUN apt-get -qq update && apt-get -qq install -y unzip
 ---> Using cache
 ---> 451c7c144ea9
Step 5 : RUN unzip -qq /app/lib/instantclient-basic-linux.x64-11.2.0.4.0.zip     -d /usr/local/lib
 ---> Using cache
 ---> 7671d6361c1b
Step 6 : RUN unzip -qq /app/lib/instantclient-sdk-linux.x64-11.2.0.4.0.zip     -d /usr/local/lib
 ---> Using cache
 ---> 817eaffba316
Step 7 : RUN ln -s /usr/local/lib/instantclient_11_2/libclntsh.so.11.1     /usr/local/lib/instantclient_11_2/libclntsh.so
 ---> Using cache
 ---> e46a3861a23b
Step 8 : RUN apt-get update &&     apt-get install -y     libssl-dev     libcurl4-openssl-dev     libxml2-dev     openjdk-7-jdk     libaio1     && rm -rf /var/lib/apt/lists/*     && R CMD javareconf
 ---> Using cache
 ---> 22d4cdbabd37
Step 9 : RUN install2.r --error     devtools     httr     rjson     && installGithub.r     OHDSI/SqlRender     OHDSI/DatabaseConnector     && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
 ---> Using cache
 ---> 0d4e3edbad6e
Step 10 : WORKDIR /opt/app
 ---> Using cache
 ---> 675d99e66a5d
Step 11 : ENV PATH /opt/app:$PATH
 ---> Using cache
 ---> bc801f5d45e8
Step 12 : VOLUME /opt/app/output
 ---> Using cache
 ---> d107d1b79606
Step 13 : COPY . /opt/app/
 ---> cda424d49886
Removing intermediate container ea6ec9df0ee1
Step 14 : RUN chmod +x /opt/app/docker-run
 ---> Running in f415a056d31b
 ---> d8a1906432ab
Removing intermediate container f415a056d31b
Step 15 : RUN R CMD INSTALL /opt/app     && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
 ---> Running in cb9e5b15fd49
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘Achilles’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (Achilles)
 ---> 409438021de7
Removing intermediate container cb9e5b15fd49
Step 16 : CMD docker-run
 ---> Running in 49bfdd7d514d
 ---> 58dbf6cd0dce
Removing intermediate container 49bfdd7d514d
Successfully built 58dbf6cd0dce

$ sudo docker-compose run achilles
Warning: the mapping "achilles_output:/opt/app/output:rw" in the volumes config for service "achilles" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./achilles_output:/opt/app/output:rw"
Loading required package: SqlRender
Loading required package: DatabaseConnector
Loading required package: RJDBC
Loading required package: methods
Loading required package: DBI
Loading required package: rJava
Loading required package: rjson
Connecting using Oracle driver
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  :
  java.lang.UnsatisfiedLinkError: no ocijdbc11 in java.library.path
Calls: achilles ... .valueClassTest -> is -> is -> .local -> .jcall -> .jcheck -> .Call
Execution halted

Here is an ls of my lib directory inside the achilles project:
Achilles$ ls lib/
instantclient-basic-linux.x64-11.2.0.4.0.zip
instantclient-sdk-linux.x64-11.2.0.4.0.zip

Any ideas?

**Comment by dtabacco** [comment]
Almost there.  Now I get this:  My DB url uses a /service-name at the end instead of a SID.  is that a problem?

Connecting using Oracle driver
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[         1],  :
  java.sql.SQLException: ORA-12541: TNS:no listener
Calls: achilles ... .valueClassTest -> is -> is -> .local -> .jcall -> .jcheck -         > .Call
Execution halted

**Comment by aaron0browne** [comment]
Yeah, I've always been a bit confused by the multitude of ways one can specify connection to an Oracle DB. I would suggest trying several different permutations of your `ACHILLES_DB_URI` environment variable.

Here's the relevant code. Perusing it may help to figure out what's going wrong, if you have more Oracle knowledge than I do...

The `docker-run` script parses your `ACHILLES_DB_URI` using `parse_url` (impenetrable RFC1808 implementation [here](https://github.com/hadley/httr/blob/master/R/url.r#L29)), and then those pieces to call `createConnectionDetails`, the result of which is passed to the `connect` function by Achilles, which comes from the `OHDSI/DatabaseConnector` package, the relevant (Oracle) lines of which are [here](https://github.com/OHDSI/DatabaseConnector/blob/master/R/DatabaseConnector.R#L220).

You could also `docker run -it <achilles_image_name> /bin/bash` and try to debug the relevant R function calls from the shell.

**Comment by dtabacco** [comment]
I added a print statement to the docker-run file and this is what it gave me what is printed below.  Also, the DBA gave me a SID instead of a service name, hoping that would help.

Based on this config:
ACHILLES_DB_URI=oracle://myuser:xxxxxxxxx@myserver:myport/mysid

print (db_conf)

$scheme
[1] "oracle"

$hostname
[1] "myserver"

$port
[1] "myport"

$path
[1] "mysid"

$query
NULL

$params
NULL

$fragment
NULL

$username
[1] "myuser"    

$password
[1] "xxxxxxxxx"       

attr(,"class")
[1] "url"

print (server)
[1] "myserver/mysid"

print (connectionDetails)

[1] "createConnectionDetails"

$dbms
[1] "oracle"

$user
[1] "myusername"

$password
[1] "xxxxxxxxx"

$server
[1] "myserver/mysid"

$port
[1] "myport"

$schema
[1] "myside"

attr(,"class")
[1] "connectionDetails"

It gives me the following error though:
Connecting using Oracle driver
Error in .local(conn, statement, ...) :
  execute JDBC update query failed in dbSendUpdate (ORA-01435: user does not exist
)
Calls: achilles ... connect.default -> <Anonymous> -> <Anonymous> -> .local
Execution halted

I can connect to the DB using SQL Developer using the config information.  I feel like i've tried everyithng.

**Comment by aaron0browne** [comment]
OK, here's a little interactive debugging session, inspired by the DatabaseConnector code, at the R shell inside of the container. Everything up to the `host` variable assignment is just setup. Once you get there, you can assign whatever you think might work to the various variables and try the three different connection methods that Achilles will use for yourself, until you get it to work. Once you figure out which connection method with which values gets you a successful connection, I can help reverse engineer that all the way back out to the environment variable.

```
$ dcomp run achilles R

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

jdbcDrivers <<- new.env()
jdbcSingleton <- function(driverClass = "", classPath = "", identifier.quote = NA) {
  key <- paste(driverClass, classPath)
  if (key %in% ls(jdbcDrivers)) {
    driver <- get(key, jdbcDrivers)
    if (rJava::is.jnull(driver@jdrv)) {
      driver <- RJDBC::JDBC(driverClass, classPath, identifier.quote)
      assign(key, driver, envir = jdbcDrivers)
    }
  } else {
    driver <- RJDBC::JDBC(driverClass, classPath, identifier.quote)
    assign(key, driver, envir = jdbcDrivers)
  }
  driver
}
pathToJar <- system.file("java", "ojdbc6.jar", package = "DatabaseConnector")
driver <- jdbcSingleton("oracle.jdbc.driver.OracleDriver", pathToJar)
host <- "myserver"
port <- "myport"
sid <- "mysid"
server <- "myserver"
user <- "myuser"
password <- "mypass"
connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@", host, ":", port, ":", sid, sep = ""), user, password)
connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@", server, sep = ""), user, password)
connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:oci8:@", server,msep = ""), user, password)
q()
Save workspace image? [y/n/c]: n
```

**Comment by dtabacco** [comment]
What type of privileges are required for the Oracle user?  The one I am using is read-only.  After some debugging, it's pretty clear its making a connection, but failing during a dbSendUpdate.

Also, what value should I be using for the res_schema?  I am not sure what that is expecting?

**Comment by aaron0browne** [comment]
You need a read/write user. The package writes analysis results to database tables so they are stored for future use. `res_schema` is a schema where those results can be written, in order to allow for separation from the source data.

**Comment by dtabacco** [comment]
I'm not sure how to do the "in container" troubleshooting, because the container execution halts at the JDBC connection setup when executing sudo docker-compose run achilles.

Still not having any luck.

**Comment by aaron0browne** [comment]
You can use `docker-compose run achilles R` to get an R shell inside of a new container, as mentioned above. Similarly, you can use `docker-compose run achilles bash` to get a bash shell inside of a new container.

**Comment by dtabacco** [comment]
I did the interactive debugging from the R shell:

Here is what I found, after populating the DB environment variables

** Connection Statement 1: **
> connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@", host, ":", port, ":", sid, sep = ""), user, password)

> print(connection)
An object of class "JDBCConnection"
Slot "jc":
[1] "Java-Object{oracle.jdbc.driver.T4CConnection@11eb0eac}"

Slot "identifier.quote":
[1] NA

*This may have worked?  I'm not sure how to test this further?  What would the syntax be to try to execute a SQL query on this connection object?*


** Connection Statement 2: **
> connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@", server, sep = ""), user, password)
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  :
  java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection

*This doesn't work*

** Connection Statement 3: **
> connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:oci8:@", server,msep = ""), user, password)
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  :
  java.sql.SQLException: ORA-12541: TNS:no listener

*This doesn't work*

Also, when I run the program normally, how do I know which of the 3 connection statements is being executed?

**Comment by dtabacco** [comment]
Ok, small update.  After running the successful connection statement, I ran this:

RJDBC::dbGetQuery(connection, "select * from CDM_SCHEMA.LOCATION")

and it returned results!

So, now I know that this statement works, when I manually populate the variables:
connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@", host, ":", port, ":", sid, sep = ""), user, password)

Why would it work this way, but return an error when running the program with the env_vars confiuration file?

**Comment by dtabacco** [comment]
I also started working through the Database Connector Code you told me to reference:

 if (dbms == "oracle") {
    writeLines("Connecting using Oracle driver")
    pathToJar <- system.file("java", "ojdbc6.jar", package = "DatabaseConnector")
    driver <- jdbcSingleton("oracle.jdbc.driver.OracleDriver", pathToJar)

    # First THIN driver:
    if (missing(port) || is.null(port))
      port <- "1521"
    host <- "127.0.0.1"
    sid <- server
    if (grepl("/", server)) {
      parts <- unlist(strsplit(server, "/"))
      host <- parts[1]
      sid <- parts[2]
    }
    result <- class(try(connection <- RJDBC::dbConnect(driver, paste("jdbc:oracle:thin:@",
                                                                     host,
                                                                     ":",
                                                                     port,
                                                                     ":",
                                                                     sid,
                                                                     sep = ""), user, password), silent = TRUE))[1]

   

> print(result)
[1] "JDBCConnection"

This works as well.  So, it seems that it should parse env_vars file and get a success using the oracle:thin client and not fall back to the other two methods.

**Comment by dtabacco** [comment]
I traced it a little bit further:

**in Achilles.r:**

  achillesSql <- loadRenderTranslateSql(sqlFilename = achillesFile,
                                        packageName = "Achilles",
                                        dbms = connectionDetails$dbms,
                                        oracleTempSchema = oracleTempSchema,
                                        cdm_database = cdmDatabase,
                                        cdm_database_schema = cdmDatabaseSchema,
                                        results_database = resultsDatabase, 
                                        results_database_schema = resultsDatabaseSchema,
                                        source_name = sourceName, 
                                        list_of_analysis_ids = analysisIds,
                                        createTable = createTable,
                                        smallcellcount = smallcellcount,
                                        validateSchema = validateSchema
  )
  
this command runs successfully and if I print the resulting object, it's a huge string of selects from my cdm_schema and inserts, deletes to my res_schema.ACHILLES_results

however, the next line throws the error:

 conn <- connect(connectionDetails)

Connecting using Oracle driver
Error in .local(conn, statement, ...) :
  execute JDBC update query failed in dbSendUpdate (ORA-01435: user does not exist
)
Calls: achilles ... connect.default -> <Anonymous> -> <Anonymous> -> .local
Execution halted

**Comment by dtabacco** [comment]
How do I debug once my code hits:
 conn <- connect(connectionDetails)

my printout of connectionDetails before the function runs looks correct.

It would be nice if I could add some debug statements to DatabaseConnector.R, but it's not clear to how it's referencing this file as a library?   I don't see this file as part of the achilles project.

**Comment by dtabacco** [comment]
You can disregard my previous messages.  I got the connection working.  I had to hardcode some stuff in achilles.r though.

I have a new problem though:

Executing multiple queries. This could take a while
  |===================================                                   |  50%Error executing SQL: Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (ORA-00942: table or view does not exist
)

An error report has been created at  /opt/app/errorReport.txt
Error in value[[3L]](cond) : no loop for break/next, jumping to top level
Calls: achilles ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by dtabacco** [comment]
Here is my errorreport.txt:  Can you tell which table/view it can't find?

DBMS:
oracle

Error:
execute JDBC update query failed in dbSendUpdate (ORA-00942: table or view does not exist
)

SQL:
insert into <res_schema>.ACHILLES_results (analysis_id, count_value)^M
SELECT     9 as analysis_id,  COUNT(p1.person_id) as count_value^M
  FROM   CDM_<MYDB>.PERSON p1^M
        left join CDM_<MYDB>.care_site cs1^M
        on p1.care_site_id = cs1.care_site_id^M
  WHERE  p1.care_site_id is not null^M
        and cs1.care_site_id is null^M


R version:
R version 3.1.3 RC (2015-03-06 r67947)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- methods
- stats
- graphics
- grDevices
- utils
- datasets
- base

Other attached packages:
- httr (1.0.0)
- Achilles (1.0)
- rjson (0.2.15)
- DatabaseConnector (1.3.0)
- RJDBC (0.2-5)
- rJava (0.9-7)
- DBI (0.3.1)
- SqlRender (1.1.2)

**Comment by dtabacco** [comment]
I looked at my CMD_SCHEMA tables and I don't see a care_site table.  Seems like that would be the issue?  Is that a normal table that belongs in OMOP V4?  none of my OMOP DB's have that table.

**Comment by chrisknoll** [comment]
Hi, dtabacco.  I've read your messages, so I think I'm up to speed.

It is absolutely the problem that if it is selecting from the care_site table and you don't have one, that you'll get an error.

Are you running against a CDM v4 or CDM v5?

The DDL for CDMv4 is at:
https://github.com/OHDSI/CommonDataModel/tree/master/Version4

DDL for v5 is at:
https://github.com/OHDSI/CommonDataModel

There is a paramater for running achilles for making it run as a v4 or v5 cdm.  By default, it's v4.

-Chris

**Comment by dtabacco** [comment]
Yes, I get the same error when running that query in SQL developer directly against the DB.  I'm checking with the people that manage our OMOP DB and i'll find out why the table is missing.

I believe we are using V4 and I did notice the parameter when troubleshooting the achilles.r file.

**Comment by chrisknoll** [comment]
Ok, I think once you get that table back, it will let you proceed.  Also, there is a validateSchema arg for the achilles call (defaults to false, because it can take a while to run) but it will perform a query against each CDM table that the analysis executes against to verify that the table (and columns) exist properly before beginning. So you might want to run the achilles like so:

achillesResults <- achilles(
connectionDetails, cdmDatabaseSchema=env_vars$ACHILLES_CDM_SCHEMA,
resultsDatabaseSchema=env_vars$ACHILLES_RES_SCHEMA, sourceName=src_name,
validateSchema = TRUE
)

-Chris

**Comment by t-abdul-basser** [comment]
Original issue addressed.
