### ISSUE TITLE
failure at mergeAchillesScratchTables

### ISSUE THREAD

**Issue by djogopatrao** [OHDSI/Achilles#678]
**Describe the bug**

**To Reproduce**

The error happens when I run, in a jupyter notebook, the following commands:

install.packages("remotes")
remotes::install_github("OHDSI/Achilles")
remotes::install_github("r-lib/rlang")
library( Achilles )

connectionDetails <- createConnectionDetails(dbms = "impala",
    connectionString = 'jdbc:impala://<redacted>',
    pathToDriver = '/home/jovyan/work/libs/')

Achilles::achilles( connectionDetails = connectionDetails,
         cdmDatabaseSchema = 'sandbox_gov_hdsb_omop_dev',
         resultsDatabaseSchema = 'sandbox_gov_hdsb_omop_dev',
         vocabDatabaseSchema = 'sandbox_gov_hdsb_omop_dev',
         sourceName = 'source1',
         cdmVersion = 5.3,
         numThreads = 1,
         optimizeAtlasCache = TRUE,
         sqlOnly = FALSE,
         outputFolder = '/tmp/' )

**Expected behavior**
The script ends successfully and achilles_results table is correctly filled.

**Screenshots**

Below the full log produced by achilles()

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:45:33	Beginning single-threaded execution

Connecting using Impala driver

  |======================================================================| 100%

Executing SQL took 31.2 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:20	Executing multiple queries. This could take a while

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:20	Analysis 0 (Source name) -- START
  |======================================================================| 100%

Executing SQL took 8.43 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:29	[Main Analysis] [COMPLETE] 0 (8.436860 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:29	Analysis 1 (Number of persons) -- START
  |======================================================================| 100%

Executing SQL took 1.89 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:31	[Main Analysis] [COMPLETE] 1 (1.894001 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:31	Analysis 2 (Number of persons by gender) -- START
  |======================================================================| 100%

Executing SQL took 2.46 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:33	[Main Analysis] [COMPLETE] 2 (2.468496 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:33	Analysis 3 (Number of persons by year of birth) -- START
  |======================================================================| 100%

Executing SQL took 2.36 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:35	[Main Analysis] [COMPLETE] 3 (2.367100 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 19:46:35	Analysis 4 (Number of persons by race) -- START
  |======================================================================| 100%

Executing SQL took 2.03 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

Output of this cell has been trimmed on the initial display.

Displaying the first 50 top and last bottom outputs.

Click on this message to get the complete output.

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:33	Analysis 2130 (Number of device_exposure records inside a valid observation period) -- START
  |======================================================================| 100%

Executing SQL took 1.79 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:35	[Main Analysis] [COMPLETE] 2130 (1.802430 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:35	Analysis 2131 (Proportion of people with at least one device_exposure record outside a valid observation period) -- START
  |======================================================================| 100%

Executing SQL took 1.96 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:37	[Main Analysis] [COMPLETE] 2131 (1.982211 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:37	Analysis 2132 (Proportion of device_exposure records outside a valid observation period) -- START
  |======================================================================| 100%

Executing SQL took 1.36 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:38	[Main Analysis] [COMPLETE] 2132 (1.373723 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:38	Analysis 2191 (Percentage of total persons that have at least x device exposures) -- START
  |======================================================================| 100%

Executing SQL took 1.32 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:40	[Main Analysis] [COMPLETE] 2191 (1.327106 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:40	Analysis 2200 (Number of persons with at least one note by  note_type_concept_id) -- START
  |======================================================================| 100%

Executing SQL took 4.69 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:44	[Main Analysis] [COMPLETE] 2200 (4.700886 secs)

Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:44	Analysis 2201 (Number of note records, by note_type_concept_id) -- START
  |======================================================================| 100%

Executing SQL took 0.959 secs
Currently in a tryCatch or withCallingHandlers block, so unable to add global calling handlers. ParallelLogger will not capture R messages, errors, and warnings, only explicit calls to ParallelLogger.

2022-08-18 20:04:45	[Main Analysis] [COMPLETE] 2201 (0.969714 secs)

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 184 did not have 6 elements
Traceback:

1. Achilles::achilles(connectionDetails = connectionDetails, cdmDatabaseSchema = "sandbox_gov_hdsb_omop_dev", 
 .     resultsDatabaseSchema = "sandbox_gov_hdsb_omop_dev", vocabDatabaseSchema = "sandbox_gov_hdsb_omop_dev", 
 .     sourceName = "HIAE", cdmVersion = 5.3, numThreads = 1, optimizeAtlasCache = TRUE, 
 .     sqlOnly = FALSE, outputFolder = "/tmp/")
2. lapply(resultsTablesToMerge, function(table) {
 .     .mergeAchillesScratchTables(resultsTable = table, connectionDetails = connectionDetails, 
 .         analysisIds = analysisDetails$ANALYSIS_ID, createTable = createTable, 
 .         schemaDelim = schemaDelim, scratchDatabaseSchema = scratchDatabaseSchema, 
 .         resultsDatabaseSchema = resultsDatabaseSchema, tempEmulationSchema = tempEmulationSchema, 
 .         cdmVersion = cdmVersion, tempAchillesPrefix = tempAchillesPrefix, 
 .         numThreads = numThreads, smallCellCount = smallCellCount, 
 .         outputFolder = outputFolder, sqlOnly = sqlOnly)
 . })
3. FUN(X[[i]], ...)
4. .mergeAchillesScratchTables(resultsTable = table, connectionDetails = connectionDetails, 
 .     analysisIds = analysisDetails$ANALYSIS_ID, createTable = createTable, 
 .     schemaDelim = schemaDelim, scratchDatabaseSchema = scratchDatabaseSchema, 
 .     resultsDatabaseSchema = resultsDatabaseSchema, tempEmulationSchema = tempEmulationSchema, 
 .     cdmVersion = cdmVersion, tempAchillesPrefix = tempAchillesPrefix, 
 .     numThreads = numThreads, smallCellCount = smallCellCount, 
 .     outputFolder = outputFolder, sqlOnly = sqlOnly)
5. lapply(resultsTable$analysisIds[resultsTable$analysisIds %in% 
 .     analysisIds], function(analysisId) {
 .     analysisSql <- SqlRender::render(sql = "select @castedNames from\n                   @scratchDatabaseSchema@schemaDelim@tablePrefix_@analysisId", 
 .         scratchDatabaseSchema = scratchDatabaseSchema, schemaDelim = schemaDelim, 
 .         castedNames = paste(castedNames, collapse = ", "), tablePrefix = resultsTable$tablePrefix, 
 .         analysisId = analysisId)
 .     if (!sqlOnly) {
 .         runTime <- .getAchillesResultBenchmark(analysisId, outputFolder)
 .         benchmarkSelects <- lapply(resultsTable$schema$FIELD_NAME, 
 .             function(c) {
 .                 if (tolower(c) == "analysis_id") {
 .                   sprintf("%d as analysis_id", .getBenchmarkOffset() + 
 .                     as.integer(analysisId))
 .                 }
 .                 else if (tolower(c) == "stratum_1") {
 .                   sprintf("'%s' as stratum_1", runTime)
 .                 }
 .                 else if (tolower(c) == "count_value") {
 .                   sprintf("%d as count_value", smallCellCount + 
 .                     1)
 .                 }
 .                 else {
 .                   sprintf("NULL as %s", c)
 .                 }
 .             })
 .         benchmarkSql <- SqlRender::render(sql = "select @benchmarkSelect", 
 .             benchmarkSelect = paste(benchmarkSelects, collapse = ", "))
 .         analysisSql <- paste(c(analysisSql, benchmarkSql), collapse = " union all ")
 .     }
 .     analysisSql
 . })
6. FUN(X[[i]], ...)
7. .getAchillesResultBenchmark(analysisId, outputFolder)
8. utils::read.table(file = file.path(outputFolder, "log_achilles.txt"), 
 .     header = FALSE, sep = "\t", stringsAsFactors = FALSE)
9. scan(file = file, what = what, sep = sep, quote = quote, dec = dec, 
 .     nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE, 
 .     fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip, 
 .     multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes, 
 .     flush = flush, encoding = encoding, skipNul = skipNul)

**Desktop (please complete the following information):**
- Environment:

$ version

platform       x86_64-conda-linux-gnu      
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out     

$ packageVersion('rlang')

[1] ‘1.0.2.9003’

$ packageVersion('Achilles')

[1] ‘1.7’

- Database: Impala over Hadoop

**Comment by fdefalco** [comment]
See #656
