### ISSUE TITLE
Achilles Pdf documentation 

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Achilles#685]
Hi,

I have a question on the Archilles documentation. 

I seem to recall there was a Achilles.pdf document which provided an overview of the Achilles package. I have review the [user documentation ](https://ohdsi.github.io/Achilles/#user-documentation) section and can' seem to find the document. 

Many thanks,
Solmaz

**Comment by fdefalco** [comment]
Achilles documentation can be found here:

https://ohdsi.github.io/Achilles/
