### ISSUE TITLE
Missing developer documentation

### ISSUE THREAD

**Issue by AshlinHarris** [OHDSI/Achilles#689]
[The Achilles documentation](https://ohdsi.github.io/Achilles/articles/GettingStarted.html#developers-how-to-add-or-modify-analyses) points to [README-developers.html](https://ohdsi.github.io/Achilles/articles/README-developers.html) for information on adding or modifying analyses, but the file is missing.

**Comment by fdefalco** [comment]
Achilles documentation can be found here. 

https://ohdsi.github.io/Achilles/
