### ISSUE TITLE
Achilles does not recognize version 5.4.1

### ISSUE THREAD

**Issue by bmosseveld** [OHDSI/Achilles#702]
**Describe the bug**
Running Achilles on a CDM 5.4.1 database fails in for example query 1203.sql because it doesn't test for version 5.4.1.
It then defaults to the discharge_to_concept_id attribute that is replaced by the discharged_to_concept_id attribute in 5.4 (5.4.0).
Fails also on 1900.sql.

**To Reproduce**
Run Achilles on a 5.4.1 database. Fails with error:

DBMS:
PostgreSQL 14

Error:
org.postgresql.util.PSQLException: ERROR: column vo.discharge_to_concept_id does not exist
  Hint: Perhaps you meant to reference the column "vo.discharged_to_concept_id".
  Position: 106

SQL:
--HINT DISTRIBUTE_ON_KEY(stratum_1)
CREATE TEMP TABLE s_tmpach_1203
AS
SELECT
1203 AS analysis_id,
	CAST(vo.discharge_to_concept_id AS VARCHAR(255)) AS stratum_1,
	CAST(NULL AS VARCHAR(255)) AS stratum_2,
	CAST(NULL AS VARCHAR(255)) AS stratum_3,
	CAST(NULL AS VARCHAR(255)) AS stratum_4,
	CAST(NULL AS VARCHAR(255)) AS stratum_5,
	COUNT(*) AS count_value
FROM
cdm.visit_occurrence vo
JOIN 
	cdm.observation_period op 
ON 
	vo.person_id = op.person_id
AND 
	vo.visit_start_date >= op.observation_period_start_date
AND 
	vo.visit_start_date <= op.observation_period_end_date
WHERE 
	vo.discharge_to_concept_id != 0
GROUP BY 
	vo.discharge_to_concept_id

R version:
R version 4.2.1 (2022-06-23 ucrt)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.7)
- SqlRender (1.12.0)
- DatabaseConnector (6.0.0)

**Expected behavior**
Should use the correct attributes.

**Desktop (please complete the following information):**
 - OS: Windows 11 Professional
 - Browser: NA
 - Version: NA

**Comment by fdefalco** [comment]
I believe the intent is that since major and minor versions should not break compatibility that you should specify 5.4 when running achilles instead of specifying 5.4.1.  Do you encounter the error with that as a setting?

**Comment by bmosseveld** [comment]
That works but if that is the intention test in the queries only for the major part of the version number.

**Comment by fdefalco** [comment]
@AnthonyMolinaro Is there a reason we're testing for the 5.4.0 in the query template?

**Comment by fdefalco** [comment]
I've updated the develop branch to be more consistent in the way it handles versions.  It should now be consistent with only the major and minor version being referenced, (5.3, 5.4)
