### ISSUE TITLE
DashboardExport

### ISSUE THREAD

**Issue by DeborahPh** [OHDSI/Achilles#774]
An error report has been created at  achilles_output/errorReportR.txt
Error in rJava::.jcall(connection@jConnection, "V", "close") : ignoring SIGPIPE signal

```r
DashboardExport::dashboardExport(
+     connectionDetails = connectionDetails,
+     cdmDatabaseSchema = cdmDatabaseSchema,
+     resultsDatabaseSchema = resultsDatabaseSchema,
+     outputFolder = "output",
+     databaseId = databaseId,
+     smallCellCount = 5
```

**Comment by fdefalco** [comment]
Sorry, what is the DashboardExport package?

**Comment by DeborahPh** [comment]
DashboardExport (1.2.1)

**Comment by DeborahPh** [comment]
Hi,
It is running however it has been over 15 hrs and it has not completed, is
that normal?

**Comment by fdefalco** [comment]
I am not familiar with the DashboardExport package. If your question is about duration of execution for the Achilles package, it depends on your infrastructure and size of your CDM. You can track progress in the log file the the execution generates.
