### ISSUE TITLE
Achilles Heel - Non standard concept check

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Achilles#80]
In the V5 heel script, we should check each table for non standard concepts in fields that should only have standard concepts.

**Comment by chrisknoll** [comment]
We just got bit by this with a confusion between VISIT and VISIT_TYPE domains. 

I think the query for this would just be a matter of joining like so:

FROM @cdm_database_schema.CONDITION_OCCURRENCE co
LEFT JOIN @cdm.database_schema.CONCEPT c on co.condition_concept_id = c.concept_id AND c.domain_id = 'CONDITION'
where c.concept_id is null

This should return any rows from CONDITION_OCCURRENCE where the condition_concept_id is not in the CONDITION domain.

**Comment by fdefalco** [comment]
Achilles heel is deprecated in favor of DQD which does now include non-standard concept checks.
