### ISSUE TITLE
Observation Treemap Not Generated in Export To Json

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Achilles#81]
Per this thread:

http://forums.ohdsi.org/t/problem-with-observation-data-on-achilles-and-heracles/1050

The V5 Achilles Observation treemap script should use the domain_id = 'observation' in place of vocabulary_id = 'LOINC'. In general, we should use this approach across all of the treemap scripts.

**Comment by zaijung** [comment]
Hi, I'm SUNGJAE JUNG.

I just replace the code and re-run it. and got the result I expected.

![image](https://cloud.githubusercontent.com/assets/4804957/12343715/a3a29d6e-bb79-11e5-8a66-dc3d500f5b6a.png)

I also think all the treemap script need to be replaced.

Thanks.
