### ISSUE TITLE
v4 heel sql bug

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#85]
i v4 the concept table does not have domain ID
but rule_id 7 expects it

copy of error log

> DBMS:
> redshift
> 
> Error:
> execute JDBC update query failed in dbSendUpdate (ERROR: column c1.domain_id does not exist)
> 
> SQL:
> INSERT INTO ge_cdm4.ACHILLES_HEEL_results (
> 	analysis_id,
> 	ACHILLES_HEEL_warning,
> 	rule_id,
> 	record_count
> 	)
> SELECT or1.analysis_id,
> 	'ERROR: ' || cast(or1.analysis_id as VARCHAR) || '-' || oa1.analysis_name || '; ' || cast(COUNT(DISTINCT stratum_1) AS VARCHAR) || ' concepts in data are not in correct vocabulary' AS ACHILLES_HEEL_warning,
>   7 as rule_id,
>   COUNT(DISTINCT stratum_1) as record_count
> FROM ge_cdm4.ACHILLES_results or1
> INNER JOIN ge_cdm4.ACHILLES_analysis oa1
> 	ON or1.analysis_id = oa1.analysis_id
> INNER JOIN ge_cdm4.concept c1
> 	ON or1.stratum_1 = CAST(c1.concept_id AS VARCHAR)
> WHERE or1.analysis_id IN (2)
> 	AND or1.stratum_1 IS NOT NULL
> 	AND c1.concept_id <> 0 
>   AND lower(c1.domain_id) NOT IN ('gender')
> GROUP BY or1.analysis_id,
> 	oa1.analysis_name
> 
> R version:
> R version 3.2.2 (2015-08-14)
> 
> Platform:
> i386-w64-mingw32
> 
> Attached base packages:
> - stats
> - graphics
> - grDevices
> - utils
> - datasets
> - methods
> - base
> 
> Other attached packages:
> - Achilles (1.0)
> - rjson (0.2.15)
> - DatabaseConnector (1.3.0)
> - RJDBC (0.2-5)
> - rJava (0.9-8)
> - DBI (0.3.1)
> - SqlRender (1.1.3)

**Comment by chrisknoll** [comment]
@vojtechhuser , Looks like this was introduced in commit: 2a2572026c3196bf2a9537fa1871dc7f0af7bd0c. Would you be able to revert those changes to go back to using Vocabulary_id?

**Comment by vojtechhuser** [comment]
I am not sure that that commit introduced it. 
I can remove that rule_id from v4 to make it go away. I think Patrick wrote the rule and could may be the best person to fix it for v4.

**Comment by chrisknoll** [comment]
No, that was the commit, but I can see the changes and I think I can look at how the file was changed in order to determine where domain_id was changed from vocabulary_id. I'll try to fix this (although not sure we have any cdmv4s laying around in order for me to test it...)

**Comment by chrisknoll** [comment]
@vojtechhuser , I've made pull request #88.  Can you please pull that branch 'issue_85_fix' locally, and execute it in your own enviornment?  This should have the proper vocabularyID tests now.

**Comment by vojtechhuser** [comment]
Well. I can try. My development mode is rather primitive. (not using github branches at the moment). But it is a good reason to try them and learn it.
I do have a v4 dataset but I am trying to avoid any v4 and use v5. Last week first v5 in IMEDS arrived. :-)

**Comment by vojtechhuser** [comment]
so I ran this to get that branch

> 
> library(devtools)
> remove.packages('Achilles')
> #install_github("ohdsi/Achilles")
> install_github("ohdsi/Achilles",ref = 'issue_85_fix')
> library(Achilles)

**Comment by vojtechhuser** [comment]
Invalid operation: column c1.vocabular_id does not exist;)

**Comment by blm14** [comment]
Killed by typo! Vocabular_id vs vocabulary_id

**Comment by vojtechhuser** [comment]
rule 7 seems to be fixed.
but rule 12 has the same problem
```


DBMS:
redshift

Error:
execute JDBC update query failed in dbSendUpdate ([Amazon](500310) Invalid operation: column c1.vocabular_id does not exist;)

SQL:
INSERT INTO nih.ACHILLES_HEEL_results (
	analysis_id,
	ACHILLES_HEEL_warning,
	rule_id,
	record_count
	)
SELECT or1.analysis_id,
	'ERROR: ' || cast(or1.analysis_id as VARCHAR) || '-' || oa1.analysis_name || '; ' || cast(COUNT(DISTINCT stratum_1) AS VARCHAR) || ' concepts in data are not in correct vocabulary' AS ACHILLES_HEEL_warning,
  12 as rule_id,
  COUNT(DISTINCT stratum_1) as record_count
FROM nih.ACHILLES_results or1
INNER JOIN nih.ACHILLES_analysis oa1
	ON or1.analysis_id = oa1.analysis_id
INNER JOIN mslr_cdm4.concept c1
	ON or1.stratum_1 = CAST(c1.concept_id AS VARCHAR)
WHERE or1.analysis_id IN (
		400,
		1000
		)
	AND or1.stratum_1 IS NOT NULL
	AND c1.concept_id <> 0 
  AND c1.vocabular_id NOT IN (0,1)
GROUP BY or1.analysis_id,
	oa1.analysis_name

R version:
R version 3.2.2 (2015-08-14)

Platform:
i386-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- Achilles (1.0)
- readr (0.2.2)
- stringr (1.0.0)
- tidyr (0.4.1)
- magrittr (1.5)
- dplyr (0.4.3)
- plyr (1.8.3)
- rjson (0.2.15)
- DatabaseConnector (1.4.0)
- devtools (1.10.0)
- SqlRender (1.1.3)
- RJDBC (0.2-5)
- rJava (0.9-8)
- DBI (0.3.1)
```

**Comment by vojtechhuser** [comment]
Yeah. a typo ! :-) wow. could have spotted that....

**Comment by chrisknoll** [comment]
Ok, i'll push a new commit, i had to fix these by typing by hand!

**Comment by chrisknoll** [comment]
Ok, i've updated the branch. @vojtechhuser , can you please do your install_git again (using issue_85_fix branch) and see if that fixes the v4 issues.

**Comment by vojtechhuser** [comment]
sorry for late response to this. I see the branch is deleted so it seems to be fixed.
