### ISSUE TITLE
ACHILLES_HEEL_results.record_count type change to BIGINT

### ISSUE THREAD

**Issue by wojszko** [OHDSI/Achilles#86]
Hi,
record_count column in ACHILLES_HEEL_results is INT type, can this be changed to BIGINT, as it is in ACHILLES_results.

Thanks,
Krzysztof

**Comment by vojtechhuser** [comment]
Probably yes. If you know git hub, can you suggest the change directly there and make a pull request?

**Comment by wojszko** [comment]
OK, done: https://github.com/OHDSI/Achilles/pull/89

**Comment by chrisknoll** [comment]
Thanks, @wojszko .  Merged in.
