### ISSUE TITLE
jdbcDrivers error: no item called "jdbcDrivers" on the search list

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#87]
I got this error when trying to run Achilles.
It worked fine last week and now it does not. 

> > achillesResults <- achilles(connectionDetails, myCdm, "nih", cdmVersion = "5")
> Connecting using Redshift driver
> Error in as.environment(pos) : 
>   no item called "jdbcDrivers" on the search list
> In addition: Warning message:
> In ls(jdbcDrivers) : ‘jdbcDrivers’ converted to character string
>

**Comment by vojtechhuser** [comment]
well. maybe it is gone

**Comment by schuemie** [comment]
Hi Vojtech,

Just checking up on this weird error message. Did you experience it again? Did it go away on its own?

Cheers,
Martijn

**Comment by vojtechhuser** [comment]
It is gone now. I must have had a corrupted R session (after trying to remove and install newest version of databaseconnector package. Thanks for checking even closed issues.

**Comment by chrisknoll** [comment]
I've noticed that if you clear your enviornment in RStudio (but not restart R Session) things get wiped out (such as a jdbc driver list). Restarting the session seems to reinialize the package and then all is well again until you cear your environment.
