### ISSUE TITLE
Separate vocabulary schema

### ISSUE THREAD

**Issue by aaron0browne** [OHDSI/Achilles#90]
I'm running Achilles on a PostgreSQL database where the vocabulary is in a different schema from the data. As it stands, this will fail when the Heel checks start to execute and look for the vocabulary tables.

Would anyone be interested in (or simply willing to accept) a PR that added a new `vocabSchema` argument to the `achilles` function, which would default to the `cdmSchema` value, and used that argument to qualify vocabulary tables the SQL scripts?

As far as I can tell by thinking about it, this change should be totally backwards-compatible...

**Comment by chrisknoll** [comment]
Yes, sounds good.  My suggestion on how to implement:

The parameters to Achilles and Achilles heel  take parameters to their calls that look like this:
function (connectionDetails, 
                      cdmDatabaseSchema, 
                      oracleTempSchema = cdmDatabaseSchema,
                      resultsDatabaseSchema = cdmDatabaseSchema, 
                      sourceName = "", 
                      analysisIds, 
                      createTable = TRUE, 
                      smallcellcount = 5, 
                      cdmVersion = "4", 
                      runHeel = TRUE,
                      validateSchema = FALSE){

Just add a new parameter: vocabDatabaseSchema that defaults to the cdmDatabaseSchema.  

Next, all the references to the vocabulary tables (.CONCEPT, .CONCEPT_ANCESTOR, etc) in the achilles scripts must be updated.

Additionally: the exportToJson calls also refer to vocabulary tables, so those functions and scripts will need to be updated in the same way.  

This also may need to be adapted across the other tools in the OHDSI suite (circe, calypso) but we'll take that up as a separate issue if it becomes necessary.

**Comment by aaron0browne** [comment]
Great. I'll try to take a swing at it by the end of the week.

**Comment by aaron0browne** [comment]
Just here to say I haven't gotten around to working on this ticket this week. I'll try again next week!

**Comment by chrisknoll** [comment]
Thanks for checking in. let me know if you need any support.

**Comment by aaron0browne** [comment]
See #91.

**Comment by vojtechhuser** [comment]
IMEDS solves this by making a view in the data schema to the vocabulary.

**Comment by vojtechhuser** [comment]
I think this has now been merged into master and I suggest to close the issue
