### ISSUE TITLE
Consider option to include person counts from descendant concepts in the prevalence reports

### ISSUE THREAD

**Issue by sblyman** [OHDSI/Achilles#94]
I just started running Achilles and reviewing results against a small subset of an administrative claims database and have a question regarding the reports with prevalence counts (e.g. Drug Exposures, Conditions and Procedures).  Within Achilles_v5.sql, the prevalence counts are based on exact matches with a single concept and do not take into consideration the potential of additional persons associated with any descendant concepts (via the concept_ancestor table).  I am curious as to the reasoning and would you consider enhancing the reports to have an option to include the person counts from descendant concepts?

**Comment by vojtechhuser** [comment]
There is discussion about being able to have "derived analyses".
What you propose could be derived from the current execution using the vocabulary tables.

I hope we reach consensus on the derived analyses some day.

**Comment by alondhe** [comment]
This is currently shown in Atlas in terms of RC and DRC, but could be extended to PC and DPC. But the underlying data is in Achilles already, just need to query for it.
