### ISSUE TITLE
sqlAchillesHeel.sql for V4 has an error.

### ISSUE THREAD

**Issue by rfollett** [OHDSI/Achilles#95]
The sqlAchillesHeel.sql code for V4 throws an error because of the @results_database_schema qualifier on lines 1 and 3:

1. select analysis_id as AttributeName, **@results_database_schema.**ACHILLES_HEEL_warning as AttributeValue
3. order by case when left(**@results_database_schema.**ACHILLES_HEEL_warning,5) = 'Error' then 1 else 2 end, analysis_id 

The qualifiers are not present in the V5 code.

**Comment by msuchard** [comment]
Fixed via 02dae20af1fbf8d836603b42174e284d8dca9017
