### ISSUE TITLE
Document in Achilles Results table when Achilles pre-computations were executed

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Achilles#97]
It would be nice if the user can know as of when the counts were generated.

For example, data in IMEDS achilles web are now for dataset prior to the update with 2015 data but it is not possible to tell.

(on a side note)

analysis 0 tries to document source name (but I am not sure we somehow record it. (that is also a non-number). Perhaps overload Stratum_1 varchar column?

**Comment by vojtechhuser** [comment]
I wrote a beta solution to this using R and insert statement from R.
Does SqlRender translate something like Sys.date()    (or sql server way of saying this) into all Db engines?

**Comment by vojtechhuser** [comment]
a version documentation has been implemented. (will add date as well)

**Comment by t-abdul-basser** [comment]
Hi @vojtechhuser. Just so that I can better understand: What do you mean by "version documentation"? Thx.

**Comment by vojtechhuser** [comment]
A user will be able to know if Heel Rules or Achilles analyses from version 1.3 or 1.4 were executed. (basically which version of "achilles knowledge base" was executed)

**Comment by t-abdul-basser** [comment]
Thanx for the clarification! :)
